infiltration_info_texts = {
    'landuse': 'Im ausgewählten Gebiet liegen folgende Formen der Landnutzung vor, die als Versickerungsstandorte in Betracht kommen. Welche möchten Sie für die weitere Planung nutzen?',
    'soil_suitability': 'Die Bewertung der Böden für Versickerungsmaßnahmen basiert auf den folgenden Kriterien. Anhängig von der Landnutzungsform werden diese unterschiedlich kombiniert und gewichtet um den Eignungssindex zu errechnen. Die Gewichtung kann angepasst und das Ergebnis gefiltert werden',
    'natural_sinks': 'Natürliche Senken in der Landschaft können als Versickerungsstandorte genutzt werden. Der Verzicht auf künstliche Versickerungsstrukturen bietet die Möglichkeit den finanziellen und baulichen Aufwand von Maßnahmen zu reduzieren und die Eingliederung in das natürliche Umfeld zu erleichtern. Zur Anpassung an das Planungsvorhaben können die Senken entsprechend ihrer Proportionen selektiert werden.',
    'enlarged_sinks': 'Durch die Restriktion der Bodeneignung können Anteile vereinzelter natürlicher Senken in schlechter geeigneten Gebieten liegen. Entsprechend wurden diese im vorherigen Schritt ausgeblendet. \
        Mit einer weniger konservativen Einstellung der Bodeneignung können diese für den weiteren Planungsprozess genutzt bzw. vergrößert werden. Diese werden im Folgenden als natürlich modifizierte Senken bezeichnet und beinhalten Anteile von Senken mit schlechteren Versickerungs- oder Speichereigenschaften, schließen jedoch weiterhin wichtige Filter wie Kontaminationen oder Landnutzungskonflikte ein.\
        Entsprechend werden große natürliche Senken an einigen Orten von menschlicher Infrastruktur wie Straßen oder Siedlungen begrenzt oder zerteilt. Folglich bilden diese meist kein geschlossenes Becken mehr, was ihre Nutzbarkeit entsprechend einschränkt.\
        Um diese Standorte dennoch als Versickerungsstandorte nutzen zu können, können bauliche Modifikationen vorgenommen werden, um die Senken künstlich zu schließen. Hierfür können dammähnliche Verwallungsstrukturen genutzt werden. Das Potenzial für diese Baumaßnahmen wurde ermittelt und unter dem Begriff „baulich modifizierte Senken“ zusammengefasst. \
        Sowohl natürlich als auch baulich modifizierte Senken können hier gefiltert werden:',
    'construction_sinks': 'Die empfohlenen trapezförmigen Verwallungsstrukturen haben eine Breite von 6 Metern, einen Konstanten Winkel (α) und bilden einen Damm homogener Textur. Entsprechend der natürlichen Umrandung der Senke wurde die maximale Füllhöhe (HW) berechnet und ergibt, inklusive eines Puffers von 0,2 Meter, die Höhe der Verwallung (HV). Hierbei resultiert die Breite des oberen Plateaus der Trapezfläche (P), bei konstantem Winkel (α), aus der Höhe (HV), wobei P > 1,0 Meter.\
        Aus Gründen der Standsicherheit wurde die Höhe der Verwallung (HV) auf 1,2 Meter und die entsprechende maximale Füllhöhe (HW) auf 1,0 Meter begrenzt. Überschreitet die errechnete Füllhöhe (HW) der Senke diesen Wert, wurde diese entsprechend verkleinert',
    
}