# Generated by Django 4.2 on 2023-11-24 14:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboveGroundWaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uezg_id', models.CharField(max_length=100)),
                ('hapt_ezg', models.CharField(max_length=100)),
                ('teil_ezg', models.CharField(max_length=100)),
                ('qru_m3_s', models.FloatField()),
                ('flaeche_m2', models.FloatField()),
                ('bg_id', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=25832)),
            ],
        ),
        migrations.CreateModel(
            name='BelowGroundWaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kennzahl', models.IntegerField()),
                ('gewaesser', models.CharField(max_length=100)),
                ('gew_alias', models.CharField(max_length=255)),
                ('gew_kennz', models.IntegerField()),
                ('beschr_von', models.CharField(max_length=255)),
                ('beschr_bis', models.CharField(max_length=255)),
                ('laenge', models.CharField(max_length=20)),
                ('land', models.CharField(max_length=100)),
                ('ordnung', models.IntegerField()),
                ('fl_art', models.CharField(max_length=100)),
                ('wrrl_kr', models.CharField(max_length=100)),
                ('areea_qkm', models.FloatField()),
                ('area_ha', models.FloatField()),
                ('ezg_id', models.IntegerField()),
                ('bemerkung', models.CharField(max_length=255)),
                ('shape_area', models.FloatField()),
                ('shape_len', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=25832)),
            ],
        ),
    ]
