# Generated by Django 4.2 on 2023-12-04 14:43

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abovegroundwaters',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
