# Generated by Django 4.2 on 2023-12-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_alter_abovegroundwaters_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abovegroundwaters',
            name='bg_id',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='abovegroundwaters',
            name='flaeche_m2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='abovegroundwaters',
            name='hapt_ezg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='abovegroundwaters',
            name='qru_m3_s',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='abovegroundwaters',
            name='teil_ezg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='area_ha',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='areea_qkm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='bemerkung',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='beschr_bis',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='beschr_von',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='ezg_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='fl_art',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='gew_alias',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='gew_kennz',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='gewaesser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='laenge',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='land',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='ordnung',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='shape_area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='shape_len',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='wrrl_kr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
