# Generated by Django 4.2 on 2023-12-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0003_alter_abovegroundwaters_bg_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='belowgroundwaters',
            old_name='areea_qkm',
            new_name='area_qkm',
        ),
        migrations.AddField(
            model_name='belowgroundwaters',
            name='wrrl_bg',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='belowgroundwaters',
            name='wrrl_fge',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='fl_art',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='gew_alias',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='gew_kennz',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='gewaesser',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='kennzahl',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='ordnung',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='belowgroundwaters',
            name='wrrl_kr',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
