# Generated by Django 4.2 on 2023-12-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0004_rename_areea_qkm_belowgroundwaters_area_qkm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belowgroundwaters',
            name='area_qkm',
        ),
    ]
