# Generated by Django 4.2 on 2023-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0005_remove_belowgroundwaters_area_qkm'),
    ]

    operations = [
        migrations.AddField(
            model_name='belowgroundwaters',
            name='area_qkm',
            field=models.FloatField(null=True),
        ),
    ]
