# Generated by Django 4.2 on 2023-12-04 15:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0006_belowgroundwaters_area_qkm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=25833),
        ),
    ]
