# Generated by Django 4.2 on 2024-03-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0008_outlinedrainage_outlinegeste_outlineinfiltratioon_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutlineInfiltratioon',
            new_name='OutlineInfiltration',
        ),
    ]
