# Generated by Django 4.2 on 2024-04-03 11:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0009_rename_outlineinfiltratioon_outlineinfiltration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinksWithLandUseAndSoilProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('objectid', models.IntegerField(null=True)),
                ('fid_sink', models.IntegerField(null=True)),
                ('depth_sink', models.FloatField(null=True)),
                ('area_sink', models.FloatField(null=True)),
                ('index_sink', models.FloatField(null=True)),
                ('index_si_1', models.FloatField(null=True)),
                ('land_use_1', models.CharField(max_length=100, null=True)),
                ('land_use_2', models.CharField(max_length=100, null=True)),
                ('land_use_3', models.CharField(max_length=100, null=True)),
                ('index_soil', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilProperties4326',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('depth_to_groundwater', models.CharField(max_length=100, null=True)),
                ('hydraulic_1m', models.CharField(max_length=100, null=True)),
                ('hydraulic_2m', models.CharField(max_length=100, null=True)),
                ('field_capacity', models.CharField(max_length=100, null=True)),
                ('hydromorph', models.CharField(max_length=100, null=True)),
                ('agriculture', models.CharField(max_length=100, null=True)),
                ('wetness_so', models.CharField(max_length=100, null=True)),
                ('type_of_agriculture', models.CharField(max_length=100, null=True)),
                ('class_land', models.CharField(max_length=100, null=True)),
                ('index_soil', models.FloatField(null=True)),
            ],
        ),
    ]
