# Generated by Django 4.2 on 2024-04-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0010_sinkswithlanduseandsoilproperties_soilproperties4326'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilproperties4326',
            name='nitrate_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilproperties4326',
            name='waterloggi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
