# Generated by Django 4.2 on 2024-04-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0011_soilproperties4326_nitrate_co_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilproperties4326',
            name='depth_to_groundwater_lower',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='soilproperties4326',
            name='depth_to_groundwater_upper',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='soilproperties4326',
            name='nitrate_contamination',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='soilproperties4326',
            name='waterlogging',
            field=models.BooleanField(null=True),
        ),
    ]
