# Generated by Django 4.2 on 2024-04-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0012_soilproperties4326_depth_to_groundwater_lower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilproperties4326',
            name='nitrate_co',
        ),
        migrations.RemoveField(
            model_name='soilproperties4326',
            name='waterloggi',
        ),
    ]
