# Generated by Django 4.2 on 2024-04-04 14:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0014_sinkswithlanduseandsoilpropertiessimplified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinksWithLandUseAndSoilPropertiesAsPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('objectid', models.IntegerField(null=True)),
                ('fid_sink', models.IntegerField(null=True)),
                ('depth_sink', models.FloatField(null=True)),
                ('area_sink', models.FloatField(null=True)),
                ('index_sink', models.FloatField(null=True)),
                ('index_si_1', models.FloatField(null=True)),
                ('land_use_1', models.CharField(max_length=100, null=True)),
                ('land_use_2', models.CharField(max_length=100, null=True)),
                ('land_use_3', models.CharField(max_length=100, null=True)),
                ('index_soil', models.FloatField(null=True)),
            ],
        ),
    ]
