# Generated by Django 4.2 on 2024-04-04 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0015_sinkswithlanduseandsoilpropertiesaspoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=None, srid=4326),
        ),
    ]
