# Generated by Django 4.2 on 2024-04-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0016_alter_sinkswithlanduseandsoilpropertiesaspoints_geom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutlineDrainage',
        ),
    ]
