# Generated by Django 4.2 on 2024-10-11 06:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0017_delete_outlinedrainage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wasserrueckhaltepotentiale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('typ', models.CharField(max_length=100, null=True)),
                ('anmerkung', models.CharField(max_length=255, null=True)),
                ('dokument1', models.CharField(max_length=255, null=True)),
                ('derzeitige_nutzung', models.CharField(max_length=255, null=True)),
                ('quelle_1', models.CharField(max_length=255, null=True)),
                ('quelle_2', models.CharField(max_length=255, null=True)),
                ('quelle_3', models.CharField(max_length=255, null=True)),
                ('massnahmen_id', models.IntegerField(null=True)),
                ('gewaesserverwaltung', models.CharField(max_length=255, null=True)),
                ('gewaesser_name', models.CharField(max_length=255, null=True)),
                ('flaeche_m2', models.FloatField(null=True)),
                ('kartenquelle', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
