# Generated by Django 4.2 on 2024-10-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0018_wasserrueckhaltepotentiale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasserrueckhaltepotentiale',
            name='massnahmen_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
