# Generated by Django 4.2 on 2024-10-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0019_alter_wasserrueckhaltepotentiale_massnahmen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinkswithlanduseandsoilproperties',
            name='landuse_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilproperties',
            name='landuse_1_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilproperties',
            name='landuse_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilproperties',
            name='landuse_2_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilproperties',
            name='landuse_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilproperties',
            name='landuse_3_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='landuse_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='landuse_1_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='landuse_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='landuse_2_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='landuse_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='landuse_3_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='landuse_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='landuse_1_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='landuse_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='landuse_2_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='landuse_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='landuse_3_percent',
            field=models.FloatField(null=True),
        ),
    ]
