# Generated by Django 4.2 on 2024-10-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0020_sinkswithlanduseandsoilproperties_landuse_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilproperties',
            name='land_use_1',
        ),
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilproperties',
            name='land_use_2',
        ),
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilproperties',
            name='land_use_3',
        ),
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='land_use_1',
        ),
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='land_use_2',
        ),
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='land_use_3',
        ),
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='land_use_1',
        ),
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='land_use_2',
        ),
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='land_use_3',
        ),
    ]
