# Generated by Django 4.2 on 2024-10-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0022_sinkswithlanduseandsoilproperties_agricultural_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilproperties',
            name='agricultural_a',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilproperties',
            name='farmland',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilproperties',
            name='forest_conifer',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilproperties',
            name='forest_conifers',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilproperties',
            name='forest_deciduous_trees',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilproperties',
            name='grassland',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilproperties',
            name='heath',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilproperties',
            name='orchard_meadow',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilproperties',
            name='vegetation',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilproperties',
            name='woody_area',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='agricultural_a',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='farmland',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='forest_conifer',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='forest_conifers',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='forest_deciduous_trees',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='grassland',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='heath',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='orchard_meadow',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='vegetation',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='woody_area',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='agricultural_a',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='farmland',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='forest_conifer',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='forest_conifers',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='forest_deciduous_trees',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='grassland',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='heath',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='orchard_meadow',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='vegetation',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='woody_area',
            field=models.FloatField(default=0, null=True),
        ),
    ]
