# Generated by Django 4.2 on 2024-10-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0023_alter_sinkswithlanduseandsoilproperties_agricultural_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinkswithlanduseandsoilproperties',
            old_name='agricultural_a',
            new_name='agricultural_area_without_information',
        ),
        migrations.RenameField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            old_name='agricultural_a',
            new_name='agricultural_area_without_information',
        ),
        migrations.RenameField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            old_name='agricultural_a',
            new_name='agricultural_area_without_information',
        ),
    ]
