# Generated by Django 4.2 on 2024-10-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0024_rename_agricultural_a_sinkswithlanduseandsoilproperties_agricultural_area_without_information_and_mo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinkswithlanduseandsoilproperties',
            name='forest_conifers_and_deciduous_trees',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='forest_conifers_and_deciduous_trees',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='forest_conifers_and_deciduous_trees',
            field=models.FloatField(default=0, null=True),
        ),
    ]
