# Generated by Django 4.2 on 2024-10-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0025_sinkswithlanduseandsoilproperties_forest_conifers_and_deciduous_trees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilproperties',
            name='forest_conifer',
        ),
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilpropertiesaspoints',
            name='forest_conifer',
        ),
        migrations.RemoveField(
            model_name='sinkswithlanduseandsoilpropertiessimplified',
            name='forest_conifer',
        ),
    ]
