# Generated by Django 4.2 on 2024-12-02 15:58

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolbox', '0026_remove_sinkswithlanduseandsoilproperties_forest_conifer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='area',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='user',
        ),
        migrations.AddField(
            model_name='userproject',
            name='calculation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='calculation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='calculation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='UserField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('geom_json', djgeojson.fields.PolygonField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_userfields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userproject',
            name='toolbox_field',
            field=models.ForeignKey(default=399, on_delete=django.db.models.deletion.CASCADE, to='toolbox.userfield'),
            preserve_default=False,
        ),
    ]
