# Generated by Django 4.2 on 2024-12-03 09:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0028_aquifer_dataenlargedsinks_datalakes_datastreams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid_sink', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('depth', models.FloatField(null=True)),
                ('area', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('index_1', models.FloatField(null=True)),
                ('index_2', models.FloatField(null=True)),
                ('index_3', models.FloatField(null=True)),
                ('land_use_1', models.CharField(max_length=100, null=True)),
                ('land_use_2', models.CharField(max_length=100, null=True)),
                ('land_use_3', models.CharField(max_length=100, null=True)),
                ('index_soil', models.FloatField(null=True)),
                ('shape_length', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
            ],
        ),
    ]
