# Generated by Django 4.2 on 2024-12-03 10:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0029_datasinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquifer',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='dataenlargedsinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
        migrations.AlterField(
            model_name='datalakes',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
        migrations.AlterField(
            model_name='datasinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
        migrations.AlterField(
            model_name='datastreams',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=25833),
        ),
        migrations.AlterField(
            model_name='extractionpointsenlargedsinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=25833),
        ),
        migrations.AlterField(
            model_name='extractionpointssinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=25833),
        ),
        migrations.AlterField(
            model_name='feasability',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='feasabilityenlargedsinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='feasabilitysinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='hydrogeology',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='hydrogeologyenlargedsinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
        migrations.AlterField(
            model_name='hydrogeologysinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
        migrations.AlterField(
            model_name='inletpointsenlargedsinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=25833),
        ),
        migrations.AlterField(
            model_name='inletpointssinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=25833),
        ),
        migrations.AlterField(
            model_name='landusedissolve',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
        migrations.AlterField(
            model_name='sinkembankment',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
        migrations.AlterField(
            model_name='soilproperties',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
    ]
