# Generated by Django 4.2 on 2024-12-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0030_alter_aquifer_geom_alter_dataenlargedsinks_geom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='por_length',
            field=models.FloatField(null=True),
        ),
    ]
