# Generated by Django 4.2 on 2024-12-03 11:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0031_dataenlargedsinks_por_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionpointsenlargedsinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=25833),
        ),
        migrations.AlterField(
            model_name='extractionpointssinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=25833),
        ),
        migrations.AlterField(
            model_name='inletpointsenlargedsinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=25833),
        ),
        migrations.AlterField(
            model_name='inletpointssinks',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=25833),
        ),
    ]
