# Generated by Django 4.2 on 2024-12-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0032_alter_extractionpointsenlargedsinks_geom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrogeology',
            name='aqufer_id',
        ),
    ]
