# Generated by Django 4.2 on 2024-12-03 15:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0033_remove_hydrogeology_aqufer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquifer',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='datalakes',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='datasinks',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='feasability',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='feasabilityenlargedsinks',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='feasabilitysinks',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='hydrogeology',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='hydrogeologyenlargedsinks',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='hydrogeologysinks',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='landusedissolve',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='sinkembankment',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
    ]
