# Generated by Django 4.2 on 2024-12-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0034_aquifer_centroid_dataenlargedsinks_centroid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='toolbox_field',
        ),
        migrations.AddField(
            model_name='userproject',
            name='user_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_userprojects', to='toolbox.userfield'),
            preserve_default=False,
        ),
    ]
