# Generated by Django 4.2 on 2024-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0035_remove_userproject_toolbox_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilproperties',
            name='c_suit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
