# Generated by Django 4.2 on 2024-12-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0036_soilproperties_c_suit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilproperties',
            name='ag_soil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soilproperties',
            name='fiecap',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soilproperties',
            name='hycon_2m',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soilproperties',
            name='hydro',
            field=models.CharField(max_length=100),
        ),
    ]
