# Generated by Django 4.2 on 2024-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0037_alter_soilproperties_ag_soil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilproperties',
            name='hycon_1m',
            field=models.CharField(max_length=50),
        ),
    ]
