# Generated by Django 4.2 on 2024-12-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0038_alter_soilproperties_hycon_1m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasinks',
            name='id',
        ),
        migrations.AlterField(
            model_name='datasinks',
            name='fid_sink',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
