# Generated by Django 4.2 on 2024-12-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0019_remove_mapsoilclc_clc'),
        ('toolbox', '0039_remove_datasinks_id_alter_datasinks_fid_sink'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='landusedissolve',
            name='corine_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='landusedissolve',
            name='corine_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='landusedissolve',
            name='corine_land_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buek.corinelandcover2018'),
        ),
    ]
