# Generated by Django 4.2 on 2024-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0040_landusage_landusedissolve_corine_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusedissolve',
            name='corine_3',
            field=models.IntegerField(null=True),
        ),
    ]
