# Generated by Django 4.2 on 2024-12-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0041_landusedissolve_corine_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landusedissolve',
            old_name='veg_01_f',
            new_name='name',
        ),
    ]
