# Generated by Django 4.2 on 2024-12-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0042_rename_veg_01_f_landusedissolve_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landusedissolve',
            old_name='veg_01_f_v',
            new_name='name_v',
        ),
    ]
