# Generated by Django 4.2 on 2024-12-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0043_rename_veg_01_f_v_landusedissolve_name_v'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landusedissolve',
            name='veg_02_f',
        ),
        migrations.RemoveField(
            model_name='landusedissolve',
            name='veg_02_f_v',
        ),
        migrations.RemoveField(
            model_name='landusedissolve',
            name='veg_03_f',
        ),
        migrations.RemoveField(
            model_name='landusedissolve',
            name='veg_04_f',
        ),
    ]
