# Generated by Django 4.2 on 2024-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0044_remove_landusedissolve_veg_02_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasinks',
            name='feasibility_sinks_index',
            field=models.FloatField(null=True),
        ),
    ]
