# Generated by Django 4.2 on 2024-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0045_datasinks_feasibility_sinks_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeasabilitySinks',
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='feasibilty_enlarged_sinks_index',
            field=models.FloatField(null=True),
        ),
    ]
