# Generated by Django 4.2 on 2024-12-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0046_delete_feasabilitysinks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataLakes',
            new_name='Lakes',
        ),
        migrations.RenameModel(
            old_name='DataStreams',
            new_name='Streams',
        ),
        migrations.DeleteModel(
            name='Aquifer',
        ),
    ]
