# Generated by Django 4.2 on 2024-12-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0047_rename_datalakes_lakes_rename_datastreams_streams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lakes',
            name='id_lake',
        ),
    ]
