# Generated by Django 4.2 on 2024-12-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0048_remove_lakes_id_lake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionpointssinks',
            name='id_lake',
        ),
        migrations.AddField(
            model_name='extractionpointssinks',
            name='lake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.lakes'),
        ),
    ]
