# Generated by Django 4.2 on 2024-12-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0049_remove_extractionpointssinks_id_lake_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasinks',
            old_name='fid_sink',
            new_name='id',
        ),
    ]
