# Generated by Django 4.2 on 2024-12-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0050_rename_fid_sink_datasinks_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydrogeologysinks',
            old_name='fid_sink',
            new_name='sink',
        ),
    ]
