# Generated by Django 4.2 on 2024-12-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0051_rename_fid_sink_hydrogeologysinks_sink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSinks',
            new_name='Sink',
        ),
    ]
