# Generated by Django 4.2 on 2024-12-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0052_rename_datasinks_sink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrogeologysinks',
            name='sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.sink'),
        ),
    ]
