# Generated by Django 4.2 on 2024-12-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0019_remove_mapsoilclc_clc'),
        ('toolbox', '0053_alter_hydrogeologysinks_sink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandUseDissolve',
            new_name='LandUse',
        ),
    ]
