# Generated by Django 4.2 on 2024-12-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0054_rename_landusedissolve_landuse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streams',
            name='id_source',
        ),
    ]
