# Generated by Django 4.2 on 2024-12-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0055_remove_streams_id_source'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Streams',
            new_name='Stream',
        ),
    ]
