# Generated by Django 4.2 on 2024-12-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0056_rename_streams_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionpointssinks',
            old_name='fid_sink',
            new_name='sink',
        ),
    ]
