# Generated by Django 4.2 on 2024-12-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0058_alter_extractionpointssinks_sink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionpointssinks',
            name='id_source',
        ),
        migrations.AddField(
            model_name='extractionpointssinks',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.stream'),
        ),
    ]
