# Generated by Django 4.2 on 2024-12-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0059_remove_extractionpointssinks_id_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionpointssinks',
            name='lake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.lakes'),
        ),
        migrations.AlterField(
            model_name='extractionpointssinks',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.stream'),
        ),
    ]
