# Generated by Django 4.2 on 2024-12-17 16:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0060_alter_extractionpointssinks_lake_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalElevationModel10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=25833)),
                ('extent', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833)),
            ],
        ),
    ]
