# Generated by Django 4.2 on 2025-03-18 15:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0061_digitalelevationmodel10'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('calculation_start_date', models.DateField(blank=True, null=True)),
                ('calculation_end_date', models.DateField(blank=True, null=True)),
                ('calculation', models.JSONField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('toolbox_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.toolboxtype')),
            ],
        ),
        migrations.DeleteModel(
            name='SoilProperties4326',
        ),
        migrations.AlterField(
            model_name='userfield',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=25833),
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
        migrations.AddField(
            model_name='toolboxproject',
            name='user_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.userfield'),
        ),
    ]
