# Generated by Django 4.2 on 2025-03-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0063_toolboxproject_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolboxproject',
            old_name='comment',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='toolboxproject',
            name='calculation',
        ),
        migrations.RemoveField(
            model_name='toolboxproject',
            name='calculation_end_date',
        ),
        migrations.RemoveField(
            model_name='toolboxproject',
            name='calculation_start_date',
        ),
        migrations.AddField(
            model_name='toolboxproject',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
