# Generated by Django 4.2 on 2025-03-19 15:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0064_rename_comment_toolboxproject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_fid_sink',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_id_lake',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_id_source',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_index_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_index_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_index_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_max_sv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_mean_sv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_min_sv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_vol_sink',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_weight_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='ep_weight_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataenlargedsinks',
            name='extractionpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.extractionpointsenlargedsinks'),
        ),
    ]
