# Generated by Django 4.2 on 2025-03-20 12:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0065_dataenlargedsinks_ep_distance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SinksWithLandUseAndSoilProperties',
        ),
        migrations.DeleteModel(
            name='SinksWithLandUseAndSoilPropertiesAsPoints',
        ),
        migrations.DeleteModel(
            name='SinksWithLandUseAndSoilPropertiesSimplified',
        ),
        migrations.RemoveField(
            model_name='dataenlargedsinks',
            name='id',
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_index_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_index_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_index_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_lake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.lakes'),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_max_sv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_mean_sv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_min_sv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_sink',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.stream'),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_vol_sink',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_weight_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='ep_weight_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dataenlargedsinks',
            name='fid_sink',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
