# Generated by Django 4.2 on 2025-03-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0066_delete_sinkswithlanduseandsoilproperties_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEnlargedSinks',
            new_name='EnlargedSinks',
        ),
    ]
