# Generated by Django 4.2 on 2025-03-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0067_rename_dataenlargedsinks_enlargedsinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrogeologyenlargedsinks',
            name='enlarged_sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.enlargedsinks'),
        ),
    ]
