# Generated by Django 4.2 on 2025-03-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0068_hydrogeologyenlargedsinks_enlarged_sink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrogeologyenlargedsinks',
            name='enlarged_sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.enlargedsinks'),
        ),
    ]
