# Generated by Django 4.2 on 2025-03-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0069_alter_hydrogeologyenlargedsinks_enlarged_sink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrogeologyenlargedsinks',
            name='fid_sink',
        ),
    ]
