# Generated by Django 4.2 on 2025-03-24 14:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0071_sink4326'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlargedSinks4326',
            fields=[
                ('fid_sink', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833)),
                ('depth', models.FloatField(null=True)),
                ('area', models.FloatField(null=True)),
                ('nat_length', models.FloatField(null=True)),
                ('por_length', models.FloatField(null=True)),
                ('con_length', models.FloatField(null=True)),
                ('sink_type', models.CharField(max_length=100, null=True)),
                ('volume', models.FloatField(null=True)),
                ('vol_ba_con', models.FloatField(null=True)),
                ('gained_vol', models.FloatField(null=True)),
                ('con_eff', models.FloatField(null=True)),
                ('index_1', models.FloatField(null=True)),
                ('index_2', models.FloatField(null=True)),
                ('index_3', models.FloatField(null=True)),
                ('land_use_1', models.CharField(max_length=100, null=True)),
                ('land_use_2', models.CharField(max_length=100, null=True)),
                ('land_use_3', models.CharField(max_length=100, null=True)),
                ('land_use_4', models.CharField(max_length=100, null=True)),
                ('index_soil', models.FloatField(null=True)),
                ('shape_length', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('feasibilty_enlarged_sinks_index', models.FloatField(null=True)),
                ('ep_geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=25833)),
                ('ep_fid_sink', models.IntegerField(null=True)),
                ('ep_id_source', models.IntegerField(null=True)),
                ('ep_id_lake', models.IntegerField(null=True)),
                ('ep_distance', models.FloatField(null=True)),
                ('ep_min_sv', models.FloatField(null=True)),
                ('ep_mean_sv', models.FloatField(null=True)),
                ('ep_max_sv', models.FloatField(null=True)),
                ('ep_vol_sink', models.FloatField(null=True)),
                ('ep_index_1', models.FloatField(null=True)),
                ('ep_weight_1', models.FloatField(null=True)),
                ('ep_index_2', models.FloatField(null=True)),
                ('ep_weight_2', models.FloatField(null=True)),
                ('ep_index_3', models.FloatField(null=True)),
                ('extractionpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.extractionpointsenlargedsinks')),
            ],
        ),
    ]
