# Generated by Django 4.2 on 2025-03-24 14:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0072_enlargedsinks4326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lakes4326',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833)),
                ('shape_length', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('min_sv', models.FloatField()),
                ('mean_sv', models.FloatField()),
                ('max_sv', models.FloatField()),
                ('plus_days', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stream4326',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=25833)),
                ('shape_length', models.FloatField()),
                ('min_sv', models.FloatField()),
                ('mean_sv', models.FloatField()),
                ('max_sv', models.FloatField()),
                ('plus_days', models.FloatField()),
            ],
        ),
    ]
