# Generated by Django 4.2 on 2025-03-24 14:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0073_lakes4326_stream4326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfield',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
