# Generated by Django 4.2 on 2025-03-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0074_alter_userfield_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilproperties',
            name='waterlog',
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='depth_gw_lower_limit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='depth_gw_upper_limit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
