# Generated by Django 4.2 on 2025-03-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0075_remove_soilproperties_waterlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilproperties',
            name='depth_gw',
        ),
        migrations.AlterField(
            model_name='soilproperties',
            name='depth_gw_lower_limit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='soilproperties',
            name='depth_gw_upper_limit',
            field=models.FloatField(null=True),
        ),
    ]
