# Generated by Django 4.2 on 2025-03-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0076_remove_soilproperties_depth_gw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilproperties',
            old_name='c_hycon_1m',
            new_name='c_hydraulic_conductivity_1m',
        ),
        migrations.RenameField(
            model_name='soilproperties',
            old_name='c_hycon_2m',
            new_name='c_hydraulic_conductivity_2m',
        ),
        migrations.RenameField(
            model_name='soilproperties',
            old_name='hycon_1m',
            new_name='hydraulic_conductivity_1m',
        ),
        migrations.RenameField(
            model_name='soilproperties',
            old_name='hycon_2m',
            new_name='hydraulic_conductivity_2m',
        ),
        migrations.RenameField(
            model_name='soilproperties',
            old_name='w_hycon_1m',
            new_name='w_hydraulic_conductivity_1m',
        ),
        migrations.RenameField(
            model_name='soilproperties',
            old_name='w_hycon_2m',
            new_name='w_hydraulic_conductivity_2m',
        ),
    ]
