# Generated by Django 4.2 on 2025-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0077_rename_c_hycon_1m_soilproperties_c_hydraulic_conductivity_1m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hydraulic_conductivity_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_limit', models.FloatField()),
                ('lower_limit', models.FloatField()),
                ('class_name', models.CharField(max_length=50)),
                ('rating_index', models.FloatField()),
            ],
        ),
    ]
