# Generated by Django 4.2 on 2025-03-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0078_hydraulic_conductivity_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilproperties',
            name='w_hydraulic_conductivity_1m',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='w_hydraulic_conductivity_2m',
        ),
        migrations.AlterField(
            model_name='hydraulic_conductivity_class',
            name='lower_limit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hydraulic_conductivity_class',
            name='upper_limit',
            field=models.FloatField(null=True),
        ),
    ]
