# Generated by Django 4.2 on 2025-03-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0079_remove_soilproperties_w_hydraulic_conductivity_1m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilproperties',
            name='ag_use_fields',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='ag_use_forest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='ag_use_grassland',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='ag_use_no_agriculture',
            field=models.IntegerField(default=0),
        ),
    ]
