# Generated by Django 4.2 on 2025-03-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0080_soilproperties_ag_use_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilproperties',
            name='ag_use_forest',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='c_land_use',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='w_ag_soil',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='w_fiecap',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='w_hydro',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='w_wet_gras',
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='nitrate_contamination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='waterlog',
            field=models.BooleanField(default=False),
        ),
    ]
