# Generated by Django 4.2 on 2025-03-26 07:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0022_rename_area_percenteage_soilprofile_area_percentage'),
        ('toolbox', '0081_remove_soilproperties_ag_use_forest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUse4326',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833)),
                ('name', models.CharField(max_length=50)),
                ('name_v', models.CharField(max_length=50)),
                ('index_land', models.IntegerField()),
                ('corine_1', models.IntegerField(null=True)),
                ('corine_2', models.IntegerField(null=True)),
                ('corine_3', models.IntegerField(null=True)),
                ('corine_land_cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buek.corinelandcover2018')),
            ],
        ),
        migrations.DeleteModel(
            name='LandUsage',
        ),
    ]
