# Generated by Django 4.2 on 2025-03-26 07:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0082_landuse4326_delete_landusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuse4326',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='landuse4326',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
