# Generated by Django 4.2 on 2025-03-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0083_alter_landuse4326_centroid_alter_landuse4326_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuse',
            name='code_18',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
