# Generated by Django 4.2 on 2025-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0085_landuse_buek_corine_land_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='sink',
            name='land_use_1_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='land_use_2_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='land_use_3_percentage',
            field=models.FloatField(null=True),
        ),
    ]
