# Generated by Django 4.2 on 2025-03-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0086_sink_land_use_1_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsinks',
            name='land_use_1_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='enlargedsinks',
            name='land_use_2_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='enlargedsinks',
            name='land_use_3_percentage',
            field=models.FloatField(null=True),
        ),
    ]
