# Generated by Django 4.2 on 2025-03-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0022_rename_area_percenteage_soilprofile_area_percentage'),
        ('toolbox', '0087_enlargedsinks_land_use_1_percentage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandUse',
            new_name='LandUseMap',
        ),
    ]
