# Generated by Django 4.2 on 2025-03-26 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0088_rename_landuse_landusemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_v', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='landusemap',
            name='landuse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.landuse'),
        ),
    ]
