# Generated by Django 4.2 on 2025-03-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0089_landuse_landusemap_landuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuse',
            name='clc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
