# Generated by Django 4.2 on 2025-03-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0090_landuse_clc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landusemap',
            name='corine_land_cover',
        ),
    ]
