# Generated by Django 4.2 on 2025-03-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0092_remove_landusemap_buek_corine_land_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilproperties',
            name='landuse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.landuse'),
        ),
    ]
