# Generated by Django 4.2 on 2025-03-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0093_soilproperties_landuse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hydraulic_conductivity_class',
            new_name='HydraulicConductivityClass',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='c_nitrate',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='c_waterlog',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='nitrate',
        ),
    ]
