# Generated by Django 4.2 on 2025-03-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0094_rename_hydraulic_conductivity_class_hydraulicconductivityclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilproperties',
            name='hydraulic_conductivity_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hydraulic_conductivity_1m', to='toolbox.hydraulicconductivityclass'),
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='hydraulic_conductivity_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hydraulic_conductivity_2m', to='toolbox.hydraulicconductivityclass'),
        ),
    ]
