# Generated by Django 4.2 on 2025-03-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0095_soilproperties_hydraulic_conductivity_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundWaterDepthyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_limit', models.FloatField(null=True)),
                ('lower_limit', models.FloatField(null=True)),
                ('class_name', models.CharField(max_length=50)),
                ('rating_index', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='hydraulic_conductivity_1m',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='hydraulic_conductivity_2m',
        ),
    ]
