# Generated by Django 4.2 on 2025-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0096_groundwaterdepthyclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundWaterDepthClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_limit', models.FloatField(null=True)),
                ('lower_limit', models.FloatField(null=True)),
                ('class_name', models.CharField(max_length=50, null=True)),
                ('rating_index', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='GroundWaterDepthyClass',
        ),
    ]
