# Generated by Django 4.2 on 2025-03-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0097_groundwaterdepthclass_delete_groundwaterdepthyclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydraulicconductivityclass',
            name='lower_limit',
        ),
        migrations.RemoveField(
            model_name='hydraulicconductivityclass',
            name='upper_limit',
        ),
        migrations.AddField(
            model_name='hydraulicconductivityclass',
            name='hydraulic_conductivity',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
