# Generated by Django 4.2 on 2025-03-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0098_remove_hydraulicconductivityclass_lower_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilproperties',
            name='hydraulic_conductivity_1',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='hydraulic_conductivity_2',
        ),
        migrations.DeleteModel(
            name='HydraulicConductivityClass',
        ),
    ]
