# Generated by Django 4.2 on 2025-03-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0099_remove_soilproperties_hydraulic_conductivity_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilproperties',
            old_name='c_hydraulic_conductivity_1m',
            new_name='hydraulic_conductivity_1m_rating',
        ),
    ]
