# Generated by Django 4.2 on 2025-03-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0100_rename_c_hydraulic_conductivity_1m_soilproperties_hydraulic_conductivity_1m_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_vol', models.IntegerField(blank=True, choices=[(None, 'No Data'), (0, '< 13 vol.%'), (13, '< 26 vol.%'), (26, '< 39 vol.%'), (39, '< 52 vol.%'), (52, '> 52 vol.%')], help_text='Minimum soil volume percentage', null=True)),
                ('partially_min_vol', models.IntegerField(blank=True, choices=[(None, 'No Partial Data'), (13, '< 13 vol.%'), (26, '< 26 vol.%'), (39, '< 39 vol.%'), (52, '< 52 vol.%')], help_text='Partially lower than', null=True)),
                ('partially_max_vol', models.IntegerField(blank=True, choices=[(None, 'No Partial Data'), (13, '> 13 vol.%'), (26, '> 26 vol.%'), (39, '> 39 vol.%'), (52, '> 52 vol.%')], help_text='Partially greater than', null=True)),
                ('lack_of_data', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FieldCapacityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_limit', models.FloatField(null=True)),
                ('lower_limit', models.FloatField(null=True)),
                ('class_name', models.CharField(max_length=50, null=True)),
                ('rating_index', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='soilproperties',
            old_name='c_hydraulic_conductivity_2m',
            new_name='hydraulic_conductivity_2m_rating',
        ),
    ]
