# Generated by Django 4.2 on 2025-03-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0101_fieldcapacity_fieldcapacityclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcapacity',
            name='max_vol',
            field=models.IntegerField(blank=True, choices=[(None, ''), (52, '> 52 vol.%')], help_text='Maximum soil volume percentage', null=True),
        ),
    ]
