# Generated by Django 4.2 on 2025-03-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0102_fieldcapacity_max_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcapacity',
            name='field_capacity_index',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldcapacity',
            name='max_vol',
            field=models.IntegerField(blank=True, choices=[(None, 'No Data'), (52, '> 52 vol.%')], help_text='Maximum soil volume percentage', null=True),
        ),
    ]
