# Generated by Django 4.2 on 2025-03-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0103_fieldcapacity_field_capacity_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilproperties',
            name='fieldcapacity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.fieldcapacity'),
        ),
    ]
