# Generated by Django 4.2 on 2025-03-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0104_soilproperties_fieldcapacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hydromoprhy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating_index', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='fieldcapacity',
            old_name='field_capacity_index',
            new_name='rating_index',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='c_fiecap',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='fiecap',
        ),
    ]
