# Generated by Django 4.2 on 2025-03-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0105_hydromoprhy_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hydromoprhy',
            new_name='Hydromorphy',
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='hydromorphy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.hydromorphy'),
        ),
    ]
