# Generated by Django 4.2 on 2025-03-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0106_rename_hydromoprhy_hydromorphy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating_index', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='c_hydro',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='hydro',
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='soil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.soil'),
        ),
    ]
