# Generated by Django 4.2 on 2025-03-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0107_soil_remove_soilproperties_c_hydro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalLanduse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='ag_soil',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='ag_use_fields',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='ag_use_grassland',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='ag_use_no_agriculture',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='c_ag_soil',
        ),
    ]
