# Generated by Django 4.2 on 2025-03-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0108_agriculturallanduse_remove_soilproperties_ag_soil_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroundWaterDepthClass',
            new_name='GroundWaterDinstanceClass',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='w_soil',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='w_suit_gw',
        ),
    ]
