# Generated by Django 4.2 on 2025-03-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0109_rename_groundwaterdepthclass_groundwaterdinstanceclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilproperties',
            name='groundwater_distance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.groundwaterdinstanceclass'),
        ),
    ]
