# Generated by Django 4.2 on 2025-03-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0110_soilproperties_groundwater_distance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroundWaterDinstanceClass',
            new_name='GroundWaterDistanceClass',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='c_depth_gw',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='depth_gw_lower_limit',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='depth_gw_upper_limit',
        ),
    ]
