# Generated by Django 4.2 on 2025-03-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0111_rename_groundwaterdinstanceclass_groundwaterdistanceclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WetGrassland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating_index', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='soilproperties',
            name='wet_grassland',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.wetgrassland'),
        ),
    ]
