# Generated by Django 4.2 on 2025-03-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0112_wetgrassland_soilproperties_wet_grassland'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilproperties',
            name='agricultural_landuse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.agriculturallanduse'),
        ),
    ]
