# Generated by Django 4.2 on 2025-03-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0113_soilproperties_agricultural_landuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinkWeighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.FloatField(default=0.2)),
                ('soil', models.FloatField(default=0.8)),
                ('field_capacity', models.FloatField(default=0.33)),
                ('hydro_conduct_1m', models.FloatField(default=0.33)),
                ('hydro_conduct_2m', models.FloatField(default=0.33)),
                ('hydromorphy', models.FloatField(default=0.33)),
                ('soil_index', models.FloatField(default=0.33)),
                ('grassland_soil_moisture', models.FloatField(default=0.25)),
                ('grassland_field_capacity', models.FloatField(default=0.25)),
                ('grassland_soil_index', models.FloatField(default=0.25)),
                ('grassland_hydromorphy', models.FloatField(default=0.25)),
            ],
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='ag_use',
        ),
    ]
