# Generated by Django 4.2 on 2025-03-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0114_sinkweighting_remove_soilproperties_ag_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infiltration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.sinkweighting')),
            ],
        ),
    ]
