# Generated by Django 4.2 on 2025-04-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0115_infiltration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnlargedSinks',
            new_name='EnlargedSink',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='shape_area',
        ),
    ]
