# Generated by Django 4.2 on 2025-04-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0116_rename_enlargedsinks_enlargedsink_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sink4326',
        ),
    ]
