# Generated by Django 4.2 on 2025-04-02 15:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0118_sink4326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sink4326',
            name='shape_area',
        ),
        migrations.AddField(
            model_name='sink4326',
            name='land_use_1_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink4326',
            name='land_use_2_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink4326',
            name='land_use_3_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sink4326',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='sink4326',
            name='ep_geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='sink4326',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
    ]
