# Generated by Django 4.2 on 2025-04-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0119_remove_sink4326_shape_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sink4326',
        ),
    ]
