# Generated by Django 4.2 on 2025-04-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0121_sink4326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnlargedSinks4326',
        ),
    ]
