# Generated by Django 4.2 on 2025-04-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0122_delete_enlargedsinks4326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='fid_sink',
            new_name='id',
        ),
    ]
