# Generated by Django 4.2 on 2025-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0123_rename_fid_sink_enlargedsink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='constructed_sink',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
