# Generated by Django 4.2 on 2025-04-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0124_enlargedsink_constructed_sink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsink',
            name='sink_type',
        ),
    ]
