# Generated by Django 4.2 on 2025-04-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0125_remove_enlargedsink_sink_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='vol_ba_con',
            new_name='vol_construction_barrier',
        ),
    ]
