# Generated by Django 4.2 on 2025-04-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0126_rename_vol_ba_con_enlargedsink_vol_construction_barrier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='vol_construction_barrier',
            new_name='volume_construction_barrier',
        ),
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='gained_vol',
            new_name='volume_gained',
        ),
    ]
