# Generated by Django 4.2 on 2025-04-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0127_rename_vol_construction_barrier_enlargedsink_volume_construction_barrier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='con_eff',
            new_name='construction_efficiciency',
        ),
    ]
