# Generated by Django 4.2 on 2025-04-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0128_rename_con_eff_enlargedsink_construction_efficiciency'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='land_use_4_percentage',
            field=models.FloatField(null=True),
        ),
    ]
