# Generated by Django 4.2 on 2025-04-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0130_enlargedsink4326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='ep_min_sv',
            new_name='ep_min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='enlargedsink4326',
            old_name='ep_min_sv',
            new_name='ep_min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='extractionpointsenlargedsinks',
            old_name='min_sv',
            new_name='min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='extractionpointssinks',
            old_name='min_sv',
            new_name='min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='inletpointsenlargedsinks',
            old_name='min_sv',
            new_name='min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='inletpointssinks',
            old_name='min_sv',
            new_name='min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='min_sv',
            new_name='min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='lakes4326',
            old_name='min_sv',
            new_name='min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='sink',
            old_name='ep_min_sv',
            new_name='ep_min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='sink4326',
            old_name='ep_min_sv',
            new_name='ep_min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='min_sv',
            new_name='min_surplus_volume',
        ),
        migrations.RenameField(
            model_name='stream4326',
            old_name='min_sv',
            new_name='min_surplus_volume',
        ),
    ]
