# Generated by Django 4.2 on 2025-04-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0131_rename_ep_min_sv_enlargedsink_ep_min_surplus_volume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='ep_mean_sv',
            new_name='ep_mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='enlargedsink4326',
            old_name='ep_mean_sv',
            new_name='ep_mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='extractionpointsenlargedsinks',
            old_name='mean_sv',
            new_name='mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='extractionpointssinks',
            old_name='mean_sv',
            new_name='mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='inletpointsenlargedsinks',
            old_name='mean_sv',
            new_name='mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='inletpointssinks',
            old_name='mean_sv',
            new_name='mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='mean_sv',
            new_name='mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='lakes4326',
            old_name='mean_sv',
            new_name='mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='sink',
            old_name='ep_mean_sv',
            new_name='ep_mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='sink4326',
            old_name='ep_mean_sv',
            new_name='ep_mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='mean_sv',
            new_name='mean_surplus_volume',
        ),
        migrations.RenameField(
            model_name='stream4326',
            old_name='mean_sv',
            new_name='mean_surplus_volume',
        ),
    ]
