# Generated by Django 4.2 on 2025-04-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0133_rename_ep_max_sv_enlargedsink_ep_max_surplus_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lakes4326',
            name='plus_days',
            field=models.IntegerField(),
        ),
    ]
