# Generated by Django 4.2 on 2025-04-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0135_lake_rename_lakes4326_lake4326_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lake4326',
        ),
        migrations.DeleteModel(
            name='Stream4326',
        ),
    ]
