# Generated by Django 4.2 on 2025-04-04 09:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0136_delete_lake4326_delete_stream4326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lake4326',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('shape_length', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('min_surplus_volume', models.FloatField()),
                ('mean_surplus_volume', models.FloatField()),
                ('max_surplus_volume', models.FloatField()),
                ('plus_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stream4326',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('shape_length', models.FloatField()),
                ('min_surplus_volume', models.FloatField()),
                ('mean_surplus_volume', models.FloatField()),
                ('max_surplus_volume', models.FloatField()),
                ('plus_days', models.IntegerField()),
            ],
        ),
    ]
