# Generated by Django 4.2 on 2025-04-14 07:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0137_lake4326_stream4326'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake4326',
            name='simple_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='stream4326',
            name='simple_geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
