# Generated by Django 4.2 on 2025-04-14 09:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0138_lake4326_simple_geom_stream4326_simple_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink4326',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='sink4326',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
