# Generated by Django 4.2 on 2025-04-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0139_enlargedsink4326_geom_simplified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream4326',
            name='geom',
        ),
    ]
