# Generated by Django 4.2 on 2025-04-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0140_remove_stream4326_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream4326',
            old_name='simple_geom',
            new_name='geom',
        ),
    ]
