# Generated by Django 4.2 on 2025-04-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0141_rename_simple_geom_stream4326_geom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeasabilityEnlargedSinks',
        ),
    ]
