# Generated by Django 4.2 on 2025-05-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0142_delete_feasabilityenlargedsinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='index_hydrology',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='enlargedsink4326',
            name='index_hydrology',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='index_hydrology',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sink4326',
            name='index_hydrology',
            field=models.FloatField(null=True),
        ),
    ]
