# Generated by Django 4.2 on 2025-05-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0144_sinksoilproperties_enlargedsinksoilproperties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsinksoilproperties',
            old_name='agricultural_landuse_id',
            new_name='agricultural_landuse',
        ),
        migrations.RenameField(
            model_name='enlargedsinksoilproperties',
            old_name='fieldcapacity_id',
            new_name='fieldcapacity',
        ),
        migrations.RenameField(
            model_name='enlargedsinksoilproperties',
            old_name='groundwater_distance_id',
            new_name='groundwater_distance',
        ),
        migrations.RenameField(
            model_name='enlargedsinksoilproperties',
            old_name='hydromorphy_id',
            new_name='hydromorphy',
        ),
        migrations.RenameField(
            model_name='enlargedsinksoilproperties',
            old_name='landuse_id',
            new_name='landuse',
        ),
        migrations.RenameField(
            model_name='enlargedsinksoilproperties',
            old_name='sink_id',
            new_name='sink',
        ),
        migrations.RenameField(
            model_name='enlargedsinksoilproperties',
            old_name='soil_properties_id',
            new_name='soil_properties',
        ),
        migrations.RenameField(
            model_name='enlargedsinksoilproperties',
            old_name='wet_grassland_id',
            new_name='wet_grassland',
        ),
    ]
