# Generated by Django 4.2 on 2025-05-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0146_rename_agricultural_landuse_id_sinksoilproperties_agricultural_landuse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfiltrationProject',
            fields=[
                ('toolboxproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='toolbox.toolboxproject')),
                ('weighting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.sinkweighting')),
            ],
            bases=('toolbox.toolboxproject',),
        ),
        migrations.RenameModel(
            old_name='Soil',
            new_name='SoilTexture',
        ),
        migrations.DeleteModel(
            name='Infiltration',
        ),
    ]
