# Generated by Django 4.2 on 2025-05-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0147_infiltrationproject_rename_soil_soiltexture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilproperties',
            old_name='soil',
            new_name='soil_texture',
        ),
    ]
