# Generated by Django 4.2 on 2025-05-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0148_rename_soil_soilproperties_soil_texture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsinksoilproperties',
            old_name='soil_id',
            new_name='soil_texture',
        ),
        migrations.RenameField(
            model_name='sinksoilproperties',
            old_name='soil_id',
            new_name='soil_texture',
        ),
    ]
