# Generated by Django 4.2 on 2025-05-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0149_rename_soil_id_enlargedsinksoilproperties_soil_texture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlargedsinksoilproperties',
            name='soil_texture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.soiltexture'),
        ),
        migrations.AlterField(
            model_name='sinksoilproperties',
            name='soil_texture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.soiltexture'),
        ),
    ]
