# Generated by Django 4.2 on 2025-05-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0150_alter_enlargedsinksoilproperties_soil_texture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsinksoilproperties',
            name='c_soil_1',
        ),
        migrations.RemoveField(
            model_name='enlargedsinksoilproperties',
            name='c_soil_2',
        ),
        migrations.RemoveField(
            model_name='enlargedsinksoilproperties',
            name='c_soil_3',
        ),
        migrations.RemoveField(
            model_name='enlargedsinksoilproperties',
            name='c_suit_gw',
        ),
        migrations.AddField(
            model_name='enlargedsinksoilproperties',
            name='land_use_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enlargedsinksoilproperties',
            name='land_use_4_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enlargedsinksoilproperties',
            name='landuse_1',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_1', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='enlargedsinksoilproperties',
            name='landuse_2',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_2', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='enlargedsinksoilproperties',
            name='landuse_3',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_3', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='enlargedsinksoilproperties',
            name='landuse_4',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_4', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='sinksoilproperties',
            name='landuse_1',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sink_landuse_1', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='sinksoilproperties',
            name='landuse_2',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sink_landuse_2', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='sinksoilproperties',
            name='landuse_3',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sink_landuse_3', to='toolbox.landuse'),
        ),
    ]
