# Generated by Django 4.2 on 2025-05-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0151_remove_enlargedsinksoilproperties_c_soil_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuse',
            name='sink_landuse_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
