# Generated by Django 4.2 on 2025-05-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0152_landuse_sink_landuse_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldCapacityClass',
        ),
    ]
