# Generated by Django 4.2 on 2025-05-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0153_delete_fieldcapacityclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrogeologyenlargedsinks',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='hydrogeologyenlargedsinks',
            name='shape_length',
        ),
        migrations.RemoveField(
            model_name='hydrogeologysinks',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='hydrogeologysinks',
            name='shape_length',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='c_wet_gras',
        ),
        migrations.RemoveField(
            model_name='soilproperties',
            name='wet_gras',
        ),
    ]
