# Generated by Django 4.2 on 2025-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0155_remove_sinksoilproperties_agricultural_landuse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinksoilproperties',
            name='partial_sink_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
