# Generated by Django 4.2 on 2025-05-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0157_remove_enlargedsinksoilproperties_agricultural_landuse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsinksoilproperties',
            name='percent_of_total_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinksoilproperties',
            name='percent_of_total_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
