# Generated by Django 4.2 on 2025-05-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0158_enlargedsinksoilproperties_percent_of_total_area_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SinkEmbankment',
            new_name='EnlargedSinkEmbankment',
        ),
    ]
