# Generated by Django 4.2 on 2025-05-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0159_rename_sinkembankment_enlargedsinkembankment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsinkembankment',
            name='enlarged_sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.enlargedsink4326'),
        ),
    ]
