# Generated by Django 4.2 on 2025-05-09 13:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0160_enlargedsinkembankment_enlarged_sink'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsinkembankment',
            name='centroid4326',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='enlargedsinkembankment',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='enlargedsinkembankment',
            name='enlarged_sink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.enlargedsink4326'),
        ),
    ]
