# Generated by Django 4.2 on 2025-05-09 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0161_enlargedsinkembankment_centroid4326_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sink4326',
            name='geom25833',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833),
        ),
    ]
