# Generated by Django 4.2 on 2025-05-09 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0163_enlargedsink4326_geom25833'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionpointsenlargedsinks',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='extractionpointssinks',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
