# Generated by Django 4.2 on 2025-05-09 14:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0164_extractionpointsenlargedsinks_geom4326_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlargedsinksoilproperties',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
