# Generated by Django 4.2 on 2025-05-09 14:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0165_alter_enlargedsinksoilproperties_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='inletpointsenlargedsinks',
            name='enlarged_sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.sink4326'),
        ),
        migrations.AddField(
            model_name='inletpointsenlargedsinks',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='inletpointssinks',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='inletpointssinks',
            name='sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.sink4326'),
        ),
    ]
