# Generated by Django 4.2 on 2025-05-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0166_inletpointsenlargedsinks_enlarged_sink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionpointsenlargedsinks',
            name='enlarged_sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.enlargedsink4326'),
        ),
    ]
