# Generated by Django 4.2 on 2025-05-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0167_extractionpointsenlargedsinks_enlarged_sink'),
    ]

    operations = [        
        migrations.DeleteModel(
            name='OutlineGeste',
        ),
    ]
