# Generated by Django 4.2 on 2025-05-16 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0168_delete_digitalelevationmodel10_delete_outlinegeste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalElevationModel10',
        ),
        migrations.RenameField(
            model_name='enlargedsinksoilproperties',
            old_name='sink',
            new_name='enlarged_sink',
        ),
        migrations.AlterField(
            model_name='sinksoilproperties',
            name='sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sink_soil_properties', to='toolbox.sink4326'),
        ),
    ]
