# Generated by Django 4.2 on 2025-05-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0169_delete_digitalelevationmodel10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlargedsinksoilproperties',
            name='enlarged_sink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.enlargedsink4326'),
        ),
    ]
