# Generated by Django 4.2 on 2025-05-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0170_alter_enlargedsinksoilproperties_enlarged_sink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feasability',
            new_name='Feasibility',
        ),
        migrations.AlterField(
            model_name='enlargedsinksoilproperties',
            name='enlarged_sink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enlarged_sink_soil_properties', to='toolbox.enlargedsink4326'),
        ),
    ]
