# Generated by Django 4.2 on 2025-05-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0171_rename_feasability_feasibility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feasibility',
            old_name='fie_as_num',
            new_name='soil_quality_index',
        ),
    ]
