# Generated by Django 4.2 on 2025-05-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0172_rename_fie_as_num_feasibility_soil_quality_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feasibility',
        ),
    ]
