# Generated by Django 4.2 on 2025-05-28 11:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0173_delete_feasibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feasibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833)),
                ('shape_length', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('veg_fe', models.CharField(max_length=100, null=True)),
                ('land_use', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('soil_quality_index', models.FloatField(null=True)),
                ('index', models.FloatField(null=True)),
            ],
        ),
    ]
