# Generated by Django 4.2 on 2025-05-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0174_feasibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasibility',
            name='centroid',
        ),
        migrations.RemoveField(
            model_name='feasibility',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='feasibility',
            name='shape_length',
        ),
    ]
