# Generated by Django 4.2 on 2025-05-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0175_remove_feasibility_centroid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibility',
            name='landuse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.landuse'),
        ),
    ]
