# Generated by Django 4.2 on 2025-05-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0176_feasibility_landuse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feasibility',
        ),
    ]
