# Generated by Django 4.2 on 2025-05-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0178_feasibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasibility',
            name='land_use',
        ),
        migrations.RemoveField(
            model_name='feasibility',
            name='type',
        ),
    ]
