# Generated by Django 4.2 on 2025-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0179_remove_feasibility_land_use_remove_feasibility_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feasibility',
            old_name='index',
            new_name='index_feasibility',
        ),
        migrations.AlterField(
            model_name='feasibility',
            name='soil_quality_index',
            field=models.IntegerField(null=True),
        ),
    ]
