# Generated by Django 4.2 on 2025-05-28 13:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0180_rename_index_feasibility_index_feasibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeasibilitySink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('area', models.FloatField(blank=True, null=True)),
                ('area_of_total', models.FloatField(blank=True, null=True)),
                ('feasibility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.feasibility')),
                ('sink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.sink4326')),
            ],
        ),
        migrations.CreateModel(
            name='FeasibilityEnlargedSink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('area', models.FloatField(blank=True, null=True)),
                ('area_of_total', models.FloatField(blank=True, null=True)),
                ('enlarged_sink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.enlargedsink4326')),
                ('feasibility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.feasibility')),
            ],
        ),
    ]
