# Generated by Django 4.2 on 2025-06-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0181_feasibilitysink_feasibilityenlargedsink'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuse',
            name='de',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landuse',
            name='en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
