# Generated by Django 4.2 on 2025-06-02 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0182_landuse_de_landuse_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink4326',
            name='landuse_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_1', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='enlargedsink4326',
            name='landuse_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_2', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='enlargedsink4326',
            name='landuse_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_3', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='enlargedsink4326',
            name='landuse_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_4', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='sink4326',
            name='landuse_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sink_landuse_1', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='sink4326',
            name='landuse_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sink_landuse_2', to='toolbox.landuse'),
        ),
        migrations.AddField(
            model_name='sink4326',
            name='landuse_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sink_landuse_3', to='toolbox.landuse'),
        ),
    ]
