# Generated by Django 4.2 on 2025-06-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0183_enlargedsink4326_landuse_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landusemap',
            old_name='centroid',
            new_name='centroid25833',
        ),
        migrations.RenameField(
            model_name='landusemap',
            old_name='geom',
            new_name='geom25833',
        ),
    ]
