# Generated by Django 4.2 on 2025-06-05 10:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0184_rename_centroid_landusemap_centroid25833_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusemap',
            name='centroid4326',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='landusemap',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
