# Generated by Django 4.2 on 2025-06-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0185_landusemap_centroid4326_landusemap_geom4326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandUse4326',
        ),
    ]
