# Generated by Django 4.2 on 2025-06-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0186_delete_landuse4326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landusemap',
            name='name',
        ),
        migrations.RemoveField(
            model_name='landusemap',
            name='name_v',
        ),
    ]
