# Generated by Django 4.2 on 2025-06-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0022_rename_area_percenteage_soilprofile_area_percentage'),
        ('toolbox', '0187_remove_landusemap_name_remove_landusemap_name_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuse',
            name='corine_land_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corine_land_cover', to='buek.corinelandcover2018'),
        ),
    ]
