# Generated by Django 4.2 on 2025-06-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0188_landuse_corine_land_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landuse',
            name='clc',
        ),
        migrations.RemoveField(
            model_name='landuse',
            name='corine_land_cover',
        ),
    ]
