# Generated by Django 4.2 on 2025-06-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0189_remove_landuse_clc_remove_landuse_corine_land_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landuse',
            name='buek_corine_land_cover',
        ),
        migrations.RemoveField(
            model_name='landusemap',
            name='code_18',
        ),
    ]
