# Generated by Django 4.2 on 2025-06-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0022_rename_area_percenteage_soilprofile_area_percentage'),
        ('toolbox', '0190_remove_landuse_buek_corine_land_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusemap',
            name='buek_corine_land_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buek_corine_land_cover', to='buek.corinelandcover2018'),
        ),
    ]
