# Generated by Django 4.2 on 2025-06-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0191_landusemap_buek_corine_land_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landusemap',
            name='buek_corine_land_cover',
        ),
        migrations.RemoveField(
            model_name='landusemap',
            name='corine_1',
        ),
        migrations.RemoveField(
            model_name='landusemap',
            name='corine_2',
        ),
        migrations.RemoveField(
            model_name='landusemap',
            name='corine_3',
        ),
    ]
