# Generated by Django 4.2 on 2025-06-05 13:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0192_remove_landusemap_buek_corine_land_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake4326',
            name='geom25833',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='stream4326',
            name='geom25833',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
