# Generated by Django 4.2 on 2025-06-05 14:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0194_alter_stream4326_geom25833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream4326',
            name='geom25833',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=25833),
        ),
    ]
