# Generated by Django 4.2 on 2025-06-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0195_alter_stream4326_geom25833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionpointssinks',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.stream4326'),
        ),
    ]
