# Generated by Django 4.2 on 2025-06-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0196_alter_extractionpointssinks_stream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
