# Generated by Django 4.2 on 2025-06-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0197_delete_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionpointssinks',
            name='lake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.lake4326'),
        ),
        migrations.DeleteModel(
            name='Lake',
        ),
    ]
