# Generated by Django 4.2 on 2025-06-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0198_alter_extractionpointssinks_lake_delete_lake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionpointssinks',
            name='sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.sink4326'),
        ),
    ]
