# Generated by Django 4.2 on 2025-06-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0199_alter_extractionpointssinks_sink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrogeologyenlargedsinks',
            name='enlarged_sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.enlargedsink4326'),
        ),
        migrations.AlterField(
            model_name='hydrogeologysinks',
            name='sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.sink4326'),
        ),
        migrations.DeleteModel(
            name='Sink',
        ),
    ]
