# Generated by Django 4.2 on 2025-06-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0200_alter_hydrogeologyenlargedsinks_enlarged_sink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inletpointsenlargedsinks',
            name='enlarged_sink',
        ),
        migrations.RemoveField(
            model_name='inletpointssinks',
            name='sink',
        ),
        migrations.DeleteModel(
            name='EnlargedSink',
        ),
        migrations.DeleteModel(
            name='InletPointsEnlargedSinks',
        ),
        migrations.DeleteModel(
            name='InletPointsSinks',
        ),
    ]
