# Generated by Django 4.2 on 2025-06-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0201_remove_inletpointsenlargedsinks_enlarged_sink_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnlargedSink4326',
            new_name='EnlargedSink',
        ),
        migrations.RenameModel(
            old_name='Sink4326',
            new_name='Sink',
        ),
    ]
