# Generated by Django 4.2 on 2025-06-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0202_rename_enlargedsink4326_enlargedsink_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lake4326',
            new_name='Lake',
        ),
        migrations.RenameModel(
            old_name='Stream4326',
            new_name='Stream',
        ),
    ]
