# Generated by Django 4.2 on 2025-06-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0203_rename_lake4326_lake_rename_stream4326_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlargedsink',
            name='landuse_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_4_2', to='toolbox.landuse'),
        ),
        migrations.CreateModel(
            name='EnlargedSinkX',
            fields=[
                ('sink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='toolbox.sink')),
                ('nat_length', models.FloatField(null=True)),
                ('por_length', models.FloatField(null=True)),
                ('con_length', models.FloatField(null=True)),
                ('constructed_sink', models.BooleanField(default=False, null=True)),
                ('volume_construction_barrier', models.FloatField(null=True)),
                ('volume_gained', models.FloatField(null=True)),
                ('construction_efficiciency', models.FloatField(null=True)),
                ('land_use_4', models.CharField(max_length=100, null=True)),
                ('land_use_4_percentage', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('feasibilty_enlarged_sinks_index', models.FloatField(null=True)),
                ('landuse_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_4', to='toolbox.landuse')),
            ],
            bases=('toolbox.sink',),
        ),
    ]
