# Generated by Django 4.2 on 2025-06-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0204_alter_enlargedsink_landuse_4_enlargedsinkx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsink',
            name='extractionpoint',
        ),
        migrations.AddField(
            model_name='enlargedsinkx',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
