# Generated by Django 4.2 on 2025-06-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0205_remove_enlargedsink_extractionpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
