# Generated by Django 4.2 on 2025-06-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0206_alter_sink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='land_use_1_fk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enlargedsink',
            name='land_use_2_fk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enlargedsink',
            name='land_use_4_fk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enlargedsink',
            name='landuse_3_fk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='landuse_1_fk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='landuse_2_fk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='landuse_3_fk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EnlargedSinkX',
        ),
    ]
