# Generated by Django 4.2 on 2025-06-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0207_enlargedsink_land_use_1_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsink',
            name='landuse_1',
        ),
        migrations.RemoveField(
            model_name='enlargedsink',
            name='landuse_2',
        ),
        migrations.RemoveField(
            model_name='enlargedsink',
            name='landuse_3',
        ),
        migrations.RemoveField(
            model_name='enlargedsink',
            name='landuse_4',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='landuse_1',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='landuse_2',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='landuse_3',
        ),
    ]
