# Generated by Django 4.2 on 2025-06-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0208_remove_enlargedsink_landuse_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsink',
            name='land_use_1_fk',
        ),
        migrations.RemoveField(
            model_name='enlargedsink',
            name='land_use_2_fk',
        ),
        migrations.RemoveField(
            model_name='enlargedsink',
            name='landuse_3_fk',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='landuse_1_fk',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='landuse_2_fk',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='landuse_3_fk',
        ),
    ]
