# Generated by Django 4.2 on 2025-06-10 08:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0209_remove_enlargedsink_land_use_1_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinkX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom25833', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('geom_simplified', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('depth', models.FloatField(null=True)),
                ('area', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('shape_length', models.FloatField(null=True)),
                ('index_1', models.FloatField(null=True)),
                ('index_2', models.FloatField(null=True)),
                ('index_3', models.FloatField(null=True)),
                ('land_use_1', models.CharField(max_length=100, null=True)),
                ('land_use_2', models.CharField(max_length=100, null=True)),
                ('land_use_3', models.CharField(max_length=100, null=True)),
                ('land_use_1_percentage', models.FloatField(null=True)),
                ('land_use_2_percentage', models.FloatField(null=True)),
                ('land_use_3_percentage', models.FloatField(null=True)),
                ('index_soil', models.FloatField(null=True)),
                ('index_hydrology', models.FloatField(null=True)),
                ('feasibility_sinks_index', models.FloatField(null=True)),
                ('landuse_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_landuse_1', to='toolbox.landuse')),
                ('landuse_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_landuse_2', to='toolbox.landuse')),
                ('landuse_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_landuse_3', to='toolbox.landuse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnlargedSinkX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom25833', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('geom_simplified', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('depth', models.FloatField(null=True)),
                ('area', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('shape_length', models.FloatField(null=True)),
                ('index_1', models.FloatField(null=True)),
                ('index_2', models.FloatField(null=True)),
                ('index_3', models.FloatField(null=True)),
                ('land_use_1', models.CharField(max_length=100, null=True)),
                ('land_use_2', models.CharField(max_length=100, null=True)),
                ('land_use_3', models.CharField(max_length=100, null=True)),
                ('land_use_1_percentage', models.FloatField(null=True)),
                ('land_use_2_percentage', models.FloatField(null=True)),
                ('land_use_3_percentage', models.FloatField(null=True)),
                ('index_soil', models.FloatField(null=True)),
                ('index_hydrology', models.FloatField(null=True)),
                ('feasibility_sinks_index', models.FloatField(null=True)),
                ('nat_length', models.FloatField(null=True)),
                ('por_length', models.FloatField(null=True)),
                ('con_length', models.FloatField(null=True)),
                ('constructed_sink', models.BooleanField(default=False, null=True)),
                ('volume_construction_barrier', models.FloatField(null=True)),
                ('volume_gained', models.FloatField(null=True)),
                ('construction_efficiciency', models.FloatField(null=True)),
                ('land_use_4', models.CharField(max_length=100, null=True)),
                ('land_use_4_percentage', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('feasibilty_enlarged_sinks_index', models.FloatField(null=True)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('landuse_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_1', to='toolbox.landuse')),
                ('landuse_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_2', to='toolbox.landuse')),
                ('landuse_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse_3', to='toolbox.landuse')),
                ('landuse_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlargedsink_landuse_4', to='toolbox.landuse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
