# Generated by Django 4.2 on 2025-06-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0210_sinkx_enlargedsinkx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlargedsinkx',
            name='landuse_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_landuse_1', to='toolbox.landuse'),
        ),
        migrations.AlterField(
            model_name='enlargedsinkx',
            name='landuse_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_landuse_2', to='toolbox.landuse'),
        ),
        migrations.AlterField(
            model_name='enlargedsinkx',
            name='landuse_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_landuse_3', to='toolbox.landuse'),
        ),
    ]
