# Generated by Django 4.2 on 2025-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0211_alter_enlargedsinkx_landuse_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinkx',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
