# Generated by Django 4.2 on 2025-06-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0212_sinkx_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionpointssinks',
            name='lake',
        ),
        migrations.RemoveField(
            model_name='extractionpointssinks',
            name='sink',
        ),
        migrations.RemoveField(
            model_name='extractionpointssinks',
            name='stream',
        ),
        migrations.AddField(
            model_name='enlargedsinkembankment',
            name='enlarged_sink_x',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.enlargedsinkx'),
        ),
        migrations.AddField(
            model_name='enlargedsinksoilproperties',
            name='enlarged_sink_x',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_soil_properties_x', to='toolbox.enlargedsinkx'),
        ),
        migrations.AddField(
            model_name='feasibilityenlargedsink',
            name='enlarged_sink_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.enlargedsinkx'),
        ),
        migrations.AddField(
            model_name='feasibilitysink',
            name='sink_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.sinkx'),
        ),
        migrations.AddField(
            model_name='hydrogeologyenlargedsinks',
            name='enlarged_sink_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.enlargedsinkx'),
        ),
        migrations.AddField(
            model_name='hydrogeologysinks',
            name='sink_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.sinkx'),
        ),
        migrations.AddField(
            model_name='sinksoilproperties',
            name='sink_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sink_soil_properties_x', to='toolbox.sinkx'),
        ),
        migrations.AlterField(
            model_name='enlargedsinkembankment',
            name='enlarged_sink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.enlargedsink'),
        ),
        migrations.AlterField(
            model_name='enlargedsinksoilproperties',
            name='enlarged_sink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_soil_properties', to='toolbox.enlargedsink'),
        ),
        migrations.AlterField(
            model_name='hydrogeologyenlargedsinks',
            name='enlarged_sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.enlargedsink'),
        ),
        migrations.AlterField(
            model_name='sinksoilproperties',
            name='sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sink_soil_properties', to='toolbox.sink'),
        ),
        migrations.DeleteModel(
            name='ExtractionPointsEnlargedSinks',
        ),
        migrations.DeleteModel(
            name='ExtractionPointsSinks',
        ),
    ]
