# Generated by Django 4.2 on 2025-06-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0213_remove_extractionpointssinks_lake_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandUseMap',
        ),
    ]
