# Generated by Django 4.2 on 2025-06-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0215_landusemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusemap',
            name='vegetation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
