# Generated by Django 4.2 on 2025-06-10 16:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0216_landusemap_vegetation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landusemap',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='landusemap',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
