# Generated by Django 4.2 on 2025-06-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0217_alter_landusemap_geom_alter_landusemap_geom4326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanduseMap',
        ),
    ]
