# Generated by Django 4.2 on 2025-06-10 16:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0218_delete_landusemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanduseMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetation', models.BooleanField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833)),
                ('geom4326', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('landuse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landuse_map', to='toolbox.landuse')),
            ],
        ),
    ]
