# Generated by Django 4.2 on 2025-06-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0219_landusemap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinkx',
            name='landuse_1',
        ),
        migrations.RemoveField(
            model_name='sinkx',
            name='landuse_2',
        ),
        migrations.RemoveField(
            model_name='sinkx',
            name='landuse_3',
        ),
        migrations.RemoveField(
            model_name='enlargedsinkembankment',
            name='enlarged_sink_x',
        ),
        migrations.RemoveField(
            model_name='enlargedsinksoilproperties',
            name='enlarged_sink_x',
        ),
        migrations.RemoveField(
            model_name='feasibilityenlargedsink',
            name='enlarged_sink_x',
        ),
        migrations.RemoveField(
            model_name='feasibilitysink',
            name='sink_x',
        ),
        migrations.RemoveField(
            model_name='hydrogeologyenlargedsinks',
            name='enlarged_sink_x',
        ),
        migrations.RemoveField(
            model_name='hydrogeologysinks',
            name='sink_x',
        ),
        migrations.RemoveField(
            model_name='sinksoilproperties',
            name='sink_x',
        ),
        migrations.DeleteModel(
            name='EnlargedSinkX',
        ),
        migrations.DeleteModel(
            name='SinkX',
        ),
    ]
