# Generated by Django 4.2 on 2025-06-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0220_remove_sinkx_landuse_1_remove_sinkx_landuse_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='geom',
            new_name='geom4326',
        ),
        migrations.RenameField(
            model_name='sink',
            old_name='geom',
            new_name='geom4326',
        ),
    ]
