# Generated by Django 4.2 on 2025-06-11 08:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0221_rename_geom_enlargedsink_geom4326_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='sink',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833),
        ),
    ]
