# Generated by Django 4.2 on 2025-06-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0222_enlargedsink_geom_sink_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsink',
            name='geom25833',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='geom25833',
        ),
    ]
