# Generated by Django 4.2 on 2025-06-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0223_remove_enlargedsink_geom25833_remove_sink_geom25833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='geom',
            new_name='geom25833',
        ),
    ]
