# Generated by Django 4.2 on 2025-06-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0224_rename_geom_enlargedsink_geom25833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sink',
            old_name='geom',
            new_name='geom25833',
        ),
    ]
