# Generated by Django 4.2 on 2025-06-11 10:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0227_sinklanduse_enlargedsinklanduse'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanduseEnlargedSink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('area_of_total', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(null=True)),
                ('landuse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.landuse')),
                ('sink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enlarged_sink_landuse', to='toolbox.sink')),
            ],
        ),
        migrations.CreateModel(
            name='LanduseSink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('area_of_total', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(null=True)),
                ('landuse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.landuse')),
                ('sink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sink_landuse', to='toolbox.sink')),
            ],
        ),
        migrations.RemoveField(
            model_name='sinklanduse',
            name='landuse',
        ),
        migrations.RemoveField(
            model_name='sinklanduse',
            name='sink',
        ),
        migrations.DeleteModel(
            name='EnlargedSinkLanduse',
        ),
        migrations.DeleteModel(
            name='SinkLanduse',
        ),
    ]
