# Generated by Django 4.2 on 2025-06-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0228_landuseenlargedsink_landusesink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuseenlargedsink',
            name='sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enlarged_sink_landuse', to='toolbox.enlargedsink'),
        ),
    ]
