# Generated by Django 4.2 on 2025-06-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0229_alter_landuseenlargedsink_sink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuseenlargedsink',
            name='sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlarged_sink_landuse', to='toolbox.enlargedsink'),
        ),
        migrations.AlterField(
            model_name='landusemap',
            name='landuse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='landuse_map', to='toolbox.landuse'),
        ),
        migrations.AlterField(
            model_name='landusesink',
            name='sink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sink_landuse', to='toolbox.sink'),
        ),
        migrations.AlterField(
            model_name='sinksoilproperties',
            name='soil_properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.soilproperties'),
        ),
    ]
