# Generated by Django 4.2 on 2025-06-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0230_alter_landuseenlargedsink_sink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinksoilproperties',
            name='sink_fid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
