# Generated by Django 4.2 on 2025-06-11 15:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0231_sinksoilproperties_sink_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sink',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
