# Generated by Django 4.2 on 2025-06-11 16:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0232_alter_sink_geom4326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlargedsink',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
