# Generated by Django 4.2 on 2025-06-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0233_alter_enlargedsink_geom4326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlargedsink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
