# Generated by Django 4.2 on 2025-06-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0234_alter_enlargedsink_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanduseSinkProportions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('area_of_total', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(null=True)),
                ('enlarged_sink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sink_landuse_proportions', to='toolbox.enlargedsink')),
                ('landuse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.landuse')),
            ],
        ),
    ]
