# Generated by Django 4.2 on 2025-06-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0235_landusesinkproportions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sink',
            name='geom4326',
        ),
    ]
