# Generated by Django 4.2 on 2025-06-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0237_sink_geom4326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsink',
            name='geom4326',
        ),
    ]
