# Generated by Django 4.2 on 2025-06-12 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0238_remove_enlargedsink_geom4326'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
