# Generated by Django 4.2 on 2025-06-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0239_enlargedsink_geom4326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanduseSinkProportions',
        ),
    ]
