# Generated by Django 4.2 on 2025-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0240_delete_landusesinkproportions'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibility',
            name='vegetation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
