# Generated by Django 4.2 on 2025-06-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0242_alter_enlargedsinkembankment_enlarged_sink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsinkembankment',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='enlargedsinkembankment',
            name='shape_length',
        ),
    ]
