# Generated by Django 4.2 on 2025-07-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0243_remove_enlargedsinkembankment_shape_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='fgw_id',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lake',
            name='minimum_environmental_flow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lake',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
