# Generated by Django 4.2 on 2025-07-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0245_stream_fgw_id_stream_minimum_environmental_flow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sink',
            old_name='feasibility_sinks_index',
            new_name='index_feasibility',
        ),
    ]
