# Generated by Django 4.2 on 2025-07-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0246_rename_feasibility_sinks_index_sink_index_feasibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='feasibilty_enlarged_sinks_index',
            new_name='index_feasibility',
        ),
    ]
