# Generated by Django 4.2 on 2025-07-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0247_rename_feasibilty_enlarged_sinks_index_enlargedsink_index_feasibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='hydrogeology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enlargedsink',
            name='index_hydrogeology',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enlargedsink',
            name='soil_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='hydrogeology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='index_hydrogeology',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='soil_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
