# Generated by Django 4.2 on 2025-07-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0248_enlargedsink_hydrogeology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlargedsink',
            name='soil_points',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='soil_points',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
