# Generated by Django 4.2 on 2025-07-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0249_alter_enlargedsink_soil_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsink',
            name='index_hydrology',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='index_hydrology',
        ),
    ]
