# Generated by Django 4.2 on 2025-07-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0251_aquifer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='aquifer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.aquifer'),
        ),
        migrations.AddField(
            model_name='sink',
            name='aquifer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.aquifer'),
        ),
    ]
