# Generated by Django 4.2 on 2025-07-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0254_rename_sink_proportion_evaluation_enlargedsink_proportion_evaluation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='hydrogeology',
            new_name='hydrogeology_text',
        ),
        migrations.RenameField(
            model_name='sink',
            old_name='hydrogeology',
            new_name='hydrogeology_text',
        ),
    ]
