# Generated by Django 4.2 on 2025-07-09 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0255_rename_hydrogeology_enlargedsink_hydrogeology_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='hydrogeology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.hydrogeology'),
        ),
        migrations.AddField(
            model_name='sink',
            name='hydrogeology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.hydrogeology'),
        ),
    ]
