# Generated by Django 4.2 on 2025-07-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0256_enlargedsink_hydrogeology_sink_hydrogeology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsink',
            name='hydrogeology',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='hydrogeology',
        ),
    ]
