# Generated by Django 4.2 on 2025-07-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0257_remove_enlargedsink_hydrogeology_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsink',
            old_name='index_3',
            new_name='index_proportions',
        ),
        migrations.RenameField(
            model_name='sink',
            old_name='index_3',
            new_name='index_proportions',
        ),
    ]
