# Generated by Django 4.2 on 2025-07-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0259_remove_enlargedsink_proportion_evaluation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasibilitysink',
            name='feasibility',
        ),
        migrations.RemoveField(
            model_name='feasibilitysink',
            name='sink',
        ),
        migrations.DeleteModel(
            name='FeasibilityEnlargedSink',
        ),
        migrations.DeleteModel(
            name='FeasibilitySink',
        ),
    ]
