# Generated by Django 4.2 on 2025-07-21 11:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0260_remove_feasibilitysink_feasibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiekerLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geb_kz', models.IntegerField(blank=True, null=True)),
                ('see_name', models.CharField(blank=True, max_length=255, null=True)),
                ('objart', models.IntegerField(blank=True, null=True)),
                ('geo_quelle', models.CharField(blank=True, max_length=255, null=True)),
                ('see_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('stand', models.DateField(blank=True, null=True)),
                ('ms_cd_lw', models.CharField(blank=True, max_length=255, null=True)),
                ('cd_ls', models.CharField(blank=True, max_length=255, null=True)),
                ('wrrl_pg', models.CharField(blank=True, max_length=255, null=True)),
                ('wa_cd', models.CharField(blank=True, max_length=255, null=True)),
                ('genese', models.CharField(blank=True, max_length=255, null=True)),
                ('gis_id', models.IntegerField(blank=True, null=True)),
                ('wrrl', models.IntegerField(blank=True, null=True)),
                ('badesee', models.IntegerField(blank=True, null=True)),
                ('quelldat', models.DateField(blank=True, null=True)),
                ('jp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('area_gis', models.FloatField(blank=True, null=True)),
                ('area_gis_h', models.FloatField(blank=True, null=True)),
                ('umfang_gis', models.FloatField(blank=True, null=True)),
                ('see_kz', models.CharField(blank=True, max_length=255, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('shape_len', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
            ],
        ),
    ]
