# Generated by Django 4.2 on 2025-07-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0261_siekerlake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siekerlake',
            name='objart',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
