# Generated by Django 4.2 on 2025-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0262_alter_siekerlake_objart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siekerlake',
            name='geb_kz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
