# Generated by Django 4.2 on 2025-07-21 12:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0264_siekergewnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='EZG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('kennzahl', models.CharField(blank=True, max_length=100, null=True)),
                ('gewaesser', models.CharField(blank=True, max_length=100, null=True)),
                ('gew_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('gew_kennz', models.CharField(blank=True, max_length=100, null=True)),
                ('beschr_von', models.CharField(blank=True, max_length=100, null=True)),
                ('beschr_bis', models.CharField(blank=True, max_length=100, null=True)),
                ('lage', models.CharField(blank=True, max_length=100, null=True)),
                ('land', models.CharField(blank=True, max_length=100, null=True)),
                ('ordnung', models.CharField(blank=True, max_length=100, null=True)),
                ('fl_art', models.CharField(blank=True, max_length=100, null=True)),
                ('wrrl_kr', models.CharField(blank=True, max_length=100, null=True)),
                ('area_qkm', models.FloatField(blank=True, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('ezg_id', models.IntegerField(blank=True, null=True)),
                ('bemerkung', models.CharField(blank=True, max_length=100, null=True)),
                ('wrrl_fge', models.CharField(blank=True, max_length=100, null=True)),
                ('wrrl_bg', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('shape_len', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiekerLargeLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('stand', models.DateField(blank=True, null=True)),
                ('wrrl_pg', models.CharField(blank=True, max_length=100, null=True)),
                ('genese', models.CharField(blank=True, max_length=100, null=True)),
                ('wrrl', models.IntegerField(blank=True, null=True)),
                ('badesee', models.IntegerField(blank=True, null=True)),
                ('quelldat', models.DateField(blank=True, null=True)),
                ('area_m2', models.IntegerField(blank=True, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('vol_mio_m3', models.FloatField(blank=True, null=True)),
                ('ezg_km2', models.FloatField(blank=True, null=True)),
                ('d_max_m', models.IntegerField(blank=True, null=True)),
                ('verweilt', models.CharField(blank=True, max_length=100, null=True)),
                ('t_cm_per_a', models.FloatField(blank=True, null=True)),
                ('seetyp', models.IntegerField(blank=True, null=True)),
                ('seetyp_txt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
