# Generated by Django 4.2 on 2025-07-21 12:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0265_ezg_siekerlargelake'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiekerWaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833)),
                ('messstelle', models.CharField(blank=True, max_length=100, null=True)),
                ('t_d', models.IntegerField(blank=True, null=True)),
                ('t_a', models.FloatField(blank=True, null=True)),
                ('startdatum', models.CharField(blank=True, max_length=100, null=True)),
                ('enddatum', models.CharField(blank=True, max_length=100, null=True)),
                ('min_cm', models.IntegerField(blank=True, null=True)),
                ('max_cm', models.IntegerField(blank=True, null=True)),
                ('mw_10_19', models.FloatField(blank=True, null=True)),
                ('mw_90_99', models.FloatField(blank=True, null=True)),
                ('stdev_cm', models.FloatField(blank=True, null=True)),
                ('twenty_yr_trend', models.FloatField(blank=True, null=True)),
                ('pkz', models.CharField(blank=True, max_length=100, null=True)),
                ('pegelname', models.CharField(blank=True, max_length=100, null=True)),
                ('gewaesser', models.CharField(blank=True, max_length=100, null=True)),
                ('pegelart', models.CharField(blank=True, max_length=100, null=True)),
                ('mess_w', models.CharField(blank=True, max_length=100, null=True)),
                ('mess_q', models.CharField(blank=True, max_length=100, null=True)),
                ('soll_w', models.CharField(blank=True, max_length=100, null=True)),
                ('soll_q', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('hwmp', models.IntegerField(blank=True, null=True)),
                ('dgjp', models.IntegerField(blank=True, null=True)),
                ('gwk', models.CharField(blank=True, max_length=100, null=True)),
                ('gbk', models.CharField(blank=True, max_length=100, null=True)),
                ('a_ezg', models.FloatField(blank=True, null=True)),
                ('bemerkung', models.CharField(blank=True, max_length=100, null=True)),
                ('anfrage', models.CharField(blank=True, max_length=100, null=True)),
                ('stat', models.CharField(blank=True, max_length=100, null=True)),
                ('ent_quell', models.IntegerField(blank=True, null=True)),
                ('ent_muend', models.IntegerField(blank=True, null=True)),
                ('diff_cm', models.IntegerField(blank=True, null=True)),
                ('bilddatei', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
