# Generated by Django 4.2 on 2025-07-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0267_siekersink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiekerSink',
        ),
    ]
