# Generated by Django 4.2 on 2025-07-21 13:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0271_siekersink'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanduseCLC2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('fid', models.FloatField(blank=True, null=True)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('clc18', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('name_de', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
