# Generated by Django 4.2 on 2025-07-21 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0272_landuseclc2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='GekRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('dokument', models.CharField(blank=True, max_length=100, null=True)),
                ('derz_nutzu', models.CharField(blank=True, max_length=100, null=True)),
                ('quelle_1', models.CharField(blank=True, max_length=100, null=True)),
                ('quelle_2', models.CharField(blank=True, max_length=100, null=True)),
                ('gew_u_ver', models.CharField(blank=True, max_length=100, null=True)),
                ('gew_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pabschnitt', models.CharField(blank=True, max_length=100, null=True)),
                ('hrsg', models.CharField(blank=True, max_length=100, null=True)),
                ('ersch_jahr', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('mnt_1_id', models.CharField(blank=True, max_length=100, null=True)),
                ('anz_1', models.FloatField(blank=True, null=True)),
                ('besch_1', models.CharField(blank=True, max_length=100, null=True)),
                ('prio_1', models.CharField(blank=True, max_length=100, null=True)),
                ('kosten_1', models.CharField(blank=True, max_length=100, null=True)),
                ('mnt_id_2', models.CharField(blank=True, max_length=100, null=True)),
                ('mnt_id_3', models.CharField(blank=True, max_length=100, null=True)),
                ('mnt_id_4', models.CharField(blank=True, max_length=100, null=True)),
                ('mnt_id_5', models.CharField(blank=True, max_length=100, null=True)),
                ('mnt_id_6', models.CharField(blank=True, max_length=100, null=True)),
                ('anz_2', models.FloatField(blank=True, null=True)),
                ('anz_3', models.FloatField(blank=True, null=True)),
                ('anz_4', models.FloatField(blank=True, null=True)),
                ('anz_5', models.FloatField(blank=True, null=True)),
                ('anz_6', models.FloatField(blank=True, null=True)),
                ('massn_insg', models.FloatField(blank=True, null=True)),
                ('besch_2', models.CharField(blank=True, max_length=100, null=True)),
                ('besch_3', models.CharField(blank=True, max_length=100, null=True)),
                ('besch_4', models.CharField(blank=True, max_length=100, null=True)),
                ('besch_5', models.CharField(blank=True, max_length=100, null=True)),
                ('besch_6', models.CharField(blank=True, max_length=100, null=True)),
                ('prio_2', models.CharField(blank=True, max_length=100, null=True)),
                ('prio_3', models.CharField(blank=True, max_length=100, null=True)),
                ('prio_4', models.CharField(blank=True, max_length=100, null=True)),
                ('prio_5', models.CharField(blank=True, max_length=100, null=True)),
                ('prio_6', models.CharField(blank=True, max_length=100, null=True)),
                ('kosten_2', models.CharField(blank=True, max_length=100, null=True)),
                ('kosten_3', models.CharField(blank=True, max_length=100, null=True)),
                ('kosten_4', models.CharField(blank=True, max_length=100, null=True)),
                ('kosten_5', models.CharField(blank=True, max_length=100, null=True)),
                ('kosten_6', models.CharField(blank=True, max_length=100, null=True)),
                ('datum_zugr', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWetlands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('anmerkung', models.CharField(blank=True, max_length=100, null=True)),
                ('derz_nutzu', models.CharField(blank=True, max_length=100, null=True)),
                ('quelle_1', models.CharField(blank=True, max_length=100, null=True)),
                ('quelle_2', models.CharField(blank=True, max_length=100, null=True)),
                ('gew_u_ver', models.CharField(blank=True, max_length=100, null=True)),
                ('gew_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dokument1', models.CharField(blank=True, max_length=100, null=True)),
                ('flaeche_m2', models.IntegerField(blank=True, null=True)),
                ('quelle_3', models.CharField(blank=True, max_length=100, null=True)),
                ('waseransch', models.CharField(blank=True, max_length=100, null=True)),
                ('feucht_per', models.FloatField(blank=True, null=True)),
                ('umsetzbkt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
