# Generated by Django 4.2 on 2025-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0273_gekretention_historicalwetlands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gekretention',
            name='besch_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gekretention',
            name='besch_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gekretention',
            name='besch_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gekretention',
            name='besch_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gekretention',
            name='besch_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gekretention',
            name='besch_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
