# Generated by Django 4.2 on 2025-07-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0274_alter_gekretention_besch_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wasserrueckhaltepotentiale',
        ),
    ]
