# Generated by Django 4.2 on 2025-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0275_delete_wasserrueckhaltepotentiale'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekerwaterlevel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siekerwaterlevel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
