# Generated by Django 4.2 on 2025-07-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0276_siekerwaterlevel_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siekerwaterlevel',
            name='enddatum',
        ),
        migrations.RemoveField(
            model_name='siekerwaterlevel',
            name='startdatum',
        ),
    ]
