# Generated by Django 4.2 on 2025-07-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0277_remove_siekerwaterlevel_enddatum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siekerlake',
            old_name='see_name',
            new_name='name',
        ),
    ]
