# Generated by Django 4.2 on 2025-07-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0278_rename_see_name_siekerlake_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekerlake',
            name='object_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
