# Generated by Django 4.2 on 2025-07-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0279_siekerlake_object_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siekerlake',
            name='objart',
        ),
    ]
