# Generated by Django 4.2 on 2025-07-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0280_remove_siekerlake_objart'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekerlake',
            name='geb_kz_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
