# Generated by Django 4.2 on 2025-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0281_siekerlake_geb_kz_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siekerlake',
            name='geb_kz_int',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
