# Generated by Django 4.2 on 2025-07-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0282_alter_siekerlake_geb_kz_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siekerlake',
            name='geb_kz',
        ),
        migrations.RemoveField(
            model_name='siekerlake',
            name='ms_cd_lw',
        ),
        migrations.AddField(
            model_name='siekerlake',
            name='wa_cd_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
