# Generated by Django 4.2 on 2025-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0283_remove_siekerlake_geb_kz_remove_siekerlake_ms_cd_lw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siekerlake',
            name='wa_cd',
        ),
        migrations.AddField(
            model_name='siekerlake',
            name='bathing_lake',
            field=models.BooleanField(default=False),
        ),
    ]
