# Generated by Django 4.2 on 2025-07-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0284_remove_siekerlake_wa_cd_siekerlake_bathing_lake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siekerlargelake',
            old_name='geom',
            new_name='geom_multi',
        ),
    ]
