# Generated by Django 4.2 on 2025-07-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0286_siekerlargelake_geom_single'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siekerlargelake',
            old_name='geom_single',
            new_name='geom',
        ),
    ]
