# Generated by Django 4.2 on 2025-07-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0287_rename_geom_single_siekerlargelake_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siekerlargelake',
            name='geom_multi',
        ),
    ]
