# Generated by Django 4.2 on 2025-07-23 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0288_remove_siekerlargelake_geom_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekerlargelake',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
