# Generated by Django 4.2 on 2025-07-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0289_siekerlargelake_geom4326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ezg',
            old_name='geom',
            new_name='geom25833',
        ),
        migrations.RenameField(
            model_name='gekretention',
            old_name='geom',
            new_name='geom25833',
        ),
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='geom',
            new_name='geom25833',
        ),
        migrations.RenameField(
            model_name='landuseclc2018',
            old_name='geom',
            new_name='geom25833',
        ),
        migrations.RenameField(
            model_name='siekergewnet',
            old_name='geom',
            new_name='geom25833',
        ),
        migrations.RenameField(
            model_name='siekerlake',
            old_name='geom',
            new_name='geom25833',
        ),
        migrations.RenameField(
            model_name='siekerlargelake',
            old_name='geom',
            new_name='geom25833',
        ),
        migrations.RenameField(
            model_name='siekersink',
            old_name='geom',
            new_name='geom25833',
        ),
        migrations.RenameField(
            model_name='siekerwaterlevel',
            old_name='geom',
            new_name='geom25833',
        ),
    ]
