# Generated by Django 4.2 on 2025-07-23 12:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0290_rename_geom_ezg_geom25833_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ezg',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='ezg',
            name='geom_single',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833),
        ),
    ]
