# Generated by Django 4.2 on 2025-07-23 13:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0292_gekretention_geom4326_gekretention_geom_single_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siekerwaterlevel',
            name='geom_single',
        ),
        migrations.AlterField(
            model_name='siekerwaterlevel',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
