# Generated by Django 4.2 on 2025-07-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0293_remove_siekerwaterlevel_geom_single_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gekretention',
            name='geom25833',
        ),
        migrations.RemoveField(
            model_name='historicalwetlands',
            name='geom25833',
        ),
    ]
