# Generated by Django 4.2 on 2025-07-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0294_remove_gekretention_geom25833_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='geom_single',
            new_name='geom25833',
        ),
    ]
