# Generated by Django 4.2 on 2025-07-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0295_rename_geom_single_historicalwetlands_geom25833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretention',
            old_name='geom_single',
            new_name='geom25833',
        ),
    ]
