# Generated by Django 4.2 on 2025-07-23 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0296_rename_geom_single_gekretention_geom25833'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekergewnet',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='siekergewnet',
            name='geom_single',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=25833),
        ),
    ]
