# Generated by Django 4.2 on 2025-07-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0297_siekergewnet_geom4326_siekergewnet_geom_single'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siekergewnet',
            name='geom25833',
        ),
    ]
