# Generated by Django 4.2 on 2025-07-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0298_remove_siekergewnet_geom25833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siekergewnet',
            old_name='geom_single',
            new_name='geom25833',
        ),
    ]
