# Generated by Django 4.2 on 2025-07-24 07:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0299_rename_geom_single_siekergewnet_geom25833'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekersink',
            name='geom_remaining',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833),
        ),
    ]
