# Generated by Django 4.2 on 2025-07-24 08:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0300_siekersink_geom_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinkDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom25833', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833)),
                ('geom_single', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833)),
                ('geom_remaining', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833)),
                ('geom4326', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('sink_depth', models.FloatField(blank=True, null=True)),
                ('max_elevation', models.FloatField(blank=True, null=True)),
                ('min_elevation', models.FloatField(blank=True, null=True)),
                ('urbanarea', models.CharField(blank=True, max_length=100, null=True)),
                ('urbanarea_percent', models.FloatField(blank=True, null=True)),
                ('wetlands', models.CharField(blank=True, max_length=100, null=True)),
                ('wetlands_percent', models.FloatField(blank=True, null=True)),
                ('avg_depth', models.FloatField(blank=True, null=True)),
                ('distance_t', models.FloatField(blank=True, null=True)),
                ('dist_lake', models.CharField(blank=True, max_length=100, null=True)),
                ('umsetzbark', models.CharField(blank=True, max_length=100, null=True)),
                ('waterdist', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
