# Generated by Django 4.2 on 2025-07-24 09:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0301_sinkdifference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siekersink',
            name='geom_remaining',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833),
        ),
    ]
