# Generated by Django 4.2 on 2025-07-24 12:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0302_alter_siekersink_geom_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekersink',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
