# Generated by Django 4.2 on 2025-08-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0303_siekersink_centroid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretention',
            old_name='derz_nutzu',
            new_name='current_landusage',
        ),
    ]
