# Generated by Django 4.2 on 2025-08-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0304_rename_derz_nutzu_gekretention_current_landusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEKMeasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_de', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
