# Generated by Django 4.2 on 2025-08-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0306_gekretentionmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekretentionmeasure',
            name='measure_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
