# Generated by Django 4.2 on 2025-08-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0307_gekretentionmeasure_measure_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GekRetentionMeasure',
        ),
    ]
