# Generated by Django 4.2 on 2025-08-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0309_gekretentionmeasure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GekRetentionMeasure',
        ),
    ]
