# Generated by Django 4.2 on 2025-08-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0310_delete_gekretentionmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='GekRetentionMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz', models.FloatField(blank=True, null=True)),
                ('besch', models.CharField(blank=True, max_length=255, null=True)),
                ('prio', models.CharField(blank=True, max_length=100, null=True)),
                ('kosten', models.CharField(blank=True, max_length=100, null=True)),
                ('measure_number', models.IntegerField(blank=True, null=True)),
                ('gek_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.gekmeasures')),
                ('gek_retention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='toolbox.gekretention')),
            ],
        ),
    ]
