# Generated by Django 4.2 on 2025-08-11 09:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0312_remove_gekretention_anz_1_remove_gekretention_anz_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekretention',
            name='centroid4326',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
