# Generated by Django 4.2 on 2025-08-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0313_gekretention_centroid4326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretention',
            old_name='pabschnitt',
            new_name='planning_segment',
        ),
    ]
