# Generated by Django 4.2 on 2025-08-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0314_rename_pabschnitt_gekretention_planning_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GekDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_publication', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
