# Generated by Django 4.2 on 2025-08-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0315_gekdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekretention',
            name='gek_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retention_areas', to='toolbox.gekdocument'),
        ),
    ]
