# Generated by Django 4.2 on 2025-08-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0316_gekretention_gek_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gekretention',
            name='dokument',
        ),
        migrations.RemoveField(
            model_name='gekretention',
            name='ersch_jahr',
        ),
        migrations.RemoveField(
            model_name='gekretention',
            name='link',
        ),
    ]
