# Generated by Django 4.2 on 2025-08-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0317_remove_gekretention_dokument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gekretention',
            name='massn_insg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
