# Generated by Django 4.2 on 2025-08-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0318_alter_gekretention_massn_insg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretention',
            old_name='massn_insg',
            new_name='number_of_measures',
        ),
    ]
