# Generated by Django 4.2 on 2025-08-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0319_rename_massn_insg_gekretention_number_of_measures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretention',
            old_name='gew_u_ver',
            new_name='association',
        ),
    ]
