# Generated by Django 4.2 on 2025-08-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0320_rename_gew_u_ver_gekretention_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretention',
            old_name='gew_name',
            new_name='name',
        ),
    ]
