# Generated by Django 4.2 on 2025-08-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0321_rename_gew_name_gekretention_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GekPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_de', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
