# Generated by Django 4.2 on 2025-08-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0322_gekpriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekretentionmeasure',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='toolbox.gekpriority'),
        ),
    ]
