# Generated by Django 4.2 on 2025-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0323_gekretentionmeasure_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekretentionmeasure',
            name='costs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
