# Generated by Django 4.2 on 2025-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0324_gekretentionmeasure_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfield',
            name='has_sieker_gek',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userfield',
            name='has_sieker_large_lake',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userfield',
            name='has_sieker_sink',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userfield',
            name='has_sieker_surface_water',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userfield',
            name='has_zalf_enlarged_sinks',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userfield',
            name='has_zalf_sinks',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
