# Generated by Django 4.2 on 2025-08-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0325_userfield_has_sieker_gek_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretentionmeasure',
            old_name='anz',
            new_name='quantity',
        ),
    ]
