# Generated by Django 4.2 on 2025-08-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0326_rename_anz_gekretentionmeasure_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretentionmeasure',
            old_name='besch',
            new_name='description_de',
        ),
    ]
