# Generated by Django 4.2 on 2025-08-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0327_rename_besch_gekretentionmeasure_description_de'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gekretentionmeasure',
            name='prio',
        ),
    ]
