# Generated by Django 4.2 on 2025-08-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0329_geklanduse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GekLanduse',
        ),
    ]
