# Generated by Django 4.2 on 2025-08-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0026_alter_clcmap2018_geom'),
        ('toolbox', '0330_delete_geklanduse'),
    ]

    operations = [
        migrations.CreateModel(
            name='GekLanduse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_landuse', models.CharField(blank=True, max_length=100, null=True)),
                ('first_two_clc_digits', models.CharField(blank=True, max_length=2, null=True)),
                ('area_total', models.FloatField(blank=True, null=True)),
                ('area_of_landuse', models.FloatField(blank=True, null=True)),
                ('area_percentage', models.FloatField(blank=True, null=True)),
                ('clc_landuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gek_landuses', to='buek.corinelandcover2018')),
                ('gek_retention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landuses', to='toolbox.gekretention')),
            ],
        ),
    ]
