# Generated by Django 4.2 on 2025-08-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0331_geklanduse'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekpriority',
            name='priority_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
