# Generated by Django 4.2 on 2025-08-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0332_gekpriority_priority_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=255)),
                ('feature_color', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('feature_type', models.CharField(max_length=255)),
                ('table_caption', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataInfoProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup', models.BooleanField(default=True)),
                ('table', models.BooleanField(default=True)),
                ('title_de', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('value_name', models.CharField(max_length=255)),
                ('href', models.BooleanField(default=False)),
                ('data_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='toolbox.datainfo')),
            ],
        ),
    ]
