# Generated by Django 4.2 on 2025-08-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0333_datainfo_datainfoproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainfoproperty',
            name='data_info',
        ),
        migrations.DeleteModel(
            name='DataInfo',
        ),
        migrations.DeleteModel(
            name='DataInfoProperty',
        ),
    ]
