# Generated by Django 4.2 on 2025-08-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0335_datainfo_datainfoproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='marker_cluster',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
