# Generated by Django 4.2 on 2025-08-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0336_datainfo_marker_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfoproperty',
            name='order_position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
