# Generated by Django 4.2 on 2025-08-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0337_datainfoproperty_order_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfoproperty',
            name='unit',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
