# Generated by Django 4.2 on 2025-08-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0338_datainfoproperty_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='select_checkbox',
            field=models.BooleanField(default=True),
        ),
    ]
