# Generated by Django 4.2 on 2025-08-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0339_datainfo_select_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainfo',
            name='select_checkbox',
        ),
    ]
