# Generated by Django 4.2 on 2025-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0340_remove_datainfo_select_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='inner_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datainfo',
            name='inner_html_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
