# Generated by Django 4.2 on 2025-08-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0341_datainfo_inner_html_datainfo_inner_html_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='derz_nutzu',
            new_name='current_landusage',
        ),
    ]
