# Generated by Django 4.2 on 2025-08-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0342_rename_derz_nutzu_historicalwetlands_current_landusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='gew_u_ver',
            new_name='association',
        ),
    ]
