# Generated by Django 4.2 on 2025-08-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0343_rename_gew_u_ver_historicalwetlands_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='flaeche_m2',
            new_name='area',
        ),
    ]
