# Generated by Django 4.2 on 2025-08-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0344_rename_flaeche_m2_historicalwetlands_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='umsetzbkt',
            new_name='feasibility',
        ),
    ]
