# Generated by Django 4.2 on 2025-08-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0345_rename_umsetzbkt_historicalwetlands_feasibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='gew_name',
            new_name='name',
        ),
    ]
