# Generated by Django 4.2 on 2025-08-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0346_rename_gew_name_historicalwetlands_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='anmerkung',
            new_name='comment',
        ),
    ]
