# Generated by Django 4.2 on 2025-08-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0347_rename_anmerkung_historicalwetlands_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='waseransch',
            new_name='water_connection',
        ),
    ]
