# Generated by Django 4.2 on 2025-08-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0348_rename_waseransch_historicalwetlands_water_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='quelle_1',
            new_name='source_1',
        ),
    ]
