# Generated by Django 4.2 on 2025-08-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0349_rename_quelle_1_historicalwetlands_source_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='quelle_2',
            new_name='source_2',
        ),
    ]
