# Generated by Django 4.2 on 2025-08-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0350_rename_quelle_2_historicalwetlands_source_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='quelle_3',
            new_name='source_3',
        ),
    ]
