# Generated by Django 4.2 on 2025-08-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0351_rename_quelle_3_historicalwetlands_source_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='dokument1',
            new_name='document_1',
        ),
    ]
