# Generated by Django 4.2 on 2025-08-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0352_rename_dokument1_historicalwetlands_document_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EZG',
        ),
    ]
