# Generated by Django 4.2 on 2025-08-26 09:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0353_delete_ezg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('w_gn1', models.CharField(blank=True, max_length=255, null=True)),
                ('w_gn2', models.CharField(blank=True, max_length=255, null=True)),
                ('w_gn3', models.CharField(blank=True, max_length=255, null=True)),
                ('w_gn_lgb', models.CharField(blank=True, max_length=255, null=True)),
                ('w_wdm', models.IntegerField(blank=True, null=True)),
                ('w_ofl', models.IntegerField(blank=True, null=True)),
                ('w_ezg_kl', models.IntegerField(blank=True, null=True)),
                ('w_achse', models.IntegerField(blank=True, null=True)),
                ('w_gwk', models.CharField(blank=True, max_length=16, null=True)),
                ('w_gbk', models.CharField(blank=True, max_length=16, null=True)),
                ('w_sfk_lg', models.CharField(blank=True, max_length=4, null=True)),
                ('w_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
