# Generated by Django 4.2 on 2025-08-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0354_rivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rivers',
            name='w_sfk_lg',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
