# Generated by Django 4.2 on 2025-08-26 10:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0355_alter_rivers_w_sfk_lg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lake25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('geb_kz', models.CharField(blank=True, max_length=16, null=True)),
                ('see_name', models.CharField(blank=True, max_length=60, null=True)),
                ('objart', models.CharField(blank=True, max_length=16, null=True)),
                ('geo_quelle', models.CharField(blank=True, max_length=20, null=True)),
                ('see_alias', models.CharField(blank=True, max_length=60, null=True)),
                ('stand', models.DateField(blank=True, null=True)),
                ('ms_cd_lw', models.CharField(blank=True, max_length=24, null=True)),
                ('cd_ls', models.CharField(blank=True, max_length=24, null=True)),
                ('wrrl_pg', models.CharField(blank=True, max_length=20, null=True)),
                ('wa_cd', models.CharField(blank=True, max_length=4, null=True)),
                ('genese', models.CharField(blank=True, max_length=10, null=True)),
                ('gis_id', models.IntegerField(blank=True, null=True)),
                ('wrrl', models.IntegerField(blank=True, null=True)),
                ('badesee', models.IntegerField(blank=True, null=True)),
                ('quelldat', models.DateField()),
                ('jp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('area_gis', models.FloatField(blank=True, null=True)),
                ('area_gis_h', models.FloatField(blank=True, null=True)),
                ('umfang_gis', models.FloatField(blank=True, null=True)),
                ('see_kz', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('shape_len', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
