# Generated by Django 4.2 on 2025-08-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0356_lake25'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake25',
            name='see_kz',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
