# Generated by Django 4.2 on 2025-08-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0357_alter_lake25_see_kz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lake25',
            old_name='see_name',
            new_name='name',
        ),
    ]
