# Generated by Django 4.2 on 2025-08-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0358_rename_see_name_lake25_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rivers',
            new_name='River',
        ),
    ]
