# Generated by Django 4.2 on 2025-08-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0359_rename_rivers_river'),
    ]

    operations = [
        migrations.RenameField(
            model_name='river',
            old_name='w_gn1',
            new_name='name',
        ),
    ]
