# Generated by Django 4.2 on 2025-08-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0360_rename_w_gn1_river_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiekerGewnet',
        ),
    ]
