# Generated by Django 4.2 on 2025-08-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0361_delete_siekergewnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwetlands',
            name='index_feasibility',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
