# Generated by Django 4.2 on 2025-08-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0362_historicalwetlands_index_feasibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lake25',
            old_name='badesee',
            new_name='number_of_swimming_spots',
        ),
    ]
