# Generated by Django 4.2 on 2025-08-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0363_rename_badesee_lake25_number_of_swimming_spots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siekerlake',
            old_name='badesee',
            new_name='number_of_swimming_spots',
        ),
    ]
