# Generated by Django 4.2 on 2025-08-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0364_rename_badesee_siekerlake_number_of_swimming_spots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siekerlargelake',
            old_name='badesee',
            new_name='number_of_swimming_spots',
        ),
    ]
