# Generated by Django 4.2 on 2025-08-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0365_rename_badesee_siekerlargelake_number_of_swimming_spots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiekerLake',
        ),
    ]
