# Generated by Django 4.2 on 2025-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0366_delete_siekerlake'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterCoordinationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
