# Generated by Django 4.2 on 2025-08-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0367_watercoordinationentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake25',
            name='water_coordinatin_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.watercoordinationentity'),
        ),
    ]
