# Generated by Django 4.2 on 2025-08-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0368_lake25_water_coordinatin_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainfo',
            name='inner_html',
        ),
        migrations.RemoveField(
            model_name='datainfo',
            name='inner_html_2',
        ),
    ]
