# Generated by Django 4.2 on 2025-08-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0369_remove_datainfo_inner_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekersink',
            name='index_feasibility',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
