# Generated by Django 4.2 on 2025-08-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0370_siekersink_index_feasibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siekersink',
            old_name='sink_depth',
            new_name='depth',
        ),
    ]
