# Generated by Django 4.2 on 2025-09-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0371_rename_sink_depth_siekersink_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='color_by_index',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
