# Generated by Django 4.2 on 2025-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0372_datainfo_color_by_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='icon_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
