# Generated by Django 4.2 on 2025-09-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0373_datainfo_icon_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siekerlargelake',
            old_name='ezg_km2',
            new_name='einzugsgebiet_km2',
        ),
    ]
