# Generated by Django 4.2 on 2025-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0374_rename_ezg_km2_siekerlargelake_einzugsgebiet_km2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwetlands',
            name='index_feasibility',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
