# Generated by Django 4.2 on 2025-09-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0375_alter_historicalwetlands_index_feasibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='WetlandFeasibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(blank=True, max_length=32, null=True)),
                ('name_en', models.CharField(blank=True, max_length=32, null=True)),
                ('index', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalwetlands',
            name='fsb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.wetlandfeasibility'),
        ),
    ]
