# Generated by Django 4.2 on 2025-09-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0376_wetlandfeasibility_historicalwetlands_fsb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwetlands',
            name='feasibility',
        ),
        migrations.RemoveField(
            model_name='historicalwetlands',
            name='index_feasibility',
        ),
    ]
