# Generated by Django 4.2 on 2025-09-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0377_remove_historicalwetlands_feasibility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwetlands',
            old_name='fsb',
            new_name='feasibility',
        ),
    ]
