# Generated by Django 4.2 on 2025-09-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0378_rename_fsb_historicalwetlands_feasibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='legend_is_gradient',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='datainfo',
            name='legend_labels',
            field=models.JSONField(blank=True, default={'header': '', 'label_by_value': ''}, null=True),
        ),
    ]
