# Generated by Django 4.2 on 2025-09-19 07:54

from django.db import migrations, models
import toolbox.models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0379_datainfo_legend_is_gradient_datainfo_legend_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='legend_labels',
            field=models.JSONField(blank=True, default=toolbox.models.default_legend_labels, null=True),
        ),
    ]
