# Generated by Django 4.2 on 2025-09-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0380_alter_datainfo_legend_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegendSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_de', models.CharField(max_length=64)),
                ('header_en', models.CharField(blank=True, max_length=64, null=True)),
                ('grades', models.JSONField()),
                ('gradient_labels_de', models.JSONField()),
                ('gradient_labels_en', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
