# Generated by Django 4.2 on 2025-09-19 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0381_legendsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafletLegend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_de', models.CharField(max_length=64)),
                ('header_en', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegendGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('label_de', models.CharField(max_length=64)),
                ('label_en', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('leaflet_legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='toolbox.leafletlegend')),
            ],
        ),
        migrations.DeleteModel(
            name='LegendSettings',
        ),
    ]
