# Generated by Django 4.2 on 2025-09-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0382_leafletlegend_legendgrade_delete_legendsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legendgrade',
            old_name='order',
            new_name='order_position',
        ),
    ]
