# Generated by Django 4.2 on 2025-09-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0383_rename_order_legendgrade_order_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainfo',
            name='legend_is_gradient',
        ),
        migrations.RemoveField(
            model_name='datainfo',
            name='legend_labels',
        ),
        migrations.AddField(
            model_name='datainfo',
            name='legend',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.leafletlegend'),
        ),
    ]
