# Generated by Django 4.2 on 2025-09-19 14:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0384_remove_datainfo_legend_is_gradient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=25833)),
                ('data_provider', models.CharField(max_length=32)),
                ('absolute_elevation_of_sensor_m', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeseriesValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('waterlevel_above_sensor_cm', models.FloatField(blank=True, null=True)),
                ('absolute_elevation_of_sensor_m', models.FloatField(blank=True, null=True)),
                ('absolute_water_level_elevation_m', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.station')),
            ],
        ),
    ]
