# Generated by Django 4.2 on 2025-09-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0385_station_timeseriesvalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseriesvalues',
            name='absolute_elevation_of_sensor_m',
        ),
    ]
