# Generated by Django 4.2 on 2025-09-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0386_remove_timeseriesvalues_absolute_elevation_of_sensor_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
