# Generated by Django 4.2 on 2025-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0387_station_station_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarWeighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aquifer_thickness', models.IntegerField(default=5)),
                ('depth_groundwater_2', models.IntegerField(default=5)),
                ('hydraulic_conductivity', models.IntegerField(default=5)),
                ('land_use', models.IntegerField(default=5)),
                ('distance_to_source_water', models.IntegerField(default=5)),
                ('distance_to_well', models.IntegerField(default=5)),
            ],
        ),
    ]
