# Generated by Django 4.2 on 2025-09-22 09:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0388_marweighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowerSpreeCachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom25833', django.contrib.gis.db.models.fields.GeometryField(srid=25833)),
                ('geom4326', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
            ],
        ),
    ]
