# Generated by Django 4.2 on 2025-09-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0389_lowerspreecachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarSliderDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(blank=True, max_length=32, null=True)),
                ('name_en', models.CharField(blank=True, max_length=32, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
