# Generated by Django 4.2 on 2025-09-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0390_marsliderdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marweighting',
            old_name='depth_groundwater_2',
            new_name='depth_groundwater',
        ),
    ]
