# Generated by Django 4.2 on 2025-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0391_rename_depth_groundwater_2_marweighting_depth_groundwater'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarSuitabilitySliderDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(blank=True, max_length=32, null=True)),
                ('name_en', models.CharField(blank=True, max_length=32, null=True)),
                ('suitability', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuitabilityDepthToGroundWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forest_closed_coniferous', models.IntegerField(default=5)),
                ('forest_closed_deciduous', models.IntegerField(default=5)),
                ('forest_closed_mixed', models.IntegerField(default=5)),
                ('forest_closed_ubknown', models.IntegerField(default=5)),
                ('forest_open_coniferous', models.IntegerField(default=5)),
                ('forest_open_deciduous', models.IntegerField(default=5)),
                ('forest_open_mixed', models.IntegerField(default=5)),
                ('forest_open_ubknown', models.IntegerField(default=5)),
                ('shrubs', models.IntegerField(default=4)),
                ('herbaceous_vegetation', models.IntegerField(default=4)),
                ('cropland', models.IntegerField(default=2)),
                ('urban', models.IntegerField(default=0)),
                ('permanent_waterbodies', models.IntegerField(default=0)),
                ('herbaceous_wetland', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuitabilityDistanceToSourceWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_1_and_2', models.IntegerField(default=0)),
                ('zone_3', models.IntegerField(default=5)),
                ('well_catchment', models.IntegerField(default=4)),
                ('out_of_catchment_lt_5km', models.IntegerField(default=3)),
                ('out_of_catchment_gt_5km', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='SuitabilityHydraulicConductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductivity_gt_30', models.IntegerField(default=5)),
                ('conductivity_20_to_30', models.IntegerField(default=4)),
                ('conductivity_10_to_20', models.IntegerField(default=3)),
                ('conductivity_5_to_10', models.IntegerField(default=2)),
                ('conductivity_lt_5', models.IntegerField(default=1)),
            ],
        ),
    ]
