# Generated by Django 4.2 on 2025-09-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0392_marsuitabilitysliderdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitabilityDistanceToWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_1_and_2', models.IntegerField(default=0)),
                ('zone_3', models.IntegerField(default=5)),
                ('well_catchment', models.IntegerField(default=4)),
                ('out_of_catchment_lt_5km', models.IntegerField(default=3)),
                ('out_of_catchment_gt_5km', models.IntegerField(default=2)),
            ],
        ),
        migrations.RenameField(
            model_name='suitabilitydistancetosourcewater',
            old_name='out_of_catchment_lt_5km',
            new_name='distance_1200_to_1500',
        ),
        migrations.RenameField(
            model_name='suitabilitydistancetosourcewater',
            old_name='zone_3',
            new_name='distance_500_to_800',
        ),
        migrations.RenameField(
            model_name='suitabilitydistancetosourcewater',
            old_name='well_catchment',
            new_name='distance_800_1200',
        ),
        migrations.RenameField(
            model_name='suitabilitydistancetosourcewater',
            old_name='out_of_catchment_gt_5km',
            new_name='distance_gt_1500',
        ),
        migrations.RenameField(
            model_name='suitabilitydistancetosourcewater',
            old_name='zone_1_and_2',
            new_name='distance_lt_250',
        ),
        migrations.AddField(
            model_name='suitabilitydistancetosourcewater',
            name='distance_250_to_500',
            field=models.IntegerField(default=1),
        ),
    ]
