# Generated by Django 4.2 on 2025-09-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0393_suitabilitydistancetowell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitabilityLandUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forest_closed_coniferous', models.IntegerField(default=5)),
                ('forest_closed_deciduous', models.IntegerField(default=5)),
                ('forest_closed_mixed', models.IntegerField(default=5)),
                ('forest_closed_ubknown', models.IntegerField(default=5)),
                ('forest_open_coniferous', models.IntegerField(default=5)),
                ('forest_open_deciduous', models.IntegerField(default=5)),
                ('forest_open_mixed', models.IntegerField(default=5)),
                ('forest_open_ubknown', models.IntegerField(default=5)),
                ('shrubs', models.IntegerField(default=4)),
                ('herbaceous_vegetation', models.IntegerField(default=4)),
                ('cropland', models.IntegerField(default=2)),
                ('urban', models.IntegerField(default=0)),
                ('permanent_waterbodies', models.IntegerField(default=0)),
                ('herbaceous_wetland', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='suitabilitydepthtogroundwater',
            old_name='herbaceous_vegetation',
            new_name='depth_20_to_30',
        ),
        migrations.RenameField(
            model_name='suitabilitydepthtogroundwater',
            old_name='cropland',
            new_name='depth_40_to_50',
        ),
        migrations.RenameField(
            model_name='suitabilitydepthtogroundwater',
            old_name='forest_closed_coniferous',
            new_name='depth_lt_20',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='forest_closed_deciduous',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='forest_closed_mixed',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='forest_closed_ubknown',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='forest_open_coniferous',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='forest_open_deciduous',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='forest_open_mixed',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='forest_open_ubknown',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='herbaceous_wetland',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='permanent_waterbodies',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='shrubs',
        ),
        migrations.RemoveField(
            model_name='suitabilitydepthtogroundwater',
            name='urban',
        ),
        migrations.AddField(
            model_name='suitabilitydepthtogroundwater',
            name='depth_30_to_40',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='suitabilitydepthtogroundwater',
            name='depth_gt_50',
            field=models.IntegerField(default=1),
        ),
    ]
