# Generated by Django 4.2 on 2025-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0394_suitabilitylanduse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitabilityAquiferThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticknes_gt_60', models.IntegerField(default=5)),
                ('ticknes_40_to_60', models.IntegerField(default=4)),
                ('ticknes_30_to_40', models.IntegerField(default=3)),
                ('ticknes_20_to_30', models.IntegerField(default=2)),
                ('ticknes_lt_20', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='suitabilitylanduse',
            old_name='forest_closed_ubknown',
            new_name='forest_closed_unknown',
        ),
        migrations.RenameField(
            model_name='suitabilitylanduse',
            old_name='forest_open_ubknown',
            new_name='forest_open_unknown',
        ),
    ]
