# Generated by Django 4.2 on 2025-09-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0395_suitabilityaquiferthickness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('map', models.CharField(max_length=56)),
                ('map_value', models.IntegerField(null=True)),
                ('default_score', models.IntegerField()),
                ('order_position', models.IntegerField()),
            ],
        ),
    ]
