# Generated by Django 4.2 on 2025-09-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0396_maplabels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplabels',
            name='map',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='maplabels',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
