# Generated by Django 4.2 on 2025-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0397_alter_maplabels_map_alter_maplabels_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplabels',
            name='label_de',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='maplabels',
            name='label_en',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
