# Generated by Django 4.2 on 2025-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0398_maplabels_label_de_maplabels_label_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suitabilityaquiferthickness',
            old_name='ticknes_20_to_30',
            new_name='tickness_20_to_30',
        ),
        migrations.RenameField(
            model_name='suitabilityaquiferthickness',
            old_name='ticknes_30_to_40',
            new_name='tickness_30_to_40',
        ),
        migrations.RenameField(
            model_name='suitabilityaquiferthickness',
            old_name='ticknes_40_to_60',
            new_name='tickness_40_to_60',
        ),
        migrations.RenameField(
            model_name='suitabilityaquiferthickness',
            old_name='ticknes_gt_60',
            new_name='tickness_gt_60',
        ),
        migrations.RenameField(
            model_name='suitabilityaquiferthickness',
            old_name='ticknes_lt_20',
            new_name='tickness_lt_20',
        ),
        migrations.AddField(
            model_name='maplabels',
            name='suitability',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
