# Generated by Django 4.2 on 2025-09-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0399_rename_ticknes_20_to_30_suitabilityaquiferthickness_tickness_20_to_30_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuitabilityAquiferThickness',
        ),
        migrations.DeleteModel(
            name='SuitabilityDepthToGroundWater',
        ),
        migrations.DeleteModel(
            name='SuitabilityDistanceToSourceWater',
        ),
        migrations.DeleteModel(
            name='SuitabilityDistanceToWell',
        ),
        migrations.DeleteModel(
            name='SuitabilityHydraulicConductivity',
        ),
        migrations.DeleteModel(
            name='SuitabilityLandUse',
        ),
    ]
