# Generated by Django 4.2 on 2025-09-24 09:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0400_delete_suitabilityaquiferthickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfield',
            name='geom25833',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=25833),
        ),
    ]
