# Generated by Django 4.2 on 2025-09-24 12:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0401_userfield_geom25833'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarForbiddenArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom25833', django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833)),
            ],
        ),
    ]
