# Generated by Django 4.2 on 2025-09-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0402_marforbiddenarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maplabels',
            old_name='map',
            new_name='map_name',
        ),
    ]
