# Generated by Django 4.2 on 2025-10-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0403_rename_map_maplabels_map_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekretentionmeasure',
            name='costs_adjusted_q1_2025',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
