# Generated by Django 4.2 on 2025-10-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0404_gekretentionmeasure_costs_adjusted_q1_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretentionmeasure',
            old_name='costs',
            new_name='costs_2013',
        ),
    ]
