# Generated by Django 4.2 on 2025-10-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0405_rename_costs_gekretentionmeasure_costs_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretentionmeasure',
            old_name='costs_adjusted_q1_2025',
            new_name='costs',
        ),
    ]
