# Generated by Django 4.2 on 2025-10-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0406_rename_costs_adjusted_q1_2025_gekretentionmeasure_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='waterbody',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
