# Generated by Django 4.2 on 2025-10-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0407_station_waterbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeseriesDailyWaterlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.station')),
            ],
        ),
    ]
