# Generated by Django 4.2 on 2025-10-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0409_timeseriesyearlywaterlevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseriesmonthlywaterlevel',
            old_name='date',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='toolboxtype',
            old_name='name',
            new_name='name_de',
        ),
        migrations.AddField(
            model_name='timeseriesyearlywaterlevel',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolboxproject',
            name='project_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesdailywaterlevel',
            unique_together={('station', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesyearlywaterlevel',
            unique_together={('station', 'year')},
        ),
        migrations.AddIndex(
            model_name='timeseriesdailywaterlevel',
            index=models.Index(fields=['station', 'date'], name='station_day_idx'),
        ),
        migrations.AddIndex(
            model_name='timeseriesyearlywaterlevel',
            index=models.Index(fields=['station', 'year'], name='station_year_idx'),
        ),
        migrations.RemoveField(
            model_name='timeseriesyearlywaterlevel',
            name='date',
        ),
    ]
