# Generated by Django 4.2 on 2025-10-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0410_rename_date_timeseriesmonthlywaterlevel_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolboxtype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
