# Generated by Django 4.2 on 2025-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0411_toolboxtype_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='gauge_zero',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
