# Generated by Django 4.2 on 2025-10-07 13:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0412_station_gauge_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
    ]
