# Generated by Django 4.2 on 2025-10-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0413_alter_station_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeseriesDailyQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.station')),
            ],
        ),
        migrations.AddIndex(
            model_name='timeseriesdailyq',
            index=models.Index(fields=['station', 'date'], name='q_station_day_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesdailyq',
            unique_together={('station', 'date')},
        ),
    ]
