# Generated by Django 4.2 on 2025-10-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0414_timeseriesdailyq_timeseriesdailyq_q_station_day_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolboxtype',
            name='name_tag',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
