# Generated by Django 4.2 on 2025-10-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0415_toolboxtype_name_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infiltrationproject',
            name='toolboxproject_ptr',
        ),
        migrations.RemoveField(
            model_name='infiltrationproject',
            name='weighting',
        ),
        migrations.DeleteModel(
            name='SinkDifference',
        ),
        migrations.DeleteModel(
            name='InfiltrationProject',
        ),
    ]
