# Generated by Django 4.2 on 2025-10-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0416_remove_infiltrationproject_toolboxproject_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfield',
            name='has_sieker_large_lake',
        ),
    ]
