# Generated by Django 4.2 on 2025-10-17 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0417_remove_userfield_has_sieker_large_lake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxproject',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
