# Generated by Django 4.2 on 2025-10-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0418_alter_toolboxproject_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxproject',
            name='user_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.userfield'),
        ),
    ]
