# Generated by Django 4.2 on 2025-10-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0419_alter_toolboxproject_user_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeTimeseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgwid', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('discharge_m3s', models.FloatField(blank=True, null=True)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_timeseries_stream', to='toolbox.lake')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.stream')),
            ],
        ),
    ]
