# Generated by Django 4.2 on 2025-10-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0420_dischargetimeseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargetimeseries',
            name='lake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_timeseries_lake', to='toolbox.lake'),
        ),
        migrations.AlterField(
            model_name='dischargetimeseries',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_timeseries_stream', to='toolbox.stream'),
        ),
    ]
