# Generated by Django 4.2 on 2025-10-22 14:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0421_alter_dischargetimeseries_lake_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quoek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom25833', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=25833)),
                ('geom4326', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('gewaesser', models.CharField(blank=True, max_length=100, null=True)),
                ('fgw_id', models.IntegerField(blank=True, null=True)),
                ('ezg25_km2', models.FloatField(blank=True, null=True)),
                ('mq_qn', models.FloatField(blank=True, null=True)),
                ('mnq_qn', models.FloatField(blank=True, null=True)),
                ('wkid_2021', models.IntegerField(blank=True, null=True)),
                ('kat_2021', models.CharField(blank=True, max_length=100, null=True)),
                ('typ_2021', models.CharField(blank=True, max_length=100, null=True)),
                ('mow_2021', models.FloatField(blank=True, null=True)),
                ('q_oek', models.FloatField(blank=True, null=True)),
                ('laenge_km', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
