# Generated by Django 4.2 on 2025-10-23 10:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0422_quoek'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom25833', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=25833)),
                ('fgw_id', models.IntegerField(blank=True, null=True)),
                ('w_gn1', models.CharField(blank=True, max_length=100, null=True)),
                ('w_gn2', models.CharField(blank=True, max_length=100, null=True)),
                ('e_area', models.FloatField(blank=True, null=True)),
                ('length_km', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='quoek',
            name='fgw_unterlauf_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
