# Generated by Django 4.2 on 2025-10-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0423_tempmodel_quoek_fgw_unterlauf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoek',
            name='gewaesser_gn2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
