# Generated by Django 4.2 on 2025-10-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0424_quoek_gewaesser_gn2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempModel',
        ),
    ]
