# Generated by Django 4.2 on 2025-10-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0425_delete_tempmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoek',
            name='fgw_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
