# Generated by Django 4.2 on 2025-10-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0426_alter_quoek_fgw_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoek',
            name='id',
        ),
        migrations.AlterField(
            model_name='quoek',
            name='fgw_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
