# Generated by Django 4.2 on 2025-10-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0427_remove_quoek_id_alter_quoek_fgw_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargetimeseries',
            old_name='fgwid',
            new_name='fgw',
        ),
    ]
