# Generated by Django 4.2 on 2025-10-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0428_rename_fgwid_dischargetimeseries_fgw'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargetimeseries',
            name='fgw_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.quoek'),
        ),
    ]
