# Generated by Django 4.2 on 2025-10-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0429_dischargetimeseries_fgw_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargetimeseries',
            name='fgw',
        ),
    ]
