# Generated by Django 4.2 on 2025-10-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0430_remove_dischargetimeseries_fgw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargetimeseries',
            old_name='fgw_id',
            new_name='fgw',
        ),
    ]
