# Generated by Django 4.2 on 2025-10-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0431_rename_fgw_id_dischargetimeseries_fgw'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='fgwx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.quoek'),
        ),
        migrations.AddField(
            model_name='stream',
            name='fgwx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.quoek'),
        ),
    ]
