# Generated by Django 4.2 on 2025-10-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0432_lake_fgwx_stream_fgwx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lake',
            name='fgw_id',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='fgw_id',
        ),
    ]
