# Generated by Django 4.2 on 2025-10-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0433_remove_lake_fgw_id_remove_stream_fgw_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lake',
            old_name='fgwx',
            new_name='fgw',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='fgwx',
            new_name='fgw',
        ),
    ]
