# Generated by Django 4.2 on 2025-10-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0434_rename_fgwx_lake_fgw_rename_fgwx_stream_fgw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SinkWeighting',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='geom_json',
        ),
    ]
