# Generated by Django 4.2 on 2025-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0435_delete_sinkweighting_remove_userfield_geom_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfield',
            old_name='has_zalf_enlarged_sinks',
            new_name='has_infiltration',
        ),
        migrations.RenameField(
            model_name='userfield',
            old_name='has_zalf_sinks',
            new_name='has_injection',
        ),
        migrations.AddField(
            model_name='userfield',
            name='has_sieker_drainage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userfield',
            name='has_sieker_wetland',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
