# Generated by Django 4.2 on 2025-10-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0436_rename_has_zalf_enlarged_sinks_userfield_has_infiltration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfield',
            name='comment',
        ),
        migrations.AddField(
            model_name='userfield',
            name='filter_bounds',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
