# Generated by Django 4.2 on 2025-10-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0437_remove_userfield_comment_userfield_filter_bounds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoek',
            old_name='fgw_id',
            new_name='id',
        ),
    ]
