# Generated by Django 4.2 on 2025-10-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0438_rename_fgw_id_quoek_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlargedsink',
            name='volume_construction_barrier',
        ),
    ]
