# Generated by Django 4.2 on 2025-10-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0440_pegelonline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PegelOnline',
        ),
    ]
