# Generated by Django 4.2 on 2025-10-28 08:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0441_delete_pegelonline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PegelOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=52)),
                ('number', models.IntegerField()),
                ('shortname', models.CharField(max_length=100)),
                ('longname', models.CharField(max_length=200)),
                ('km', models.FloatField()),
                ('agency', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('water_shortname', models.CharField(max_length=100)),
                ('water_longname', models.CharField(max_length=200)),
            ],
        ),
    ]
