# Generated by Django 4.2 on 2025-10-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0442_pegelonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegelonline',
            name='agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pegelonline',
            name='km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegelonline',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegelonline',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegelonline',
            name='longname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pegelonline',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegelonline',
            name='shortname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pegelonline',
            name='water_longname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pegelonline',
            name='water_shortname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
