# Generated by Django 4.2 on 2025-10-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0443_alter_pegelonline_agency_alter_pegelonline_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegelonline',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
