# Generated by Django 4.2 on 2025-10-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0444_alter_pegelonline_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekersink',
            name='distance_lake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siekersink',
            name='distance_stream',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siekersink',
            name='nearest_lake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.lake'),
        ),
        migrations.AddField(
            model_name='siekersink',
            name='nearest_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.stream'),
        ),
    ]
