# Generated by Django 4.2 on 2025-10-28 17:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0445_siekersink_distance_lake_siekersink_distance_stream_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrainageNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom25833', django.contrib.gis.db.models.fields.PolygonField(srid=25833)),
                ('geom4326', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('eww', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnownDrainages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom25833', django.contrib.gis.db.models.fields.PolygonField(srid=25833)),
                ('geom4326', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('eww', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
