# Generated by Django 4.2 on 2025-10-28 17:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0446_drainagenetwork_knowndrainages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drainagenetwork',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='knowndrainages',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
