# Generated by Django 4.2 on 2025-10-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0447_alter_drainagenetwork_geom4326_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drainagenetwork',
            name='eww',
        ),
        migrations.AddField(
            model_name='drainagenetwork',
            name='total_length_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drainagenetwork',
            name='type_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
