# Generated by Django 4.2 on 2025-10-28 17:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0448_remove_drainagenetwork_eww_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drainagenetwork',
            name='geom25833',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=25833),
        ),
        migrations.AlterField(
            model_name='drainagenetwork',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
