# Generated by Django 4.2 on 2025-10-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0449_alter_drainagenetwork_geom25833_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrainageNetworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('description_de', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
