# Generated by Django 4.2 on 2025-10-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0450_drainagenetworktype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drainagenetworktype',
            old_name='type',
            new_name='name',
        ),
        migrations.AddField(
            model_name='drainagenetwork',
            name='drainage_network_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.drainagenetworktype'),
        ),
    ]
