# Generated by Django 4.2 on 2025-10-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0451_rename_type_drainagenetworktype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drainagenetwork',
            name='type',
        ),
        migrations.RemoveField(
            model_name='drainagenetwork',
            name='type_detail',
        ),
    ]
