# Generated by Django 4.2 on 2025-10-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0452_remove_drainagenetwork_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrainageNetworkType',
            new_name='DrainageNetworkTypeDetail',
        ),
    ]
