# Generated by Django 4.2 on 2025-10-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0453_rename_drainagenetworktype_drainagenetworktypedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrainageNetworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='drainagenetwork',
            old_name='drainage_network_type',
            new_name='drainage_network_type_detail',
        ),
        migrations.RenameField(
            model_name='drainagenetworktypedetail',
            old_name='name',
            new_name='name_de',
        ),
        migrations.AddField(
            model_name='drainagenetworktypedetail',
            name='drainage_network_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='toolbox.drainagenetworktype'),
        ),
    ]
