# Generated by Django 4.2 on 2025-10-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0454_drainagenetworktype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drainagenetworktypedetail',
            name='name_de',
        ),
    ]
