# Generated by Django 4.2 on 2025-10-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0455_remove_drainagenetworktypedetail_name_de'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drainagenetworktypedetail',
            old_name='description_de',
            new_name='name_de',
        ),
    ]
