# Generated by Django 4.2 on 2025-10-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0456_rename_description_de_drainagenetworktypedetail_name_de'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drainagenetwork',
            old_name='drainage_network_type_detail',
            new_name='network_type_detail',
        ),
        migrations.RenameField(
            model_name='drainagenetworktypedetail',
            old_name='drainage_network_type',
            new_name='network_type',
        ),
    ]
