# Generated by Django 4.2 on 2025-10-29 15:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0457_rename_drainage_network_type_detail_drainagenetwork_network_type_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='construction_geom25833',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AddField(
            model_name='enlargedsink',
            name='construction_geom4326',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='enlargedsink',
            name='volume_construction_barrier',
            field=models.FloatField(null=True),
        ),
    ]
