# Generated by Django 4.2 on 2025-10-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0458_enlargedsink_construction_geom25833_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlargedsink',
            name='construction_height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='enlargedsink',
            name='construction_plat_width',
            field=models.FloatField(null=True),
        ),
    ]
