# Generated by Django 4.2 on 2025-10-29 15:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0459_enlargedsink_construction_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlargedsink',
            name='construction_geom25833',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='enlargedsink',
            name='construction_geom4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
