# Generated by Django 4.2 on 2025-10-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0460_alter_enlargedsink_construction_geom25833_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainagenetworktype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drainagenetworktype',
            name='name_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
