# Generated by Django 4.2 on 2025-11-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0461_drainagenetworktype_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrainageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='knowndrainages',
            name='drainage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.drainagetype'),
        ),
    ]
