# Generated by Django 4.2 on 2025-11-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0462_drainagetype_knowndrainages_drainage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainagetype',
            name='eww',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
