# Generated by Django 4.2 on 2025-11-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0463_drainagetype_eww'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowndrainages',
            name='eww',
        ),
        migrations.RemoveField(
            model_name='knowndrainages',
            name='type',
        ),
    ]
