# Generated by Django 4.2 on 2025-11-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0464_remove_knowndrainages_eww_remove_knowndrainages_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnownDrainages',
        ),
    ]
