# Generated by Django 4.2 on 2025-11-03 14:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0465_delete_knowndrainages'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownDrainages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom25833', django.contrib.gis.db.models.fields.PolygonField(srid=25833)),
                ('geom4326', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('drainage_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.drainagetype')),
            ],
        ),
    ]
