# Generated by Django 4.2 on 2025-11-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0466_knowndrainages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrainageType',
            new_name='KnownDrainageType',
        ),
    ]
