# Generated by Django 4.2 on 2025-11-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0467_rename_drainagetype_knowndrainagetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrainageNetwork',
        ),
    ]
