# Generated by Django 4.2 on 2025-11-03 16:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0468_delete_drainagenetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrainageNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom25833', django.contrib.gis.db.models.fields.LineStringField(srid=25833)),
                ('geom4326', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('total_length_m', models.FloatField(blank=True, null=True)),
                ('network_type_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.drainagenetworktypedetail')),
            ],
        ),
    ]
