# Generated by Django 4.2 on 2025-11-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0469_drainagenetwork'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnownDrainages',
            new_name='DrainedArea',
        ),
    ]
