# Generated by Django 4.2 on 2025-11-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0470_rename_knowndrainages_drainedarea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnownDrainageType',
            new_name='DrainedAreaType',
        ),
        migrations.RenameField(
            model_name='drainedarea',
            old_name='drainage_type',
            new_name='drained_area_type',
        ),
    ]
