# Generated by Django 4.2 on 2025-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0471_rename_knowndrainagetype_drainedareatype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainedareatype',
            name='name_tag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
