# Generated by Django 4.2 on 2025-11-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0472_drainedareatype_name_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainagenetworktypedetail',
            name='name_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
