# Generated by Django 4.2 on 2025-11-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0473_drainagenetworktypedetail_name_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='dash_array',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
