# Generated by Django 4.2 on 2025-11-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0474_datainfo_dash_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='legendgrade',
            name='ramp',
            field=models.BooleanField(default=False),
        ),
    ]
