# Generated by Django 4.2 on 2025-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0475_legendgrade_ramp'),
    ]

    operations = [
        migrations.AddField(
            model_name='legendgrade',
            name='color_value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
