# Generated by Django 4.2 on 2025-11-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0476_legendgrade_color_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekerwaterlevel',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.station'),
        ),
    ]
