# Generated by Django 4.2 on 2025-11-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0477_siekerwaterlevel_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siekerwaterlevel',
            old_name='messstelle',
            new_name='name',
        ),
    ]
