# Generated by Django 4.2 on 2025-11-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0478_rename_messstelle_siekerwaterlevel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siekerlargelake',
            old_name='t_cm_per_a',
            new_name='trend_cm_per_a',
        ),
    ]
