# Generated by Django 4.2 on 2025-11-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0479_rename_t_cm_per_a_siekerlargelake_trend_cm_per_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='select_feature_button',
            field=models.BooleanField(default=False),
        ),
    ]
