# Generated by Django 4.2 on 2025-11-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0480_datainfo_select_feature_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlargedsinkembankment',
            old_name='geom',
            new_name='geom25833',
        ),
        migrations.RemoveField(
            model_name='enlargedsinkembankment',
            name='centroid',
        ),
        migrations.RemoveField(
            model_name='enlargedsinkembankment',
            name='centroid4326',
        ),
    ]
