# Generated by Django 4.2 on 2025-11-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0481_rename_geom_enlargedsinkembankment_geom25833_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='feature_type',
            field=models.CharField(blank=True, default='polygon', max_length=255, null=True),
        ),
    ]
