# Generated by Django 4.2 on 2025-11-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0482_alter_datainfo_feature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxproject',
            name='user_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_projects', to='toolbox.userfield'),
        ),
    ]
