# Generated by Django 4.2 on 2025-11-21 08:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0483_alter_toolboxproject_user_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekersink',
            name='geom_single_25833',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833),
        ),
    ]
