# Generated by Django 4.2 on 2025-11-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0484_siekersink_geom_single_25833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siekersink',
            name='geom_single',
        ),
        migrations.RemoveField(
            model_name='siekersink',
            name='geom_single_25833',
        ),
    ]
