# Generated by Django 4.2 on 2025-11-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0485_remove_siekersink_geom_single_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siekersink',
            name='geom_remaining',
        ),
    ]
