# Generated by Django 4.2 on 2025-11-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0486_remove_siekersink_geom_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siekersink',
            name='geom4326',
        ),
    ]
