# Generated by Django 4.2 on 2025-11-21 10:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0487_remove_siekersink_geom4326'),
    ]

    operations = [
        migrations.AddField(
            model_name='siekersink',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
