# Generated by Django 4.2 on 2025-11-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0488_siekersink_geom4326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abovegroundwaters',
            old_name='hapt_ezg',
            new_name='haupt_ezg',
        ),
    ]
