# Generated by Django 4.2 on 2025-11-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0489_rename_hapt_ezg_abovegroundwaters_haupt_ezg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboveGroundWaters',
            new_name='BAboveGroundWaters',
        ),
    ]
