# Generated by Django 4.2 on 2025-11-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0490_rename_abovegroundwaters_babovegroundwaters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BelowGroundWaters',
            new_name='AboveGroundWaters',
        ),
    ]
