# Generated by Django 4.2 on 2025-11-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0491_rename_belowgroundwaters_abovegroundwaters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BAboveGroundWaters',
            new_name='BelowGroundWaters',
        ),
    ]
