# Generated by Django 4.2 on 2025-11-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0492_rename_babovegroundwaters_belowgroundwaters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboveGroundWaters',
            new_name='AboveGroundCatchmentArea',
        ),
    ]
