# Generated by Django 4.2 on 2025-11-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0493_rename_abovegroundwaters_abovegroundcatchmentarea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BelowGroundWaters',
            new_name='BelowGroundCatchmentArea',
        ),
    ]
