# Generated by Django 4.2 on 2025-11-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0494_rename_belowgroundwaters_belowgroundcatchmentarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abovegroundcatchmentarea',
            old_name='geom',
            new_name='geom25833',
        ),
    ]
