# Generated by Django 4.2 on 2025-11-25 11:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0495_rename_geom_abovegroundcatchmentarea_geom25833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='belowgroundcatchmentarea',
            old_name='geom',
            new_name='geom25833',
        ),
        migrations.AddField(
            model_name='abovegroundcatchmentarea',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
