# Generated by Django 4.2 on 2025-11-25 11:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0496_rename_geom_belowgroundcatchmentarea_geom25833_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='belowgroundcatchmentarea',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
