# Generated by Django 4.2 on 2025-11-27 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0497_belowgroundcatchmentarea_geom4326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gekretention',
            name='geom25833',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='gekretention',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
