# Generated by Django 4.2 on 2025-11-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0497_belowgroundcatchmentarea_geom4326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geklanduse',
            name='first_two_clc_digits',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
