# Generated by Django 4.2 on 2025-11-27 16:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0498_alter_gekretention_geom25833_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gekretention',
            name='geom25833',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='gekretention',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
