# Generated by Django 4.2 on 2025-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0498_alter_geklanduse_first_two_clc_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekretentionmeasure',
            name='prio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
