# Generated by Django 4.2 on 2025-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0499_gekretentionmeasure_prio'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekretentionmeasure',
            name='specific_document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
