# Generated by Django 4.2 on 2025-11-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0500_gekretentionmeasure_specific_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekretentionmeasure',
            name='kosten_aktuell',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
