# Generated by Django 4.2 on 2025-11-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0501_gekretentionmeasure_kosten_aktuell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gekretentionmeasure',
            old_name='prio',
            new_name='priority_value',
        ),
    ]
