# Generated by Django 4.2 on 2025-12-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0499_alter_gekretention_geom25833_and_more'),
        ('toolbox', '0502_rename_prio_gekretentionmeasure_priority_value'),
    ]

    operations = [
    ]
