# Generated by Django 4.2 on 2025-12-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0503_merge_20251201_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfoproperty',
            name='help_text',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
