# Generated by Django 4.2 on 2025-12-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0504_datainfoproperty_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafletlegend',
            name='ramp',
            field=models.BooleanField(default=False),
        ),
    ]
