# Generated by Django 4.2 on 2025-12-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0505_leafletlegend_ramp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legendgrade',
            name='ramp',
        ),
    ]
