# Generated by Django 4.2 on 2025-12-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0506_remove_legendgrade_ramp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legendgrade',
            old_name='color_value',
            new_name='color',
        ),
    ]
