# Generated by Django 4.2 on 2025-12-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0507_rename_color_value_legendgrade_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legendgrade',
            old_name='value',
            new_name='value_to_color',
        ),
    ]
