# Generated by Django 4.2 on 2025-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0508_rename_value_legendgrade_value_to_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legendgrade',
            name='value_to_color',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
