# Generated by Django 4.2 on 2025-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0509_alter_legendgrade_value_to_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfield',
            name='toolbox_types',
            field=models.ManyToManyField(blank=True, related_name='user_fields', to='toolbox.toolboxtype'),
        ),
    ]
