# Generated by Django 4.2 on 2025-12-15 08:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0510_userfield_toolbox_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
    ]
