# Generated by Django 4.2 on 2025-12-15 08:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0511_injectionraster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectionraster',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(srid=25833),
        ),
    ]
