# Generated by Django 4.2 on 2025-12-15 09:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0512_alter_injectionraster_rast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlineinjection',
            name='geom',
        ),
        migrations.AddField(
            model_name='outlineinjection',
            name='geom25833',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833, verbose_name='Injection'),
        ),
        migrations.AddField(
            model_name='outlineinjection',
            name='geom4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
