# Generated by Django 4.2 on 2025-12-15 12:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0513_remove_outlineinjection_geom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineDrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('geom25833', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25833, verbose_name='Injection')),
                ('geom4326', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
