# Generated by Django 4.2 on 2026-05-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0514_outlinedrainage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InjectionRaster',
        ),
    ]
