# Generated by Django 4.2 on 2026-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0515_delete_injectionraster'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='q_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='q_mean',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
