
volumes:
#   # raster_data:
  database_data:
#   # app_data:
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.django

    volumes:
      - ./app_data:/app_data

    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG} # TODO set via env var in production
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY} # TODO set via env var in production   
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS} # TODO set via env var in production
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

      GEOSERVER_URL: http://geoserver:8080/geoserver
      GEOSERVER_USER: ${GEOSERVER_USER}
      GEOSERVER_PASS: ${GEOSERVER_PASS}

      THREDDS_URL: http://thredds:8080/thredds

      DWD_HOST: ${DWD_HOST}
      DWD_USERNAME: ${DWD_USERNAME}
      DWD_PASSWORD: ${DWD_PASSWORD}
      DWD_PORT: ${DWD_PORT}

      CLIM4CAST_FTP_SERVER: ${CLIM4CAST_FTP_SERVER}
      CLIM4CAST_SFTP_USER: ${CLIM4CAST_SFTP_USER}
      CLIM4CAST_SFTP_PORT: ${CLIM4CAST_SFTP_PORT}
      CLIM4CAST_SFTP_PASSWORD: ${CLIM4CAST_SFTP_PASSWORD}
      
      
    container_name: swn_geo_django
    depends_on:
      - db
    networks:
      - swn_network

  # Postgres database
  db:
    image: postgis/postgis:14-3.3

    #user: 1000:1000 
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

    container_name: swn_postgis
    networks:
      - swn_network

  # #geoserver for visualisation and sharing of geodata
  geoserver:
    image: kartoza/geoserver:2.25.2 # new 2025-09-25
    #user: "1000:1000"
    container_name: swn_geoserver
    volumes:
      # - ./geoserver/data:/opt/geoserver/data
      # - ./app/raster_data:/opt/geoserver/raster_data
      - ./app_data/toolbox/raster_data:/opt/geoserver/data/raster_data
      - ./app_data/toolbox/raster_styles:/opt/geoserver/data/raster_styles
    environment:
      GEOSERVER_ADMIN_USER: ${GEOSERVER_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_PASS}
      GEOSERVER_DATA_DIR: /opt/geoserver/data
      GEOSERVER_RASTER_DATA_DIR: /opt/geoserver/raster_data
      # - CATALINA_TMPDIR=/geoserver_data/data/work
    
    depends_on:
      - db
    networks:
      - swn_network

  redis:
    image: redis:latest
    container_name: swn_redis
    networks:
      - swn_network

  # thredds for sharing of netcdf data
  thredds:
    build:
      context: .
      dockerfile: Dockerfile.thredds
    container_name: swn_thredds
    volumes:
      - ./thredds_tomcat/tomcat_logs:/usr/local/tomcat/logs/
      - ./thredds_tomcat/thredds_logs:/usr/local/tomcat/content/thredds/logs/
      # - ./app/klim4cast/data/netcdf:/usr/local/tomcat/content/thredds/public/data/Klim4Cast
      - ./app_data/klim4cast/netcdf:/usr/local/tomcat/content/thredds/public/data/Klim4Cast
      # - ./thredds_data/data/DWD_Data:/usr/local/tomcat/content/thredds/public/data/DWD_Data
      - ./app_data/monica/netcdf_hindcast:/usr/local/tomcat/content/thredds/public/data/DWD_Data

    depends_on:
      - db
    networks:
      - swn_network


  # MONICA
  monica:
    image: zalfrpm/monica-cluster:3.6.35.shared_id

    container_name: swn_monica

    expose:
      - 6666  # monica_producer_port
      - 6677  # monica_intern_in_port
      - 7777  # monica_consumer_port
      - 7788  # monica_intern_out_port
    environment:
      - monica_proxy_out_mode=-prs
    networks:
      - swn_network


  # TODO Django Celery: https://www.youtube.com/watch?v=CWF-pTr1p68&list=PLOLrQ9Pn6cayGytG1fgUPEsUp3Onol8V7&index=5
networks:
  swn_network:

