FROM unidata/thredds-docker:5.4

LABEL maintainer="Colja"

COPY ./thredds_config/catalog.xml /usr/local/tomcat/content/thredds/catalog.xml
COPY ./thredds_config/threddsConfig.xml /usr/local/tomcat/content/thredds/threddsConfig.xml
COPY ./thredds_data/ /usr/local/tomcat/content/thredds/public/

WORKDIR /usr/local/tomcat/

