FROM unidata/thredds-docker:5.4

LABEL maintainer="Colja"

COPY ./thredds_config/catalog.xml /usr/local/tomcat/content/thredds/catalog.xml
COPY ./thredds_config/threddsConfig.xml /usr/local/tomcat/content/thredds/threddsConfig.xml
COPY ./app/klim4cast/data/netcdf /usr/local/tomcat/content/thredds/public/data/Klim4Cast

COPY ./thredds_data/DWD_Data /usr/local/tomcat/content/thredds/public/data/DWD_Data


WORKDIR /usr/local/tomcat/

