"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')


# AUTH_USER_MODEL = 'user.User'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-hl9ukq&o_m6c&^7co0-qlivgsq%f^ouhu5j(vc21sk8!xmf-h*')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get('DJANGO_DEBUG', 0)))



if DEBUG == True:
    ALLOWED_HOSTS = ['10.10.88.183', 'srv-pb4-spreedev.zalf.de', '127.0.0.1', 'localhost' ]
else:
    ALLOWED_HOSTS = ['srv-pb4-spreedev.zalf.de', 'klima-hub.zalf.de']

ALLOWED_HOSTS_ENV = os.environ.get('DJANGO_ALLOWED_HOSTS')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS.extend(ALLOWED_HOSTS_ENV.split(','))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.forms',
    'django_extensions',
    'django_filters',

    'utilities',

    'swn',
    'toolbox',
    'monica',
    'klim4cast',
    'buek',

    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'sass_processor',
    'debug_toolbar',
    'leaflet',
    'djgeojson',
    'django_bootstrap5',
    'django_select2',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_celery_beat',
    # 'raster',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    # 'geoip2_extras.middleware.GeoIP2Middleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'HOST': os.environ.get('DB_HOST'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
    }
}

THREDDS_URL = os.environ.get('THREDDS_URL')
THREDDS_CATALOG_XML = f"{THREDDS_URL}/catalog/data/Klim4Cast/catalog.xml"

# other data
APP_DATA_DIR =  Path(__file__).resolve().parent.parent.parent.joinpath('app_data')
# django app monica
MONICA_DATA_DIR = APP_DATA_DIR.joinpath('monica')
MONICA_NETCDF_FORECAST_DIR = MONICA_DATA_DIR.joinpath('netcdf_forecast')
MONICA_NETCDF_HINDCAST_DIR = MONICA_DATA_DIR.joinpath('netcdf_hindcast')
MONICA_RASTER_DATA_DIR = MONICA_DATA_DIR.joinpath('raster_data')
# django app klim4cast
KLIM4CAST_DATA_DIR = os.path.join(APP_DATA_DIR, 'klim4cast')
KLIM4CAST_DATA = os.path.join(KLIM4CAST_DATA_DIR, 'chech_globe_data')
KLIM4CAST_NETCDF_DIR = os.path.join(KLIM4CAST_DATA_DIR, 'netcdf')

# django app toolbox
TOOLBOX_DATA_DIR = os.path.join(APP_DATA_DIR, 'toolbox')
TOOLBOX_RASTER_DATA_DIR = os.path.join(TOOLBOX_DATA_DIR, 'raster_data')
TOOLBOX_RASTER_OUTPUT_DIR = os.path.join(TOOLBOX_DATA_DIR, 'raster_output')



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {  # TODO change min length
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 4}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]






# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'de' 
LANGUAGES = [
    ('de', 'Deutsch'),
    ('en', 'English'),
    ]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]
USE_L10N = True  # Enables localized formatting of data
USE_I18N = True  # Enables Django's translation system
TIME_ZONE = 'Europe/Berlin'
USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/static/'
MEDIA_URL = '/static/media/'
STATICFILES_DIRS = [
    STATIC_DIR,
    Path.joinpath(BASE_DIR, 'swn/static/'),
    Path.joinpath(BASE_DIR, 'monica/static/'),
    Path.joinpath(BASE_DIR, 'toolbox/static/'),
    # Path.joinpath(BASE_DIR, 'buek/static/'),
    Path.joinpath(BASE_DIR, 'klim4cast/static/'),
    ]

# https://pypi.org/project/django-sass-processor/
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
    
]

SASS_PROCESSOR_OPTIONS = {
    'source_map_enabled': False,
}


STATIC_ROOT = '/vol/web/static'
MEDIA_ROOT = '/vol/web/static/media'

LOGIN_URL = 'login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# for Debug Toolbar, the internal IPS are necessary
if DEBUG:
    import socket  
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [
        ip[: ip.rfind('.')] + '.1' for ip in ips] + ['127.0.0.1', '10.0.2.2']
    

# INTERNAL_IPS = [
#     '127.0.0.1',
#     '0.0.0.0',
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# GIS Leaflet
SERIALIZATION_MODULES = {
    'geojson': 'djgeojson.serializers',
}

# COOKIES andd SESSIONS
SESSION_COOKIE_AGE = 1209600 # 2 weeks - is the default
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# # Use secure cookies for better security (if using HTTPS)
# SESSION_COOKIE_SECURE = True  # Only send the cookie over HTTPS
# # Use HttpOnly to prevent JavaScript access to the cookie
# SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to the cookie

CRISPY_ALLOWED_TEMPLATE_PACKS = ('bootstrap5',)

CRISPY_TEMPLATE_PACK = 'bootstrap5'
CRISPY_FAIL_SILENTLY = not DEBUG


FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

# Celery
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Berlin'


GEOSERVER_URL = os.environ.get("GEOSERVER_URL", "http://geoserver:8080/geoserver")
GEOSERVER_USER = os.environ.get("GEOSERVER_USER", "")
GEOSERVER_PASS = os.environ.get("GEOSERVER_PASS", "")