# Generated by Django 4.2 on 2024-02-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
