# Generated by Django 4.2 on 2024-02-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0002_crop_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MineralFertiliser',
        ),
    ]
