# Generated by Django 4.2 on 2024-02-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0003_delete_mineralfertiliser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralFertiliser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carbamid', models.FloatField()),
                ('nh4', models.FloatField()),
                ('no3', models.FloatField()),
                ('fertiliser_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganicFertiliser',
            fields=[
                ('aom_dry_matter_content', models.FloatField()),
                ('aom_fast_dec_coeff_standard', models.FloatField()),
                ('aom_nh4_content', models.FloatField()),
                ('aom_no3_content', models.FloatField()),
                ('aom_slow_dec_coeff_standard', models.FloatField()),
                ('cn_ratio_aom_fast', models.FloatField()),
                ('cn_ratio_aom_slow', models.FloatField()),
                ('n_concentration', models.FloatField()),
                ('part_aom_slow_to_smb_fast', models.FloatField()),
                ('part_aom_slow_to_smb_slow', models.FloatField()),
                ('part_aom_to_aom_fast', models.FloatField()),
                ('part_aom_to_aom_slow', models.FloatField()),
                ('fertiliser_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
