# Generated by Django 4.2 on 2024-03-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0004_mineralfertiliser_organicfertiliser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='organ_ids_for_cutting',
        ),
    ]
