# Generated by Django 4.2 on 2024-03-01 09:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0006_crop_organ_ids_for_cutting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='organ_ids_for_cutting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
