# Generated by Django 4.2 on 2024-03-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0007_alter_crop_organ_ids_for_cutting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSpeciesParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboveground_organ', models.JSONField(default=list)),
                ('assimilate_reallocation', models.FloatField()),
                ('base_temperature', models.JSONField(default=list)),
                ('carboxylation_pathway', models.IntegerField()),
                ('critical_oxygen_content', models.JSONField(default=list)),
                ('cutting_delay_days', models.IntegerField()),
                ('default_radiation_use_efficiency', models.FloatField()),
                ('development_acceleration_by_nitrogen_stress', models.FloatField()),
                ('drought_impact_on_fertility_factor', models.FloatField()),
                ('field_condition_modifier', models.FloatField()),
                ('initial_kc_factor', models.FloatField()),
                ('initial_organ_biomass', models.JSONField(default=list)),
                ('initial_rooting_depth', models.FloatField()),
                ('limiting_temperature_heat_stress', models.FloatField()),
                ('luxury_n_coeff', models.FloatField()),
                ('max_crop_diameter', models.FloatField()),
                ('max_n_uptake_param', models.FloatField()),
                ('minimum_n_concentration', models.FloatField()),
                ('minimum_temperature_for_assimilation', models.FloatField()),
                ('minimum_temperature_root_growth', models.FloatField()),
                ('n_concentration_aboveground_biomass', models.FloatField()),
                ('n_concentration_b0', models.FloatField()),
                ('n_concentration_pn', models.FloatField()),
                ('n_concentration_root', models.FloatField()),
                ('organ_growth_respiration', models.JSONField(default=list)),
                ('organ_maintenance_respiration', models.JSONField(default=list)),
                ('part_biological_n_fixation', models.FloatField()),
                ('plant_density', models.IntegerField()),
                ('root_distribution_param', models.FloatField()),
                ('root_form_factor', models.FloatField()),
                ('root_growth_lag', models.IntegerField()),
                ('root_penetration_rate', models.FloatField()),
                ('sampling_depth', models.FloatField()),
                ('species_name', models.CharField(max_length=100)),
                ('specific_root_length', models.FloatField()),
                ('stage_after_cut', models.IntegerField()),
                ('stage_at_max_diameter', models.IntegerField()),
                ('stage_at_max_height', models.IntegerField()),
                ('stage_max_root_n_concentration', models.JSONField(default=list)),
                ('storage_organ', models.JSONField(default=list)),
                ('target_n30', models.FloatField()),
                ('target_n_sampling_depth', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('stage_mobil_from_storage_coeff', models.JSONField(default=list)),
            ],
        ),
        migrations.RenameModel(
            old_name='Crop',
            new_name='CropParameters',
        ),
    ]
