# Generated by Django 4.2 on 2024-03-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0008_cropspeciesparameters_rename_crop_cropparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_dry_matter_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_dry_matter_content_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_fast_dec_coeff_standard',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='aboveground_organ',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='assimilate_reallocation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='base_temperature',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='carboxylation_pathway',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='critical_oxygen_content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='cutting_delay_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='default_radiation_use_efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='development_acceleration_by_nitrogen_stress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='drought_impact_on_fertility_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='field_condition_modifier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='initial_kc_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='initial_organ_biomass',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='initial_rooting_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='limiting_temperature_heat_stress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='luxury_n_coeff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='max_crop_diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='max_n_uptake_param',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='minimum_n_concentration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='minimum_temperature_for_assimilation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='minimum_temperature_root_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='n_concentration_aboveground_biomass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='n_concentration_b0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='n_concentration_pn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='n_concentration_root',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='organ_growth_respiration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='organ_maintenance_respiration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='part_biological_n_fixation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='plant_density',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='root_distribution_param',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='root_form_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='root_growth_lag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='root_penetration_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='sampling_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='specific_root_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='stage_after_cut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='stage_at_max_diameter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='stage_at_max_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='stage_max_root_n_concentration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='stage_mobil_from_storage_coeff',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='storage_organ',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='target_n30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropspeciesparameters',
            name='target_n_sampling_depth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
