# Generated by Django 4.2 on 2024-03-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0009_alter_cropresidueparameters_aom_dry_matter_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CropParameters',
            new_name='CultivarParameters',
        ),
    ]
