# Generated by Django 4.2 on 2024-03-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0010_rename_cropparameters_cultivarparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivarparameters',
            name='crop_species_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
