# Generated by Django 4.2 on 2024-03-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0011_cultivarparameters_crop_species_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='crop_species_name',
            new_name='crop_name',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='name',
        ),
    ]
