# Generated by Django 4.2 on 2024-03-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0012_rename_crop_species_name_cultivarparameters_crop_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CropSpeciesParameters',
            new_name='SpeciesParameters',
        ),
    ]
