# Generated by Django 4.2 on 2024-03-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0013_rename_cropspeciesparameters_speciesparameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='crop_name',
            new_name='species_name',
        ),
    ]
