# Generated by Django 4.2 on 2024-03-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0014_rename_crop_name_cultivarparameters_species_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCropParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canopy_reflection_coefficient', models.FloatField()),
                ('growth_respiration_parameter1', models.FloatField()),
                ('growth_respiration_parameter2', models.FloatField()),
                ('growth_respiration_redux', models.FloatField()),
                ('maintenance_respiration_parameter1', models.FloatField()),
                ('maintenance_respiration_parameter2', models.FloatField()),
                ('max_crop_n_demand', models.FloatField()),
                ('minimum_available_n', models.FloatField()),
                ('minimum_n_concentration_root', models.FloatField()),
                ('reference_albedo', models.FloatField()),
                ('reference_leaf_area_index', models.FloatField()),
                ('reference_max_assimilation_rate', models.FloatField()),
                ('saturation_beta', models.FloatField()),
                ('stomata_conductance_alpha', models.FloatField()),
                ('tortuosity', models.FloatField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
