# Generated by Django 4.2 on 2024-03-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0015_generalcropparameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineralfertiliser',
            old_name='type',
            new_name='str_id',
        ),
    ]
