# Generated by Django 4.2 on 2024-03-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0016_rename_type_mineralfertiliser_str_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_dry_matter_content_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_fast_dec_coeff_standard_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_fast_dec_coeff_standard_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_nh4_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_nh4_content_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_nh4_content_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_no3_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_no3_content_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_no3_content_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_slow_dec_coeff_standard',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_slow_dec_coeff_standard_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='aom_slow_dec_coeff_standard_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='cn_ratio_aom_fast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='cn_ratio_aom_fast_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='cn_ratio_aom_fast_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='cn_ratio_aom_slow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='cn_ratio_aom_slow_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='cn_ratio_aom_slow_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='corg_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='corg_content_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='corg_content_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='n_concentration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='n_concentration_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='n_concentration_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_slow_to_smb_fast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_slow_to_smb_fast_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_slow_to_smb_fast_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_slow_to_smb_slow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_slow_to_smb_slow_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_slow_to_smb_slow_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_to_aom_fast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_to_aom_fast_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_to_aom_fast_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_to_aom_slow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_to_aom_slow_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='part_aom_to_aom_slow_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
