# Generated by Django 4.2 on 2024-03-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0017_alter_cropresidueparameters_aom_dry_matter_content_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropresidueparameters',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
