# Generated by Django 4.2 on 2024-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0018_cropresidueparameters_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='residue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
