# Generated by Django 4.2 on 2024-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0019_alter_cropresidueparameters_residue_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganicFertiliser',
        ),
        migrations.RemoveField(
            model_name='mineralfertiliser',
            name='str_id',
        ),
        migrations.AlterField(
            model_name='mineralfertiliser',
            name='carbamid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mineralfertiliser',
            name='fertiliser_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mineralfertiliser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mineralfertiliser',
            name='nh4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mineralfertiliser',
            name='no3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
