# Generated by Django 4.2 on 2024-03-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0021_organicfertiliser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganicFertiliser',
        ),
    ]
