# Generated by Django 4.2 on 2024-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0022_delete_organicfertiliser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganicFertiliser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aom_dry_matter_content', models.FloatField(blank=True, null=True)),
                ('aom_fast_dec_coeff_standard', models.FloatField(blank=True, null=True)),
                ('aom_nh4_content', models.FloatField(blank=True, null=True)),
                ('aom_no3_content', models.FloatField(blank=True, null=True)),
                ('aom_slow_dec_coeff_standard', models.FloatField(blank=True, null=True)),
                ('cn_ratio_aom_fast', models.FloatField(blank=True, null=True)),
                ('cn_ratio_aom_slow', models.FloatField(blank=True, null=True)),
                ('n_concentration', models.FloatField(blank=True, null=True)),
                ('part_aom_slow_to_smb_fast', models.FloatField(blank=True, null=True)),
                ('part_aom_slow_to_smb_slow', models.FloatField(blank=True, null=True)),
                ('part_aom_to_aom_fast', models.FloatField(blank=True, null=True)),
                ('part_aom_to_aom_slow', models.FloatField(blank=True, null=True)),
                ('fertiliser_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
