# Generated by Django 4.2 on 2024-03-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0023_organicfertiliser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineralfertiliser',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
