# Generated by Django 4.2 on 2024-03-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0024_mineralfertiliser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEnvironmentParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albedo', models.FloatField()),
                ('rcp', models.CharField(max_length=10)),
                ('atmospheric_co2', models.FloatField()),
                ('atmospheric_co2s', models.JSONField(default=dict)),
                ('yearly_co2_values', models.JSONField(default=dict)),
                ('leaching_depth', models.FloatField()),
                ('max_groundwater_depth', models.FloatField()),
                ('min_groundwater_depth', models.FloatField()),
                ('min_groundwater_depth_month', models.IntegerField()),
                ('wind_speed_height', models.FloatField()),
                ('time_step', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
