# Generated by Django 4.2 on 2024-03-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0025_generalenvironmentparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSoilMoistureParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_rain', models.FloatField()),
                ('correction_snow', models.FloatField()),
                ('critical_moisture_depth', models.FloatField()),
                ('evaporation_zeta', models.FloatField()),
                ('groundwater_discharge', models.FloatField()),
                ('hydraulic_conductivity_redux', models.FloatField()),
                ('kc_factor', models.FloatField()),
                ('max_percolation_rate', models.FloatField()),
                ('maximum_evaporation_impact_depth', models.FloatField()),
                ('moisture_init_value', models.FloatField()),
                ('new_snow_density_min', models.FloatField()),
                ('refreeze_parameter1', models.FloatField()),
                ('refreeze_parameter2', models.FloatField()),
                ('refreeze_temperature', models.FloatField()),
                ('saturated_hydraulic_conductivity', models.FloatField()),
                ('snow_accumulation_threshold_temperature', models.FloatField()),
                ('snow_max_additional_density', models.FloatField()),
                ('snow_melt_temperature', models.FloatField()),
                ('snow_packing', models.FloatField()),
                ('snow_retention_capacity_max', models.FloatField()),
                ('snow_retention_capacity_min', models.FloatField()),
                ('surface_roughness', models.FloatField()),
                ('temperature_limit_for_liquid_water', models.FloatField()),
                ('xsa_critical_soil_moisture', models.FloatField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
