# Generated by Django 4.2 on 2024-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0027_generalsoilorganicparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSoilTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.FloatField()),
                ('diffusion_coefficient_standard', models.FloatField()),
                ('dispersion_length', models.FloatField()),
                ('n_deposition', models.FloatField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
