# Generated by Django 4.2 on 2024-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0028_generalsoiltransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalenvironmentparameters',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
