# Generated by Django 4.2 on 2024-03-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0029_generalenvironmentparameters_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralEnvironmentParameters',
            new_name='UserEnvironmentParameters',
        ),
        migrations.CreateModel(
            name='SimulationEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('debug_mode', models.BooleanField(default=True)),
                ('params', models.JSONField()),
                ('general_soil_moisture_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.generalsoilmoistureparameters')),
                ('general_soil_organic_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.generalsoilorganicparameters')),
                ('general_soil_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.generalsoiltransport')),
                ('user_environment_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.userenvironmentparameters')),
            ],
        ),
    ]
