# Generated by Django 4.2 on 2024-03-21 14:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0030_rename_generalenvironmentparameters_userenvironmentparameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='type',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='type',
        ),
        migrations.AddField(
            model_name='simulationenvironment',
            name='crop_rotation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.speciesparameters')),
            ],
        ),
    ]
