# Generated by Django 4.2 on 2024-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0031_remove_cropresidueparameters_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesparameters',
            name='type',
        ),
        migrations.AddField(
            model_name='speciesparameters',
            name='maximum_temperature_for_assimilation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesparameters',
            name='optimum_temperature_for_assimilation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
