# Generated by Django 4.2 on 2024-03-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0032_remove_speciesparameters_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CultivarParameters',
        ),
    ]
