# Generated by Django 4.2 on 2024-03-21 17:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0033_delete_cultivarparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivarParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(blank=True, max_length=100)),
                ('assimilate_partitioning_coeff', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('base_daylength', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('base_daylength_unit', models.CharField(max_length=10)),
                ('begin_sensitive_phase_heat_stress', models.FloatField()),
                ('begin_sensitive_phase_heat_stress_unit', models.CharField(max_length=10)),
                ('critical_temperature_heat_stress', models.FloatField()),
                ('critical_temperature_heat_stress_unit', models.CharField(max_length=10)),
                ('crop_height_p1', models.FloatField()),
                ('crop_height_p2', models.FloatField()),
                ('crop_specific_max_rooting_depth', models.FloatField()),
                ('cultivar_name', models.CharField(max_length=100)),
                ('daylength_requirement', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('daylength_requirement_unit', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('drought_stress_threshold', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('end_sensitive_phase_heat_stress', models.FloatField()),
                ('end_sensitive_phase_heat_stress_unit', models.CharField(max_length=10)),
                ('frost_dehardening', models.FloatField()),
                ('frost_hardening', models.FloatField()),
                ('heat_sum_irrigation_end', models.FloatField()),
                ('heat_sum_irrigation_start', models.FloatField()),
                ('lt50_cultivar', models.FloatField()),
                ('latest_harvest_doy', models.IntegerField()),
                ('low_temperature_exposure', models.FloatField()),
                ('max_assimilation_rate', models.FloatField()),
                ('max_crop_height', models.FloatField()),
                ('max_crop_height_unit', models.CharField(max_length=10)),
                ('optimum_temperature', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('optimum_temperature_unit', models.CharField(max_length=10)),
                ('organ_ids_for_cutting', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('organ_ids_for_primary_yield', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('organ_ids_for_secondary_yield', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('organ_senescence_rate', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('perennial', models.BooleanField()),
                ('residue_n_ratio', models.FloatField()),
                ('respiratory_stress', models.FloatField()),
                ('specific_leaf_area', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('specific_leaf_area_unit', models.CharField(max_length=10)),
                ('stage_kc_factor', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('stage_kc_factor_unit', models.CharField(max_length=10)),
                ('stage_temperature_sum', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('stage_temperature_sum_unit', models.CharField(max_length=10)),
                ('vernalisation_requirement', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
    ]
