# Generated by Django 4.2 on 2024-03-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0034_cultivarparameters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralCropParameters',
            new_name='UserCropParameters',
        ),
    ]
