# Generated by Django 4.2 on 2024-03-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0035_rename_generalcropparameters_usercropparameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenvironmentparameters',
            name='type',
        ),
    ]
