# Generated by Django 4.2 on 2024-03-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0037_usersoilmoistureparameters_usersoilorganicparameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercropparameters',
            name='type',
        ),
    ]
