# Generated by Django 4.2 on 2024-03-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0038_remove_usercropparameters_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTemperatureModuleParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_temperature', models.FloatField()),
                ('initial_surface_temperature', models.FloatField()),
                ('density_air', models.FloatField()),
                ('specific_heat_capacity_air', models.FloatField()),
                ('density_humus', models.FloatField()),
                ('specific_heat_capacity_humus', models.FloatField()),
                ('density_water', models.FloatField()),
                ('specific_heat_capacity_water', models.FloatField()),
                ('quartz_raw_density', models.FloatField()),
                ('specific_heat_capacity_quartz', models.FloatField()),
                ('n_tau', models.FloatField()),
                ('soil_albedo', models.FloatField()),
                ('soil_moisture', models.FloatField()),
            ],
        ),
    ]
