# Generated by Django 4.2 on 2024-03-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0039_soiltemperaturemoduleparameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='base_daylength_unit',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='begin_sensitive_phase_heat_stress_unit',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='critical_temperature_heat_stress_unit',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='daylength_requirement_unit',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='end_sensitive_phase_heat_stress_unit',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='max_crop_height_unit',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='optimum_temperature_unit',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='specific_leaf_area_unit',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='stage_kc_factor_unit',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='stage_temperature_sum_unit',
        ),
    ]
