# Generated by Django 4.2 on 2024-03-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0040_remove_cultivarparameters_base_daylength_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='aom_dry_matter_content_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='aom_dry_matter_content_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='aom_fast_dec_coeff_standard_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='aom_fast_dec_coeff_standard_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='aom_nh4_content_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='aom_nh4_content_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='aom_no3_content_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='aom_no3_content_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='aom_slow_dec_coeff_standard_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='aom_slow_dec_coeff_standard_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='cn_ratio_aom_fast_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='cn_ratio_aom_fast_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='cn_ratio_aom_slow_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='cn_ratio_aom_slow_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='corg_content_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='corg_content_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='n_concentration_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='n_concentration_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='part_aom_slow_to_smb_fast_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='part_aom_slow_to_smb_fast_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='part_aom_slow_to_smb_slow_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='part_aom_slow_to_smb_slow_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='part_aom_to_aom_fast_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='part_aom_to_aom_fast_unit',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='part_aom_to_aom_slow_description',
        ),
        migrations.RemoveField(
            model_name='cropresidueparameters',
            name='part_aom_to_aom_slow_unit',
        ),
    ]
