# Generated by Django 4.2 on 2024-03-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0041_remove_cropresidueparameters_aom_dry_matter_content_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organicfertiliser',
            old_name='fertiliser_id',
            new_name='fertiliser_char_id',
        ),
        migrations.RemoveField(
            model_name='organicfertiliser',
            name='type',
        ),
    ]
