# Generated by Django 4.2 on 2024-03-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0042_rename_fertiliser_id_organicfertiliser_fertiliser_char_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='ammonia_oxidation_rate_coeff_standard_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='atmospheric_resistance_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='immobilisation_rate_coeff_nh4_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='immobilisation_rate_coeff_no3_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='inhibitor_nh3_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='limit_clay_effect_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='moisture_dec_optimal_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='n2o_production_rate_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='nitrite_oxidation_rate_coeff_standard_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='smb_fast_death_rate_standard_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='smb_fast_maint_rate_standard_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='smb_slow_death_rate_standard_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='smb_slow_maint_rate_standard_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='smb_utilization_efficiency_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='som_fast_dec_coeff_standard_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='som_slow_dec_coeff_standard_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='spec_anaerob_denitrification_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='temp_dec_optimal_unit',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='transport_rate_coeff_unit',
        ),
    ]
