# Generated by Django 4.2 on 2024-03-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0043_remove_usersoilorganicparameters_ammonia_oxidation_rate_coeff_standard_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('workstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monica.workstep')),
            ],
            bases=('monica.workstep',),
        ),
        migrations.CreateModel(
            name='Tillage',
            fields=[
                ('workstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monica.workstep')),
                ('tillage_depth', models.FloatField()),
            ],
            bases=('monica.workstep',),
        ),
        migrations.RenameField(
            model_name='workstep',
            old_name='harvest_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='workstep',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='workstep',
            name='sowing_date',
        ),
        migrations.CreateModel(
            name='Sowing',
            fields=[
                ('workstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monica.workstep')),
                ('plant_density', models.IntegerField()),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.cultivarparameters')),
                ('residue_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.cropresidueparameters')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.speciesparameters')),
            ],
            bases=('monica.workstep',),
        ),
        migrations.CreateModel(
            name='OrganicFertilization',
            fields=[
                ('workstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monica.workstep')),
                ('amount', models.FloatField()),
                ('incorporation', models.BooleanField()),
                ('organic_fertiliser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.organicfertiliser')),
            ],
            bases=('monica.workstep',),
        ),
        migrations.CreateModel(
            name='MineralFertilization',
            fields=[
                ('workstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monica.workstep')),
                ('amount', models.FloatField()),
                ('mineral_fertiliser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.mineralfertiliser')),
            ],
            bases=('monica.workstep',),
        ),
    ]
