# Generated by Django 4.2 on 2024-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0044_harvest_tillage_rename_harvest_date_workstep_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(blank=True, max_length=100)),
                ('organ_name', models.CharField(blank=True, max_length=100)),
                ('initial_organ_biomass', models.FloatField(blank=True, null=True)),
                ('organ_maintainance_respiration', models.FloatField(blank=True, null=True)),
                ('organ_growth_respiration', models.FloatField(blank=True, null=True)),
                ('is_above_ground', models.BooleanField(blank=True, null=True)),
                ('is_stoarge_organ', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
