# Generated by Django 4.2 on 2024-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0045_organ'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='organ_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
