# Generated by Django 4.2 on 2024-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0046_organ_organ_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('to_layers', models.BooleanField()),
                ('to_organs', models.BooleanField()),
                ('settable', models.BooleanField()),
                ('output_unit', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
