# Generated by Django 4.2 on 2024-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0047_outputevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputevents',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outputevents',
            name='settable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outputevents',
            name='to_layers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outputevents',
            name='to_organs',
            field=models.BooleanField(default=False),
        ),
    ]
