# Generated by Django 4.2 on 2024-03-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0048_alter_outputevents_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
