# Generated by Django 4.2 on 2024-03-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0049_outputaggregation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organ',
            new_name='OrganFromDB',
        ),
    ]
