# Generated by Django 4.2 on 2024-03-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0051_organ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputevents',
            old_name='output_unit',
            new_name='unit',
        ),
    ]
