# Generated by Django 4.2 on 2024-03-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0052_rename_output_unit_outputevents_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutputEvents',
            new_name='Output',
        ),
    ]
