# Generated by Django 4.2 on 2024-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0053_rename_outputevents_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('event_json', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
