# Generated by Django 4.2 on 2024-03-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0054_outputevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Harvest',
            new_name='WorkstepHarvest',
        ),
        migrations.RenameModel(
            old_name='OrganicFertilization',
            new_name='WorkstepOrganicFertilization',
        ),
        migrations.RenameModel(
            old_name='Sowing',
            new_name='WorkstepSowing',
        ),
        migrations.RenameModel(
            old_name='Tillage',
            new_name='WorkstepTillage',
        ),
    ]
