# Generated by Django 4.2 on 2024-03-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0055_rename_harvest_workstepharvest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MineralFertilization',
            new_name='WorkstepMineralFertilization',
        ),
    ]
