# Generated by Django 4.2 on 2024-03-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0056_rename_mineralfertilization_workstepmineralfertilization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropresidueparameters',
            old_name='species',
            new_name='species_name',
        ),
    ]
