# Generated by Django 4.2 on 2024-03-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0057_rename_species_cropresidueparameters_species_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropresidueparameters',
            name='species_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.speciesparameters'),
        ),
    ]
