# Generated by Django 4.2 on 2024-03-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0058_cropresidueparameters_species_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropresidueparameters',
            old_name='species_id',
            new_name='species_parameters',
        ),
    ]
