# Generated by Django 4.2 on 2024-03-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0059_rename_species_id_cropresidueparameters_species_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivarparameters',
            name='species_parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.speciesparameters'),
        ),
    ]
