# Generated by Django 4.2 on 2024-03-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0060_cultivarparameters_species_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropParametersExist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(blank=True, max_length=100)),
                ('in_species', models.BooleanField(default=False)),
                ('in_cultivar', models.BooleanField(default=False)),
                ('in_residues', models.BooleanField(default=False)),
            ],
        ),
    ]
