# Generated by Django 4.2 on 2024-04-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0062_organfromdb_species_parameters_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organfromdb',
            old_name='species_parameters_id',
            new_name='species_parameters',
        ),
    ]
