# Generated by Django 4.2 on 2024-04-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0063_rename_species_parameters_id_organfromdb_species_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organfromdb',
            name='organ_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.organ'),
        ),
    ]
