# Generated by Django 4.2 on 2024-04-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0064_alter_organfromdb_organ_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organfromdb',
            old_name='organ_id',
            new_name='organ',
        ),
    ]
