# Generated by Django 4.2 on 2024-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0065_rename_organ_id_organfromdb_organ'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalElevationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('grid_file', models.FileField(upload_to='ascii_grids/')),
                ('crs', models.IntegerField(default=25832)),
            ],
        ),
    ]
