# Generated by Django 4.2 on 2024-05-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0066_digitalelevationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalElevationModel',
        ),
    ]
