# Generated by Django 4.2 on 2024-05-03 13:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0067_delete_digitalelevationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date', models.DateField()),
                ('tas', models.FloatField()),
                ('tasmin', models.FloatField()),
                ('tasmax', models.FloatField()),
                ('sfcWind', models.FloatField()),
                ('rsds', models.FloatField()),
                ('pr', models.FloatField()),
                ('hurs', models.FloatField()),
            ],
        ),
    ]
