# Generated by Django 4.2 on 2024-05-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0069_weatherdata_lat_weatherdata_lon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='sfcWind',
            new_name='sfcwind',
        ),
    ]
