# Generated by Django 4.2 on 2024-05-15 13:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0070_rename_sfcwind_weatherdata_sfcwind'),
    ]

    operations = [
        migrations.CreateModel(
            name='DWDGridToPointIndixes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('lat_idx', models.IntegerField()),
                ('lon_idx', models.IntegerField()),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
