# Generated by Django 4.2 on 2024-05-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0071_dwdgridtopointindixes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DWDGridToPointIndixes',
            new_name='DWDGridToPointIndices',
        ),
    ]
