# Generated by Django 4.2 on 2024-05-28 08:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0072_rename_dwdgridtopointindixes_dwdgridtopointindices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedHarvestDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_startion', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('crop_txt', models.CharField(max_length=100)),
                ('avg_sowing_day_of_year', models.IntegerField()),
                ('x_values_sowing', models.IntegerField()),
                ('avg_harvest_day_of_year', models.IntegerField()),
                ('x_values_harvest', models.IntegerField()),
                ('earliest_sowing_day_of_year', models.IntegerField()),
                ('latest_sowing_day_of_year', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('species_parameters_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.speciesparameters')),
            ],
        ),
        migrations.CreateModel(
            name='SeedHarvestWinterWheat',
            fields=[
                ('seedharvestdates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monica.seedharvestdates')),
            ],
            bases=('monica.seedharvestdates',),
        ),
    ]
