# Generated by Django 4.2 on 2024-05-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0073_seedharvestdates_seedharvestwinterwheat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedharvestdates',
            name='species_parameters_id',
        ),
        migrations.DeleteModel(
            name='SeedHarvestWinterWheat',
        ),
    ]
