# Generated by Django 4.2 on 2024-05-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0074_remove_seedharvestdates_species_parameters_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedharvestdates',
            name='cultivar_parameters_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.cultivarparameters'),
        ),
        migrations.CreateModel(
            name='SeedHarvestWinterWheat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_harvest_dates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monica.seedharvestdates')),
            ],
        ),
    ]
