# Generated by Django 4.2 on 2024-05-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0075_seedharvestdates_cultivar_parameters_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='nearest_climate_station_for_sowing_dates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
