# Generated by Django 4.2 on 2024-05-29 09:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0076_dwdgridtopointindices_nearest_climate_station_for_sowing_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='DWDGridAsPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('lat_idx', models.IntegerField()),
                ('lon_idx', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
