# Generated by Django 4.2 on 2024-05-29 14:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0078_dwdforecastgridaspolygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DWDForecastGridToPointIndices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('lat_idx', models.IntegerField()),
                ('lon_idx', models.IntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('nearest_climate_station_for_sowing_dates', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
