# Generated by Django 4.2 on 2024-05-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0079_dwdforecastgridtopointindices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dwdforecastgridtopointindices',
            name='is_valid',
        ),
    ]
