# Generated by Django 4.2 on 2024-05-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0080_remove_dwdforecastgridtopointindices_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='forecast_lat_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='forecast_lon_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
