# Generated by Django 4.2 on 2024-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0081_dwdgridtopointindices_forecast_lat_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedharvestdates',
            name='name_of_csv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
