# Generated by Django 4.2 on 2024-05-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0083_rename_x_values_harvest_seedharvestdates_no_of_harvest_datasets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seedharvestdates',
            old_name='avg_harvest_day_of_year',
            new_name='avg_harvest_doy',
        ),
        migrations.RenameField(
            model_name='seedharvestdates',
            old_name='avg_sowing_day_of_year',
            new_name='avg_sowing_doy',
        ),
        migrations.RenameField(
            model_name='seedharvestdates',
            old_name='earliest_sowing_day_of_year',
            new_name='earliest_sowing_doy',
        ),
        migrations.RenameField(
            model_name='seedharvestdates',
            old_name='latest_sowing_day_of_year',
            new_name='latest_sowing_doy',
        ),
    ]
