# Generated by Django 4.2 on 2024-05-31 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0084_rename_avg_harvest_day_of_year_seedharvestdates_avg_harvest_doy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedHarvestclimateStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='seedharvestwinterwheat',
            name='seed_harvest_dates',
        ),
        migrations.DeleteModel(
            name='SeedHarvestDates',
        ),
        migrations.DeleteModel(
            name='SeedHarvestWinterWheat',
        ),
    ]
