# Generated by Django 4.2 on 2024-05-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0085_seedharvestclimatestation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedHarvestDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_startion', models.IntegerField(blank=True, null=True)),
                ('name_of_csv', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('crop_txt', models.CharField(max_length=100)),
                ('avg_sowing_doy', models.IntegerField()),
                ('no_of_sowing_datasets', models.IntegerField()),
                ('avg_harvest_doy', models.IntegerField()),
                ('no_of_harvest_datasets', models.IntegerField()),
                ('earliest_sowing_doy', models.IntegerField()),
                ('latest_sowing_doy', models.IntegerField()),
                ('earliest_harvest_doy', models.IntegerField()),
                ('latest_harvest_doy', models.IntegerField()),
                ('cultivar_parameters_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.cultivarparameters')),
            ],
        ),
    ]
