# Generated by Django 4.2 on 2024-05-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0086_seedharvestdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedharvestdates',
            name='avg_harvest_doy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedharvestdates',
            name='avg_sowing_doy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedharvestdates',
            name='earliest_harvest_doy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedharvestdates',
            name='earliest_sowing_doy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedharvestdates',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedharvestdates',
            name='latest_harvest_doy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedharvestdates',
            name='latest_sowing_doy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedharvestdates',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedharvestdates',
            name='no_of_harvest_datasets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedharvestdates',
            name='no_of_sowing_datasets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
