# Generated by Django 4.2 on 2024-05-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0087_alter_seedharvestdates_avg_harvest_doy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seedharvestdates',
            old_name='climate_startion',
            new_name='climate_station',
        ),
    ]
