# Generated by Django 4.2 on 2024-05-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0088_rename_climate_startion_seedharvestdates_climate_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedharvestdates',
            name='climate_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monica.seedharvestclimatestation'),
            preserve_default=False,
        ),
    ]
