# Generated by Django 4.2 on 2024-06-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0089_alter_seedharvestdates_climate_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeedHarvestDates',
        ),
    ]
