# Generated by Django 4.2 on 2024-06-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0090_delete_seedharvestdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedHarvestDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_csv', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('crop_txt', models.CharField(max_length=100)),
                ('avg_sowing_doy', models.IntegerField(blank=True, null=True)),
                ('no_of_sowing_datasets', models.IntegerField(blank=True, null=True)),
                ('avg_harvest_doy', models.IntegerField(blank=True, null=True)),
                ('no_of_harvest_datasets', models.IntegerField(blank=True, null=True)),
                ('earliest_sowing_doy', models.IntegerField(blank=True, null=True)),
                ('latest_sowing_doy', models.IntegerField(blank=True, null=True)),
                ('earliest_harvest_doy', models.IntegerField(blank=True, null=True)),
                ('latest_harvest_doy', models.IntegerField(blank=True, null=True)),
                ('climate_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.seedharvestclimatestation')),
                ('cultivar_parameters_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.cultivarparameters')),
            ],
        ),
    ]
