# Generated by Django 4.2 on 2024-06-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0091_seedharvestdates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seedharvestdates',
            old_name='cultivar_parameters_id',
            new_name='cultivar_parameters',
        ),
    ]
