# Generated by Django 4.2 on 2024-06-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0092_rename_cultivar_parameters_id_seedharvestdates_cultivar_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivarparameters',
            name='is_winter_crop',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='speciesparameters',
            name='is_perennial_crop',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
