# Generated by Django 4.2 on 2024-07-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0093_cultivarparameters_is_winter_crop_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='workstepharvest',
        #     name='workstep_ptr',
        # ),
        migrations.RemoveField(
            model_name='workstepmineralfertilization',
            name='mineral_fertiliser',
        ),
        # migrations.RemoveField(
        #     model_name='workstepmineralfertilization',
        #     name='workstep_ptr',
        # ),
        migrations.RemoveField(
            model_name='worksteporganicfertilization',
            name='organic_fertiliser',
        ),
        # migrations.RemoveField(
        #     model_name='worksteporganicfertilization',
        #     name='workstep_ptr',
        # ),
        migrations.RemoveField(
            model_name='workstepsowing',
            name='cultivar',
        ),
        migrations.RemoveField(
            model_name='workstepsowing',
            name='residue_parameters',
        ),
        migrations.RemoveField(
            model_name='workstepsowing',
            name='species',
        ),
        # migrations.RemoveField(
        #     model_name='workstepsowing',
        #     name='workstep_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='worksteptillage',
        #     name='workstep_ptr',
        # ),
        # migrations.DeleteModel(
        #     name='WorkStep',
        # ),
        # migrations.DeleteModel(
        #     name='WorkstepHarvest',
        # ),
        migrations.DeleteModel(
            name='WorkstepMineralFertilization',
        ),
        migrations.DeleteModel(
            name='WorkstepOrganicFertilization',
        ),
        migrations.DeleteModel(
            name='WorkstepSowing',
        ),
        migrations.DeleteModel(
            name='WorkstepTillage',
        ),
    ]
