# Generated by Django 4.2 on 2024-07-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0094_remove_workstepharvest_workstep_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstepharvest',
            name='workstep_ptr',
        ),
        migrations.DeleteModel(
            name='WorkStep',
        ),
        migrations.DeleteModel(
            name='WorkstepHarvest',
        ),
    ]
