# Generated by Django 4.2 on 2024-07-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0095_remove_workstepharvest_workstep_ptr_delete_workstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkstepHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkstepTillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('tillage_depth', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkstepSowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('plant_density', models.IntegerField()),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.cultivarparameters')),
                ('residue_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.cropresidueparameters')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.speciesparameters')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkstepOrganicFertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('incorporation', models.BooleanField()),
                ('organic_fertiliser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.organicfertiliser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkstepMineralFertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('mineral_fertiliser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.mineralfertiliser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
