# Generated by Django 4.2 on 2024-07-15 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monica', '0097_usercropparameters_default_usercropparameters_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersoiltransportparameters',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersoiltransportparameters',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersoiltransportparameters',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
