# Generated by Django 4.2 on 2024-07-15 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monica', '0098_usersoiltransportparameters_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkstepIrrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSimaulationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('debug', models.BooleanField(default=True)),
                ('use_secondary_yields', models.BooleanField(default=False)),
                ('nitrogen_response_on', models.BooleanField(default=False)),
                ('water_deficit_response_on', models.BooleanField(default=False)),
                ('emergence_moisture_control_on', models.BooleanField(default=False)),
                ('emergence_flooding_control_on', models.BooleanField(default=False)),
                ('use_n_min_mineral_fertilising_method', models.BooleanField(default=False)),
                ('n_min_user_params_min', models.FloatField()),
                ('n_min_user_params_max', models.FloatField()),
                ('n_min_user_params_delay_in_days', models.IntegerField()),
                ('julian_day_automatic_fertilising', models.IntegerField()),
                ('use_automatic_irrigation', models.BooleanField(default=False)),
                ('auto_irrigation_params_nitrate_concentration', models.FloatField()),
                ('auto_irrigation_params_sulfate_concentration', models.FloatField()),
                ('auto_irrigation_params_amount', models.FloatField()),
                ('auto_irrigation_params_threshold', models.FloatField()),
                ('n_min_fertiliser_partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.mineralfertiliser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
