# Generated by Django 4.2 on 2024-07-15 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monica', '0099_workstepirrigation_usersimaulationsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSimaulationSettings',
            new_name='UserSimulationSettings',
        ),
    ]
