# Generated by Django 4.2 on 2024-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0100_rename_usersimaulationsettings_usersimulationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersimulationsettings',
            name='auto_irrigation_params_amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usersimulationsettings',
            name='auto_irrigation_params_nitrate_concentration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usersimulationsettings',
            name='auto_irrigation_params_sulfate_concentration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usersimulationsettings',
            name='auto_irrigation_params_threshold',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usersimulationsettings',
            name='julian_day_automatic_fertilising',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usersimulationsettings',
            name='n_min_user_params_delay_in_days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usersimulationsettings',
            name='n_min_user_params_max',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usersimulationsettings',
            name='n_min_user_params_min',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
