# Generated by Django 4.2 on 2024-07-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0101_alter_usersimulationsettings_auto_irrigation_params_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersimulationsettings',
            name='n_min_fertiliser_partition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.mineralfertiliser'),
        ),
    ]
