# Generated by Django 4.2 on 2024-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0103_cropresidueparameters_user_cultivarparameters_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesparameters',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
