# Generated by Django 4.2 on 2024-07-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0104_speciesparameters_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropresidueparameters',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='mineralfertiliser',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='organfromdb',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='organicfertiliser',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='simulationenvironment',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='soiltemperaturemoduleparameters',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usercropparameters',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userenvironmentparameters',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usersimulationsettings',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usersoilmoistureparameters',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usersoilorganicparameters',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usersoiltransportparameters',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
