# Generated by Django 4.2 on 2024-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0105_cropresidueparameters_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiltemperaturemoduleparameters',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
