# Generated by Django 4.2 on 2024-07-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0106_soiltemperaturemoduleparameters_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropresidueparameters',
            old_name='file_name',
            new_name='name',
        ),
    ]
