# Generated by Django 4.2 on 2024-07-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0107_rename_file_name_cropresidueparameters_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='cultivar_name',
            new_name='name',
        ),
    ]
