# Generated by Django 4.2 on 2024-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0108_rename_cultivar_name_cultivarparameters_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwdgridaspolygon',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
