# Generated by Django 4.2 on 2024-09-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0109_dwdgridaspolygon_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='landcover_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='landcover_code_21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='landcover_code_23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='landcover_code_31',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='soilprofile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='soilprofile_id_21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='soilprofile_id_23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwdgridtopointindices',
            name='soilprofile_id_31',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
