# Generated by Django 4.2 on 2024-10-23 11:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monica', '0110_dwdgridtopointindices_landcover_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkstepMineralFertilization',
            new_name='WorkstepMineralFertilisation',
        ),
        migrations.RenameModel(
            old_name='WorkstepOrganicFertilization',
            new_name='WorkstepOrganicFertilisation',
        ),
    ]
