# Generated by Django 4.2 on 2024-10-28 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0019_remove_mapsoilclc_clc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monica', '0111_rename_workstepmineralfertilization_workstepmineralfertilisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstepirrigation',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='SiteParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('slope', models.FloatField()),
                ('n_deposition', models.FloatField()),
                ('soil_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buek.soilprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CentralParameterProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usersimulationsettings')),
                ('site_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.siteparameters')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_crop_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usercropparameters')),
                ('user_environment_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.userenvironmentparameters')),
                ('user_soil_moisture_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usersoilmoistureparameters')),
                ('user_soil_organic_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usersoilorganicparameters')),
                ('user_soil_transport_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usersoiltransportparameters')),
            ],
        ),
    ]
