# Generated by Django 4.2 on 2024-10-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0019_remove_mapsoilclc_clc'),
        ('monica', '0112_alter_workstepirrigation_amount_siteparameters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonicaSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('slope', models.FloatField()),
                ('n_deposition', models.FloatField()),
                ('soil_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buek.soilprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MonicaEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debug_mode', models.BooleanField(default=False)),
                ('crop_rotation', models.JSONField(blank=True, null=True)),
                ('crop_rotations', models.JSONField(blank=True, default=None, null=True)),
                ('events', models.JSONField(blank=True, null=True)),
                ('params', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.centralparameterprovider')),
            ],
        ),
    ]
