# Generated by Django 4.2 on 2024-11-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0113_monicasimulation_monicaenvironment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineralfertiliser',
            name='type',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='default',
        ),
    ]
