# Generated by Django 4.2 on 2024-11-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0114_remove_mineralfertiliser_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationenvironment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='usersoilmoistureparameters',
            name='default',
        ),
        migrations.RemoveField(
            model_name='usersoiltransportparameters',
            name='default',
        ),
    ]
