# Generated by Django 4.2 on 2024-11-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0115_remove_simulationenvironment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesparameters',
            old_name='species_name',
            new_name='name',
        ),
    ]
