# Generated by Django 4.2 on 2024-11-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0116_rename_species_name_speciesparameters_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='assimilate_partitioning_coeff',
            new_name='assimilate_partitioning_coeff_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='base_daylength',
            new_name='base_daylength_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='daylength_requirement',
            new_name='daylength_requirement_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='drought_stress_threshold',
            new_name='drought_stress_threshold_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='optimum_temperature',
            new_name='optimum_temperature_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='organ_ids_for_cutting',
            new_name='organ_ids_for_cutting_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='organ_ids_for_primary_yield',
            new_name='organ_ids_for_primary_yield_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='organ_ids_for_secondary_yield',
            new_name='organ_ids_for_secondary_yield_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='organ_senescence_rate',
            new_name='organ_senescence_rate_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='specific_leaf_area',
            new_name='specific_leaf_area_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='stage_kc_factor',
            new_name='stage_kc_factor_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='stage_temperature_sum',
            new_name='stage_temperature_sum_a',
        ),
        migrations.RenameField(
            model_name='cultivarparameters',
            old_name='vernalisation_requirement',
            new_name='vernalisation_requirement_a',
        ),
    ]
