# Generated by Django 4.2 on 2024-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0117_rename_assimilate_partitioning_coeff_cultivarparameters_assimilate_partitioning_coeff_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivarparameters',
            name='assimilate_partitioning_coeff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='base_daylength',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='daylength_requirement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='drought_stress_threshold',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='optimum_temperature',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='organ_ids_for_cutting',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='organ_ids_for_primary_yield',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='organ_ids_for_secondary_yield',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='organ_senescence_rate',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='specific_leaf_area',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='stage_kc_factor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='stage_temperature_sum',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivarparameters',
            name='vernalisation_requirement',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
