# Generated by Django 4.2 on 2024-11-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0118_cultivarparameters_assimilate_partitioning_coeff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='assimilate_partitioning_coeff',
        ),
    ]
