# Generated by Django 4.2 on 2024-11-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0119_remove_cultivarparameters_assimilate_partitioning_coeff'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivarparameters',
            name='assimilate_partitioning_coeff',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
