# Generated by Django 4.2 on 2024-11-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0120_cultivarparameters_assimilate_partitioning_coeff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='daylength_requirement',
        ),
    ]
