# Generated by Django 4.2 on 2024-11-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0121_remove_cultivarparameters_daylength_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivarparameters',
            name='daylength_requirement',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
