# Generated by Django 4.2 on 2024-11-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0122_cultivarparameters_daylength_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='assimilate_partitioning_coeff_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='base_daylength_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='daylength_requirement_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='drought_stress_threshold_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='optimum_temperature_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='organ_ids_for_cutting_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='organ_ids_for_primary_yield_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='organ_ids_for_secondary_yield_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='organ_senescence_rate_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='specific_leaf_area_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='stage_kc_factor_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='stage_temperature_sum_a',
        ),
        migrations.RemoveField(
            model_name='cultivarparameters',
            name='vernalisation_requirement_a',
        ),
    ]
