# Generated by Django 4.2 on 2024-11-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0123_remove_cultivarparameters_assimilate_partitioning_coeff_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenvironmentparameters',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
