# Generated by Django 4.2 on 2024-11-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0124_alter_userenvironmentparameters_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersoilorganicparameters',
            old_name='code_hourly_wfps_denit',
            new_name='code_hourly_wfps_denit_x',
        ),
        migrations.RenameField(
            model_name='usersoilorganicparameters',
            old_name='code_hourly_wfps_nit',
            new_name='code_hourly_wfps_nit_x',
        ),
        migrations.RenameField(
            model_name='usersoilorganicparameters',
            old_name='code_pdenit',
            new_name='code_pdenit_x',
        ),
        migrations.RenameField(
            model_name='usersoilorganicparameters',
            old_name='code_ratiodenit',
            new_name='code_ratiodenit_x',
        ),
        migrations.RenameField(
            model_name='usersoilorganicparameters',
            old_name='code_rationit',
            new_name='code_rationit_x',
        ),
        migrations.RenameField(
            model_name='usersoilorganicparameters',
            old_name='code_tnit',
            new_name='code_tnit_x',
        ),
        migrations.RenameField(
            model_name='usersoilorganicparameters',
            old_name='code_vnit',
            new_name='code_vnit_x',
        ),
        migrations.AlterField(
            model_name='userenvironmentparameters',
            name='atmospheric_co2s',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userenvironmentparameters',
            name='yearly_co2_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
