# Generated by Django 4.2 on 2024-11-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0125_rename_code_hourly_wfps_denit_usersoilorganicparameters_code_hourly_wfps_denit_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersoilorganicparameters',
            name='code_hourly_wfps_denit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersoilorganicparameters',
            name='code_hourly_wfps_nit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersoilorganicparameters',
            name='code_pdenit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersoilorganicparameters',
            name='code_rationit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersoilorganicparameters',
            name='code_tnit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersoilorganicparameters',
            name='code_vnit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
