# Generated by Django 4.2 on 2024-11-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0126_usersoilorganicparameters_code_hourly_wfps_denit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='code_hourly_wfps_denit_x',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='code_hourly_wfps_nit_x',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='code_pdenit_x',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='code_ratiodenit_x',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='code_rationit_x',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='code_tnit_x',
        ),
        migrations.RemoveField(
            model_name='usersoilorganicparameters',
            name='code_vnit_x',
        ),
    ]
