# Generated by Django 4.2 on 2024-11-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0127_remove_usersoilorganicparameters_code_hourly_wfps_denit_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersoilorganicparameters',
            name='code_ratiodenit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
