# Generated by Django 4.2 on 2024-12-09 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monica', '0128_usersoilorganicparameters_code_ratiodenit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('simulation_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usersimulationsettings')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_crop_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usercropparameters')),
                ('user_environment_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.userenvironmentparameters')),
                ('user_soil_moisture_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usersoilmoistureparameters')),
                ('user_soil_organic_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usersoilorganicparameters')),
                ('user_soil_temperature_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.soiltemperaturemoduleparameters')),
                ('user_soil_transport_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usersoiltransportparameters')),
            ],
        ),
        migrations.CreateModel(
            name='MonicaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('monica_model_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.modelsetup')),
            ],
        ),
    ]
