# Generated by Django 4.2 on 2024-12-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0129_modelsetup_monicaproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelsetup',
            old_name='name',
            new_name='setup_name',
        ),
    ]
