# Generated by Django 4.2 on 2024-12-13 09:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0019_remove_mapsoilclc_clc'),
        ('monica', '0130_rename_name_modelsetup_setup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_no', models.IntegerField()),
                ('thickness', models.FloatField()),
                ('sand', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('clay', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('silt', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('sceleton', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lambda_s', models.FloatField()),
                ('field_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pore_volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('permanent_wilting_point', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ammonium', models.FloatField()),
                ('nitrate', models.FloatField()),
                ('c_n', models.FloatField()),
                ('raw_density', models.FloatField(null=True)),
                ('bulk_density', models.FloatField(null=True)),
                ('organic_carbon', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('organic_matter', models.FloatField(null=True)),
                ('soil_moisture', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ka5_texture_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buek.ka5textureclass')),
            ],
        ),
    ]
