# Generated by Django 4.2 on 2024-12-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('monica', '0131_soillayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonicaCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('slope', models.FloatField()),
                ('n_deposition', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_start_date', models.DateField(blank=True, null=True)),
                ('soil_profile_object_id', models.PositiveIntegerField()),
                ('monica_model_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.modelsetup')),
            ],
        ),
        migrations.CreateModel(
            name='UserSoilProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='monicaproject',
            name='monica_model_setup',
        ),
        migrations.AddField(
            model_name='monicaproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='MonicaSimulation',
        ),
        migrations.AddField(
            model_name='monicacalculation',
            name='monica_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.monicaproject'),
        ),
        migrations.AddField(
            model_name='monicacalculation',
            name='soil_profile_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='soillayer',
            name='user_soil_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monica.usersoilprofile'),
            preserve_default=False,
        ),
    ]
