# Generated by Django 4.2 on 2024-12-13 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monica', '0132_monicacalculation_usersoilprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsetup',
            name='user',
        ),
        migrations.AddField(
            model_name='monicaproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
