# Generated by Django 4.2 on 2024-12-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0134_modelsetup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='monicaproject',
            name='start_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
