# Generated by Django 4.2 on 2024-12-13 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monica', '0135_monicaproject_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monicacalculation',
            name='monica_model_setup',
        ),
        migrations.RemoveField(
            model_name='monicacalculation',
            name='soil_profile_content_type',
        ),
        migrations.RemoveField(
            model_name='monicacalculation',
            name='soil_profile_object_id',
        ),
        migrations.AddField(
            model_name='monicaproject',
            name='monica_model_setup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monica.modelsetup'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MonicaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('slope', models.FloatField()),
                ('n_deposition', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('soil_profile_object_id', models.PositiveIntegerField()),
                ('soil_profile_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
