# Generated by Django 4.2 on 2024-12-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0136_remove_monicacalculation_monica_model_setup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monicaproject',
            name='monica_model_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.modelsetup'),
        ),
    ]
