# Generated by Django 4.2 on 2024-12-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0137_alter_monicaproject_monica_model_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsetup',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
