# Generated by Django 4.2 on 2024-12-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0138_modelsetup_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelsetup',
            old_name='setup_name',
            new_name='name',
        ),
    ]
