# Generated by Django 4.2 on 2024-12-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0140_monicacalculation_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monicacalculation',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='monicacalculation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='monicacalculation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='monicacalculation',
            name='n_deposition',
        ),
        migrations.RemoveField(
            model_name='monicacalculation',
            name='slope',
        ),
    ]
