# Generated by Django 4.2 on 2024-12-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0141_remove_monicacalculation_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monicacalculation',
            name='monica_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monica.monicasite'),
            preserve_default=False,
        ),
    ]
