# Generated by Django 4.2 on 2024-12-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('monica', '0142_monicacalculation_monica_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monicasite',
            name='soil_profile_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='soil_profile_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
