# Generated by Django 4.2 on 2024-12-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0143_alter_monicasite_soil_profile_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monicaproject',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='monicaproject',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
