# Generated by Django 4.2 on 2024-12-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0144_rename_created_at_monicaproject_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monicaproject',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monicaproject',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
