# Generated by Django 4.2 on 2025-01-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0145_alter_monicaproject_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monicaproject',
            name='monica_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.monicasite'),
        ),
    ]
