# Generated by Django 4.2 on 2025-01-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0147_croprotation_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstepharvest',
            name='rotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workstep_harvest', to='monica.rotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workstepirrigation',
            name='rotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workstep_irrigation', to='monica.rotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workstepmineralfertilisation',
            name='rotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workstep_mineral_fertilisation', to='monica.rotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksteporganicfertilisation',
            name='rotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workstep_organic_fertilisation', to='monica.rotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workstepsowing',
            name='rotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workstep_sowing', to='monica.rotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksteptillage',
            name='rotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workstep_tillage', to='monica.rotation'),
            preserve_default=False,
        ),
    ]
