# Generated by Django 4.2 on 2025-01-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0149_siteparameters_name_siteparameters_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteparameters',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
