# Generated by Django 4.2 on 2025-01-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0150_alter_siteparameters_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monicaenvironment',
            name='params',
        ),
        migrations.RemoveField(
            model_name='simulationenvironment',
            name='general_soil_moisture_parameters',
        ),
        migrations.RemoveField(
            model_name='simulationenvironment',
            name='general_soil_organic_parameters',
        ),
        migrations.RemoveField(
            model_name='simulationenvironment',
            name='general_soil_transport',
        ),
        migrations.RemoveField(
            model_name='simulationenvironment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='simulationenvironment',
            name='user_environment_parameters',
        ),
        migrations.DeleteModel(
            name='CentralParameterProvider',
        ),
        migrations.DeleteModel(
            name='MonicaEnvironment',
        ),
        migrations.DeleteModel(
            name='SimulationEnvironment',
        ),
    ]
