# Generated by Django 4.2 on 2025-01-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0151_remove_monicaenvironment_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monicacalculation',
            name='monica_site',
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='n_deposition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='slope',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
