# Generated by Django 4.2 on 2025-01-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0152_remove_monicacalculation_monica_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsetup',
            name='crop_rotation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
