# Generated by Django 4.2 on 2025-01-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0153_modelsetup_crop_rotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteParameters',
        ),
    ]
