# Generated by Django 4.2 on 2025-01-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0154_delete_siteparameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelsetup',
            old_name='simulation_parameters',
            new_name='user_simulation_settings',
        ),
    ]
