# Generated by Django 4.2 on 2025-04-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0156_outputsettings_delete_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercropparameters',
            name='default',
        ),
        migrations.RemoveField(
            model_name='userenvironmentparameters',
            name='default',
        ),
        migrations.RemoveField(
            model_name='usersimulationsettings',
            name='default',
        ),
    ]
