# Generated by Django 4.2 on 2025-05-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0157_remove_usercropparameters_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBCHStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=4)),
                ('macro_stage', models.IntegerField()),
                ('micro_stage', models.IntegerField()),
                ('default_en_description', models.CharField(max_length=255)),
                ('default_de_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CropStageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_en_description', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_de_description', models.CharField(blank=True, max_length=255, null=True)),
                ('bbch_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.bbchstage')),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_descriptions', to='monica.cultivarparameters')),
            ],
        ),
    ]
