# Generated by Django 4.2 on 2025-07-07 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monica', '0158_bbchstage_cropstagedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkstepNDemandFertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('days', models.IntegerField()),
                ('after', models.CharField(choices=[('sowing', 'Sowing'), ('anthesis', 'Anthesis'), ('maturity', 'Maturity')], default='sowing', help_text='The event after which the fertilisation is scheduled.')),
                ('depth', models.FloatField(help_text='The depth at which the fertiliser is applied, in meters.')),
                ('n_demand', models.FloatField(help_text='The amount of nitrogen demand for fertilisation, in kg N/ha.')),
                ('mineral_fertiliser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.mineralfertiliser')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstep_n_emand_fertilization', to='monica.rotation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkstepAutomaticHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('min_percentage_asw', models.FloatField()),
                ('max_percentage_asw', models.FloatField()),
                ('max_3d_precip_sum', models.IntegerField(default=2)),
                ('max_curr_day_precip', models.FloatField(default=0.1, help_text='Maximum precipitation on the current day in mm')),
                ('harvest_time', models.CharField(choices=[('maturity', 'Maturity'), ('anthesis', 'Anthesis')], default='maturity', help_text='The event after which the harvest is scheduled.')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstep_automatic_harvest', to='monica.rotation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
