# Generated by Django 4.2 on 2025-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0159_workstepndemandfertilization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivarparameters',
            name='is_winter_crop',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
