# Generated by Django 4.2 on 2026-01-26 10:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0027_corinelandcover2018_label_level_1_de_and_more'),
        ('monica', '0160_alter_cultivarparameters_is_winter_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilHorizon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_no', models.IntegerField(default=1)),
                ('thickness', models.FloatField(default=0.3)),
                ('sand', models.FloatField(default=33, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('clay', models.FloatField(default=33, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('silt', models.FloatField(default=34, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ph', models.FloatField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('sceleton', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lambda_s', models.FloatField(default=0.1)),
                ('field_capacity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pore_volume', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('permanent_wilting_point', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ammonium', models.FloatField(blank=True, null=True)),
                ('nitrate', models.FloatField(blank=True, null=True)),
                ('c_n', models.FloatField(default=11)),
                ('raw_density', models.FloatField(blank=True, null=True)),
                ('bulk_density', models.FloatField(blank=True, null=True)),
                ('organic_carbon', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('organic_matter', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ka5_texture_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buek.ka5textureclass')),
                ('user_soil_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monica.usersoilprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='SoilLayer',
        ),
    ]
