# Generated by Django 4.2 on 2026-01-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0161_soilhorizon_delete_soillayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilhorizon',
            name='ka5_texture_class',
        ),
    ]
