# Generated by Django 4.2 on 2026-02-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0162_remove_soilhorizon_ka5_texture_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilhorizon',
            name='silt',
        ),
        migrations.AlterField(
            model_name='soilhorizon',
            name='user_soil_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_horizons', to='monica.usersoilprofile'),
        ),
    ]
