# Generated by Django 4.2 on 2026-02-18 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0163_remove_soilhorizon_silt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monicasite',
            name='latitude',
            field=models.FloatField(blank=True, default=52.0, null=True),
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='longitude',
            field=models.FloatField(blank=True, default=10.0, null=True),
        ),
        migrations.AlterField(
            model_name='soilhorizon',
            name='sceleton',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
