# Generated by Django 4.2 on 2026-02-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0164_alter_monicasite_latitude_alter_monicasite_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monicasite',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
