# Generated by Django 4.2 on 2026-02-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0165_monicasite_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monicasite',
            old_name='name',
            new_name='site_name',
        ),
    ]
