# Generated by Django 4.2 on 2026-02-24 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0166_rename_name_monicasite_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilhorizon',
            name='silt',
            field=models.FloatField(default=34, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='soilhorizon',
            name='field_capacity',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='soilhorizon',
            name='lambda_s',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='soilhorizon',
            name='permanent_wilting_point',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='soilhorizon',
            name='pore_volume',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='soilhorizon',
            name='soil_moisture',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
