# Generated by Django 4.2 on 2026-02-24 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0167_soilhorizon_silt_alter_soilhorizon_field_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilhorizon',
            name='silt',
            field=models.FloatField(blank=True, default=34, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
