# Generated by Django 4.2 on 2026-03-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0168_alter_soilhorizon_silt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropresidueparameters',
            name='species_parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_residue_parameters', to='monica.speciesparameters'),
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='altitude',
            field=models.FloatField(blank=True, default=196, null=True),
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='n_deposition',
            field=models.FloatField(blank=True, default=10.5, null=True),
        ),
        migrations.AlterField(
            model_name='monicasite',
            name='slope',
            field=models.FloatField(blank=True, default=7.6, null=True),
        ),
        migrations.CreateModel(
            name='GermanyModelParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cultivar_name', models.CharField(choices=[(1, 'alfalfa'), (2, 'alfalfa clover grass ley mix'), (11, 'silage maize'), (16, 'moderately early potato'), (17, 'winter rape'), (18, 'winter rye'), (22, 'sugar beet'), (26, 'winter wheat'), (27, 'winter barley'), (32, 'grain maize'), (37, 'silage winter rye'), (57, 'spring wheat')], default=1, max_length=255)),
                ('simj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.usersimulationsettings')),
                ('user_crop_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.usercropparameters')),
                ('user_environment_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.userenvironmentparameters')),
                ('user_soil_moisture_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.usersoilmoistureparameters')),
                ('user_soil_organic_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.usersoilorganicparameters')),
                ('user_soil_temperature_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.soiltemperaturemoduleparameters')),
                ('user_soil_transport_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.usersoiltransportparameters')),
            ],
        ),
    ]
