# Generated by Django 4.2 on 2026-03-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0169_alter_cropresidueparameters_species_parameters_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='germanymodelparameters',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='only_one_default_germany_model_parameters'),
        ),
    ]
