# Generated by Django 4.2 on 2026-03-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0170_germanymodelparameters_only_one_default_germany_model_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='germanymodelparameters',
            old_name='cultivar_name',
            new_name='cultivar_name_for_sowing_dates',
        ),
        migrations.AddField(
            model_name='germanymodelparameters',
            name='cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monica.cultivarparameters'),
        ),
    ]
