# Generated by Django 4.2 on 2026-03-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0171_rename_cultivar_name_germanymodelparameters_cultivar_name_for_sowing_dates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='germanymodelparameters',
            old_name='user_soil_temperature_parameters',
            new_name='soil_temperature_module_parameters',
        ),
    ]
