# Generated by Django 4.2 on 2026-03-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0172_rename_user_soil_temperature_parameters_germanymodelparameters_soil_temperature_module_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germanymodelparameters',
            name='cultivar_name_for_sowing_dates',
            field=models.IntegerField(choices=[(1, 'alfalfa'), (2, 'alfalfa clover grass ley mix'), (11, 'silage maize'), (16, 'moderately early potato'), (17, 'winter rape'), (18, 'winter rye'), (22, 'sugar beet'), (26, 'winter wheat'), (27, 'winter barley'), (32, 'grain maize'), (37, 'silage winter rye'), (57, 'spring wheat')], default=1, max_length=255),
        ),
    ]
