# Generated by Django 5.2.13 on 2026-04-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0174_alter_germanymodelparameters_cultivar_name_for_sowing_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersoilmoistureparameters',
            name='correction_rain',
            field=models.IntegerField(),
        ),
    ]
