# Generated by Django 5.2.13 on 2026-04-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0175_alter_usersoilmoistureparameters_correction_rain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersoilmoistureparameters',
            name='evaporation_zeta',
            field=models.IntegerField(),
        ),
    ]
