# Generated by Django 5.2.13 on 2026-04-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0176_alter_usersoilmoistureparameters_evaporation_zeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersoilmoistureparameters',
            name='groundwater_discharge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersoilmoistureparameters',
            name='max_percolation_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersoilmoistureparameters',
            name='maximum_evaporation_impact_depth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersoilmoistureparameters',
            name='moisture_init_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersoilmoistureparameters',
            name='saturated_hydraulic_conductivity',
            field=models.IntegerField(),
        ),
    ]
