# Generated by Django 5.2.13 on 2026-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0177_alter_usersoilmoistureparameters_groundwater_discharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersoilmoistureparameters',
            name='temperature_limit_for_liquid_water',
            field=models.IntegerField(),
        ),
    ]
