# Generated by Django 5.2.13 on 2026-04-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0178_alter_usersoilmoistureparameters_temperature_limit_for_liquid_water'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBCHMacrostage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_no', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
