# Generated by Django 5.2.13 on 2026-04-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0179_bbchmacrostage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbchmacrostage',
            old_name='name',
            new_name='name_de',
        ),
    ]
