# Generated by Django 4.2 on 2026-05-08 14:28

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monica', '0180_rename_name_bbchmacrostage_name_de'),
    ]

    operations = [
        migrations.CreateModel(
            name='NUTS0000_N0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuts_id', models.CharField(max_length=16)),
                ('gf', models.IntegerField()),
                ('nuts_level', models.IntegerField()),
                ('nuts_code', models.CharField(max_length=5)),
                ('nuts_name', models.CharField(max_length=100)),
                ('name_latin', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='NUTS5000_N1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objid', models.CharField(max_length=16)),
                ('beginn', models.DateField()),
                ('gf', models.IntegerField()),
                ('nuts_level', models.IntegerField()),
                ('nuts_code', models.CharField(max_length=5)),
                ('nuts_name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='NUTS5000_N2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objid', models.CharField(max_length=16)),
                ('beginn', models.DateField()),
                ('gf', models.IntegerField()),
                ('nuts_level', models.IntegerField()),
                ('nuts_code', models.CharField(max_length=5)),
                ('nuts_name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('nuts_code_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.nuts5000_n1')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geo_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('soil_profile_polygon_ids', models.JSONField(blank=True, null=True)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('centroid_lon', models.FloatField(blank=True, null=True)),
                ('weather_grid_points', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SwnProject',
            fields=[
                ('monicaproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monica.monicaproject')),
                ('user_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swn_projects', to='swn.userfield')),
            ],
            bases=('monica.monicaproject',),
        ),
        migrations.CreateModel(
            name='NUTS5000_N3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objid', models.CharField(max_length=16)),
                ('beginn', models.DateField()),
                ('gf', models.IntegerField()),
                ('nuts_level', models.IntegerField()),
                ('nuts_code', models.CharField(max_length=5)),
                ('nuts_name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('nuts_code_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.nuts5000_n2')),
            ],
        ),
    ]
