# Generated by Django 4.1.2 on 2023-02-09 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectregion',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='geom',
        ),
        migrations.AlterField(
            model_name='userproject',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.userfield'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
