# Generated by Django 4.2 on 2025-03-19 08:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfield',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
