# Generated by Django 4.1.2 on 2023-02-09 10:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0002_remove_projectregion_geom_remove_userfield_geom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectregion',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
