# Generated by Django 4.1.2 on 2023-03-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0002_remove_crop_winter_summer_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='winter_summer_crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swn.wintersummercrop'),
        ),
    ]
