# Generated by Django 4.1.2 on 2023-01-26 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0002_userfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfield',
            name='user',
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('irrigation_input', models.JSONField()),
                ('irrigation_output', models.JSONField()),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='swn.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swn.userfield')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
