# Generated by Django 4.1.2 on 2023-01-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0002_userfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIrrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swn.userfield')),
                ('irrigation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swn.userirrigation')),
            ],
        ),
    ]
