# Generated by Django 4.1.2 on 2023-03-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0003_crop_winter_summer_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='winter_summer_crop',
        ),
    ]
