# Generated by Django 4.1.2 on 2023-02-09 10:11

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0003_projectregion_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfield',
            name='geom',
            field=djgeojson.fields.PolygonField(null=True),
        ),
    ]
