# Generated by Django 4.1.2 on 2023-01-23 14:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0003_userirrigation_userproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
