# Generated by Django 4.1.2 on 2023-04-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0005_rename_soil_profile_all_soilprofileall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilprofileall',
            name='KA5_texture_class',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='layer_description',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='range_percentage_of_area',
            field=models.CharField(max_length=56),
        ),
    ]
