# Generated by Django 4.1.2 on 2023-02-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0005_remove_userproject_user_userfield_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfield',
            name='geom',
        ),
    ]
