# Generated by Django 4.1.2 on 2023-04-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0006_alter_soilprofileall_ka5_texture_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilprofileall',
            name='polygon_id',
            field=models.IntegerField(),
        ),
    ]
