# Generated by Django 4.1.2 on 2023-02-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0006_remove_userfield_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfield',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='irrigation_input',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='irrigation_output',
            field=models.JSONField(null=True),
        ),
    ]
