# Generated by Django 4.1.2 on 2023-04-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0007_alter_soilprofileall_polygon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilprofileall',
            name='polygon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swn.buekdata'),
        ),
    ]
