# Generated by Django 4.1.2 on 2023-02-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0007_alter_userfield_comment_alter_userproject_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='irrigation_input',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='irrigation_output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
