# Generated by Django 4.1.2 on 2023-02-09 16:02

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0008_alter_userproject_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfield',
            name='geom',
            field=djgeojson.fields.PolygonField(null=True),
        ),
    ]
