# Generated by Django 4.1.2 on 2023-02-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0009_userfield_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfield',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
