# Generated by Django 4.1.2 on 2023-03-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0010_alter_userfield_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfield',
            old_name='geom',
            new_name='geom_json',
        ),
    ]
