# Generated by Django 4.1.2 on 2023-04-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0010_rename_ka5_texture_class_soilprofileall_ka5_texture_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilprofileall',
            old_name='is_impenetrabl',
            new_name='is_impenetrable',
        ),
    ]
