# Generated by Django 4.1.2 on 2023-04-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0011_rename_is_impenetrabl_soilprofileall_is_impenetrable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilprofileall',
            name='avg_range_percentage_of_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='bulk_density',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='c_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='clay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='field_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='horizon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='initial_soil_moisture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='is_impenetrable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='is_in_groundwater',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='ka5_texture_class',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='layer_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='layer_description',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='permanent_wilting_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='ph',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='profile_id_in_polygon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='range_percentage_of_area',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='raw_density',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='sand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='sceleton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='silt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='soil_ammonium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='soil_nitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='soil_organic_carbon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='soil_organic_matter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilprofileall',
            name='soil_water_conductivity_coefficient',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
