# Generated by Django 4.1.2 on 2023-03-09 16:25

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0011_rename_geom_userfield_geom_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfield',
            name='geom',
            field=djgeojson.fields.GeometryField(null=True),
        ),
    ]
