# Generated by Django 4.1.2 on 2023-03-10 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0012_userfield_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='calculation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
