# Generated by Django 4.1.2 on 2023-03-16 13:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0013_userproject_calculation_userproject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfield',
            name='geom2',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
