# Generated by Django 4.1.2 on 2023-04-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0013_rename_tkle_nr_buekdata_polygon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buekdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='buekdata',
            name='polygon_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
