# Generated by Django 4.1.2 on 2023-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0014_userfield_geom2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfield',
            name='geom',
        ),
    ]
