# Generated by Django 4.1.2 on 2023-03-20 15:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0015_remove_userfield_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfield',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
