# Generated by Django 4.1.2 on 2023-04-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0015_remove_soilprofileall_polygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuekData',
        ),
        migrations.DeleteModel(
            name='SoilProfileAll',
        ),
    ]
