# Generated by Django 4.1.2 on 2023-03-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0016_userfield_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfield',
            name='geom2',
        ),
    ]
