# Generated by Django 4.2 on 2023-04-19 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0016_delete_buekdata_delete_soilprofileall'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('file', models.FileField(blank=True, upload_to='geodata')),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
    ]
