# Generated by Django 4.2 on 2023-06-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0018_rename_date_userproject_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproject',
            old_name='user_field',
            new_name='field',
        ),
    ]
