# Generated by Django 4.2 on 2023-06-22 11:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0020_rename_field_userproject_user_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='NUTS5000_N1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objid', models.CharField(max_length=16)),
                ('beginn', models.DateField()),
                ('gf', models.IntegerField()),
                ('nuts_level', models.IntegerField()),
                ('nuts_code', models.CharField(max_length=5)),
                ('nuts_name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=25832)),
            ],
        ),
        migrations.CreateModel(
            name='NUTS5000_N2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objid', models.CharField(max_length=16)),
                ('beginn', models.DateField()),
                ('gf', models.IntegerField()),
                ('nuts_level', models.IntegerField()),
                ('nuts_code', models.CharField(max_length=5)),
                ('nuts_name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=25832)),
            ],
        ),
        migrations.CreateModel(
            name='NUTS5000_N3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objid', models.CharField(max_length=16)),
                ('beginn', models.DateField()),
                ('gf', models.IntegerField()),
                ('nuts_level', models.IntegerField()),
                ('nuts_code', models.CharField(max_length=5)),
                ('nuts_name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=25832)),
            ],
        ),
    ]
