# Generated by Django 4.2 on 2023-06-22 11:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0021_nuts5000_n1_nuts5000_n2_nuts5000_n3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuts5000_n1',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='nuts5000_n2',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='nuts5000_n3',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
