# Generated by Django 4.2 on 2023-06-22 12:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0024_alter_nuts5000_n2_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuts5000_n3',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
