# Generated by Django 4.2 on 2024-10-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuekCapillaryRise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ka5textureclass_id', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('capillary_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buek_capillary_rise',
            },
        ),
    ]
