# Generated by Django 4.2 on 2024-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0002_rename_buekcapillaryrise_capillaryrise'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuekBulkDensityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_density_class', models.CharField(blank=True, null=True)),
                ('raw_density_g_per_cm3', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buek_bulk_density_class',
            },
        ),
    ]
