# Generated by Django 4.2 on 2024-10-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0003_buekbulkdensityclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuekKa5TextureClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ka5_soiltype', models.CharField(blank=True, max_length=255, null=True)),
                ('sand', models.FloatField(blank=True, null=True)),
                ('clay', models.FloatField(blank=True, null=True)),
                ('silt', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
