# Generated by Django 4.2 on 2024-10-09 12:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0004_buekka5textureclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuekHumusClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humus_class', models.CharField(blank=True, max_length=255, null=True)),
                ('corg', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuekPHClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_class', models.CharField(blank=True, max_length=255, null=True)),
                ('ph_lower_value', models.FloatField(blank=True, null=True)),
                ('ph_upper_value', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuekPolygon',
            fields=[
                ('polygon_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('bgl', models.CharField(blank=True, max_length=80, null=True)),
                ('symbol', models.CharField(blank=True, max_length=80, null=True)),
                ('legende', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuekSoilProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_gen_id', models.IntegerField(blank=True, null=True)),
                ('system_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_bodsysteinh', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_bodtyp', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_bo_subtyp', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_bo_subtyp_txt', models.CharField(blank=True, max_length=255, null=True)),
                ('area_percenteage', models.IntegerField(blank=True, null=True)),
                ('landusage', models.CharField(blank=True, max_length=255, null=True)),
                ('landusage_corine_code', models.IntegerField(blank=True, null=True)),
                ('soil_profile_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorineLandCover2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_level_1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('label_level_2_en', models.CharField(blank=True, max_length=255, null=True)),
                ('label_level_3_en', models.CharField(blank=True, max_length=255, null=True)),
                ('label_de', models.CharField(blank=True, max_length=255, null=True)),
                ('corine_landcover_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuekSoilProfileHorizon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizont_nr', models.IntegerField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('obergrenze_m', models.FloatField(blank=True, null=True)),
                ('untergrenze_m', models.FloatField(blank=True, null=True)),
                ('stratigraphie', models.CharField(blank=True, max_length=255, null=True)),
                ('herkunft', models.CharField(blank=True, max_length=255, null=True)),
                ('geogenese', models.CharField(blank=True, max_length=255, null=True)),
                ('fraktion', models.CharField(blank=True, max_length=255, null=True)),
                ('summe', models.FloatField(blank=True, null=True)),
                ('gefuege', models.CharField(blank=True, max_length=255, null=True)),
                ('torfarten', models.CharField(blank=True, max_length=255, null=True)),
                ('substanzvolumen', models.CharField(blank=True, max_length=255, null=True)),
                ('bueksoilprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.bueksoilprofile')),
                ('bulk_density_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.buekbulkdensityclass')),
                ('humus_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.buekhumusclass')),
                ('ka5_texture_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.buekka5textureclass')),
                ('ph_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.buekphclass')),
            ],
        ),
        migrations.AddField(
            model_name='bueksoilprofile',
            name='corine_landcover_2018',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.corinelandcover2018'),
        ),
        migrations.AddField(
            model_name='bueksoilprofile',
            name='polygon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.buekpolygon'),
        ),
        migrations.CreateModel(
            name='BuekCLCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tkle_nr', models.IntegerField(blank=True, null=True)),
                ('water', models.BooleanField(default=False)),
                ('clc_code', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('label_de', models.CharField(blank=True, max_length=255, null=True)),
                ('bias_21_soilprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_21_soilprofile', to='buek.bueksoilprofile')),
                ('bias_23_soilprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_23_soilprofile', to='buek.bueksoilprofile')),
                ('bias_31_soilprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_31_soilprofile', to='buek.bueksoilprofile')),
                ('corine_landcover_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.corinelandcover2018')),
                ('polygon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.buekpolygon')),
                ('soilprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.bueksoilprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Buek',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hinweis', models.CharField(blank=True, max_length=91, null=True)),
                ('shape_area', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('polygon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.buekpolygon')),
            ],
        ),
    ]
