# Generated by Django 4.2 on 2024-10-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0005_buekhumusclass_buekphclass_buekpolygon_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuekCLCData',
            new_name='MapSoilCLC',
        ),
    ]
