# Generated by Django 4.2 on 2024-10-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0006_rename_buekclcdata_mapsoilclc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapSoilCLC',
        ),
    ]
