# Generated by Django 4.2 on 2024-10-09 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0007_delete_mapsoilclc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSoilCLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tkle_nr', models.IntegerField(blank=True, null=True)),
                ('water', models.BooleanField(default=False)),
                ('clc_code', models.IntegerField(blank=True, null=True)),
                ('bias_21_clc_code', models.IntegerField(blank=True, null=True)),
                ('bias_23_clc_code', models.IntegerField(blank=True, null=True)),
                ('bias_31_clc_code', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('label_de', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('bias_21_clc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bias_21_clc', to='buek.corinelandcover2018')),
                ('bias_21_soilprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_21_soilprofile', to='buek.bueksoilprofile')),
                ('bias_23_clc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bias_23_clc', to='buek.corinelandcover2018')),
                ('bias_23_soilprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_23_soilprofile', to='buek.bueksoilprofile')),
                ('bias_31_clc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bias_31_clc', to='buek.corinelandcover2018')),
                ('bias_31_soilprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_31_soilprofile', to='buek.bueksoilprofile')),
                ('clc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clc', to='buek.corinelandcover2018')),
                ('corine_landcover_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.corinelandcover2018')),
                ('polygon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.buekpolygon')),
                ('soilprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soilprofile', to='buek.bueksoilprofile')),
            ],
        ),
    ]
