# Generated by Django 4.2 on 2024-10-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0008_mapsoilclc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buek',
            new_name='Buek200',
        ),
    ]
