# Generated by Django 4.2 on 2024-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0009_rename_buek_buek200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuekBulkDensityClass',
            new_name='BulkDensityClass',
        ),
    ]
