# Generated by Django 4.2 on 2024-10-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0010_rename_buekbulkdensityclass_bulkdensityclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuekKa5TextureClass',
            new_name='Ka5TextureClass',
        ),
    ]
