# Generated by Django 4.2 on 2024-10-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0011_rename_buekka5textureclass_ka5textureclass'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ka5textureclass',
            table='buek_ka5_texture_class',
        ),
    ]
