# Generated by Django 4.2 on 2024-10-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0012_alter_ka5textureclass_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuekHumusClass',
            new_name='HumusClass',
        ),
        migrations.AlterModelTable(
            name='humusclass',
            table='buek_humus_class',
        ),
    ]
