# Generated by Django 4.2 on 2024-10-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0013_rename_buekhumusclass_humusclass_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buekphclass',
            table='buek_ph_class',
        ),
        migrations.AlterModelTable(
            name='buekpolygon',
            table='buek_polygon',
        ),
        migrations.AlterModelTable(
            name='bueksoilprofile',
            table='buek_soil_profile',
        ),
        migrations.AlterModelTable(
            name='bueksoilprofilehorizon',
            table='buek_soil_profile_horizon',
        ),
        migrations.AlterModelTable(
            name='corinelandcover2018',
            table='buek_corine_land_cover_2018',
        ),
        migrations.AlterModelTable(
            name='mapsoilclc',
            table='buek_map_soil_clc',
        ),
    ]
