# Generated by Django 4.2 on 2024-10-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0014_alter_buekphclass_table_alter_buekpolygon_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuekPHClass',
            new_name='PHClass',
        ),
        migrations.RenameModel(
            old_name='BuekSoilProfile',
            new_name='SoilProfile',
        ),
        migrations.RenameModel(
            old_name='BuekSoilProfileHorizon',
            new_name='SoilProfileHorizon',
        ),
    ]
