# Generated by Django 4.2 on 2024-10-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0015_rename_buekphclass_phclass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilprofilehorizon',
            old_name='bueksoilprofile',
            new_name='soilprofile',
        ),
    ]
