# Generated by Django 4.2 on 2024-10-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0016_rename_bueksoilprofile_soilprofilehorizon_soilprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsoilclc',
            name='bias_21_clc',
        ),
        migrations.RemoveField(
            model_name='mapsoilclc',
            name='bias_31_clc',
        ),
        migrations.RemoveField(
            model_name='mapsoilclc',
            name='label',
        ),
        migrations.RemoveField(
            model_name='mapsoilclc',
            name='label_de',
        ),
    ]
