# Generated by Django 4.2 on 2024-10-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0017_remove_mapsoilclc_bias_21_clc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsoilclc',
            name='bias_23_clc',
        ),
    ]
