# Generated by Django 4.2 on 2024-10-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0018_remove_mapsoilclc_bias_23_clc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsoilclc',
            name='clc',
        ),
    ]
