# Generated by Django 4.2 on 2025-01-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0019_remove_mapsoilclc_clc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capillaryrise',
            old_name='ka5textureclass_id',
            new_name='ka5textureclass',
        ),
    ]
