# Generated by Django 4.2 on 2025-01-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0020_rename_ka5textureclass_id_capillaryrise_ka5textureclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capillaryrise',
            name='ka5textureclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buek.ka5textureclass'),
        ),
    ]
