# Generated by Django 4.2 on 2025-01-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0021_alter_capillaryrise_ka5textureclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilprofile',
            old_name='area_percenteage',
            new_name='area_percentage',
        ),
    ]
