# Generated by Django 4.2 on 2025-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0022_rename_area_percenteage_soilprofile_area_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeOleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(blank=True, max_length=255, null=True)),
                ('b', models.CharField(blank=True, max_length=255, null=True)),
                ('c', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
