# Generated by Django 4.2 on 2025-08-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0023_someoleclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeOleClass',
        ),
    ]
