# Generated by Django 4.2 on 2025-08-08 11:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0024_delete_someoleclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLCMap2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('code_18', models.CharField(blank=True, max_length=255, null=True)),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('corine_landcover_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buek.corinelandcover2018')),
            ],
        ),
    ]
