# Generated by Django 4.2 on 2025-08-08 11:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0025_clcmap2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clcmap2018',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
