# Generated by Django 4.2 on 2025-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buek', '0026_alter_clcmap2018_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='corinelandcover2018',
            name='label_level_1_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corinelandcover2018',
            name='label_level_2_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corinelandcover2018',
            name='label_level_3_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
