# Generated by Django 4.2 on 2025-10-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
